// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cryptos/fleet/v1/fleet.proto

package fleetv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/CryptOS-PKI/api/go/cryptos/fleet/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FleetServiceName is the fully-qualified name of the FleetService service.
	FleetServiceName = "cryptos.fleet.v1.FleetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FleetServiceListNodesProcedure is the fully-qualified name of the FleetService's ListNodes RPC.
	FleetServiceListNodesProcedure = "/cryptos.fleet.v1.FleetService/ListNodes"
	// FleetServiceGetNodeProcedure is the fully-qualified name of the FleetService's GetNode RPC.
	FleetServiceGetNodeProcedure = "/cryptos.fleet.v1.FleetService/GetNode"
	// FleetServiceListCertificatesProcedure is the fully-qualified name of the FleetService's
	// ListCertificates RPC.
	FleetServiceListCertificatesProcedure = "/cryptos.fleet.v1.FleetService/ListCertificates"
	// FleetServiceListProfilesProcedure is the fully-qualified name of the FleetService's ListProfiles
	// RPC.
	FleetServiceListProfilesProcedure = "/cryptos.fleet.v1.FleetService/ListProfiles"
	// FleetServiceListAdaptersProcedure is the fully-qualified name of the FleetService's ListAdapters
	// RPC.
	FleetServiceListAdaptersProcedure = "/cryptos.fleet.v1.FleetService/ListAdapters"
	// FleetServiceListAuditProcedure is the fully-qualified name of the FleetService's ListAudit RPC.
	FleetServiceListAuditProcedure = "/cryptos.fleet.v1.FleetService/ListAudit"
	// FleetServiceListEnrollmentsProcedure is the fully-qualified name of the FleetService's
	// ListEnrollments RPC.
	FleetServiceListEnrollmentsProcedure = "/cryptos.fleet.v1.FleetService/ListEnrollments"
)

// FleetServiceClient is a client for the cryptos.fleet.v1.FleetService service.
type FleetServiceClient interface {
	// ListNodes returns a summary for every node the manager knows about.
	ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error)
	// GetNode returns full detail, including the identity chain, for one node.
	GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error)
	// ListCertificates returns the aggregated certificate set across nodes,
	// optionally scoped to a single node.
	ListCertificates(context.Context, *connect.Request[v1.ListCertificatesRequest]) (*connect.Response[v1.ListCertificatesResponse], error)
	// ListProfiles returns the manager's catalog of certificate issuance
	// profiles.
	ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error)
	// ListAdapters returns the manager's catalog of enrollment protocol
	// adapters.
	ListAdapters(context.Context, *connect.Request[v1.ListAdaptersRequest]) (*connect.Response[v1.ListAdaptersResponse], error)
	// ListAudit returns the manager's audit log.
	ListAudit(context.Context, *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error)
	// ListEnrollments returns the manager's pending and resolved enrollment
	// requests.
	ListEnrollments(context.Context, *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error)
}

// NewFleetServiceClient constructs a client for the cryptos.fleet.v1.FleetService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFleetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FleetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fleetServiceMethods := v1.File_cryptos_fleet_v1_fleet_proto.Services().ByName("FleetService").Methods()
	return &fleetServiceClient{
		listNodes: connect.NewClient[v1.ListNodesRequest, v1.ListNodesResponse](
			httpClient,
			baseURL+FleetServiceListNodesProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListNodes")),
			connect.WithClientOptions(opts...),
		),
		getNode: connect.NewClient[v1.GetNodeRequest, v1.GetNodeResponse](
			httpClient,
			baseURL+FleetServiceGetNodeProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("GetNode")),
			connect.WithClientOptions(opts...),
		),
		listCertificates: connect.NewClient[v1.ListCertificatesRequest, v1.ListCertificatesResponse](
			httpClient,
			baseURL+FleetServiceListCertificatesProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListCertificates")),
			connect.WithClientOptions(opts...),
		),
		listProfiles: connect.NewClient[v1.ListProfilesRequest, v1.ListProfilesResponse](
			httpClient,
			baseURL+FleetServiceListProfilesProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListProfiles")),
			connect.WithClientOptions(opts...),
		),
		listAdapters: connect.NewClient[v1.ListAdaptersRequest, v1.ListAdaptersResponse](
			httpClient,
			baseURL+FleetServiceListAdaptersProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListAdapters")),
			connect.WithClientOptions(opts...),
		),
		listAudit: connect.NewClient[v1.ListAuditRequest, v1.ListAuditResponse](
			httpClient,
			baseURL+FleetServiceListAuditProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListAudit")),
			connect.WithClientOptions(opts...),
		),
		listEnrollments: connect.NewClient[v1.ListEnrollmentsRequest, v1.ListEnrollmentsResponse](
			httpClient,
			baseURL+FleetServiceListEnrollmentsProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListEnrollments")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fleetServiceClient implements FleetServiceClient.
type fleetServiceClient struct {
	listNodes        *connect.Client[v1.ListNodesRequest, v1.ListNodesResponse]
	getNode          *connect.Client[v1.GetNodeRequest, v1.GetNodeResponse]
	listCertificates *connect.Client[v1.ListCertificatesRequest, v1.ListCertificatesResponse]
	listProfiles     *connect.Client[v1.ListProfilesRequest, v1.ListProfilesResponse]
	listAdapters     *connect.Client[v1.ListAdaptersRequest, v1.ListAdaptersResponse]
	listAudit        *connect.Client[v1.ListAuditRequest, v1.ListAuditResponse]
	listEnrollments  *connect.Client[v1.ListEnrollmentsRequest, v1.ListEnrollmentsResponse]
}

// ListNodes calls cryptos.fleet.v1.FleetService.ListNodes.
func (c *fleetServiceClient) ListNodes(ctx context.Context, req *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error) {
	return c.listNodes.CallUnary(ctx, req)
}

// GetNode calls cryptos.fleet.v1.FleetService.GetNode.
func (c *fleetServiceClient) GetNode(ctx context.Context, req *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error) {
	return c.getNode.CallUnary(ctx, req)
}

// ListCertificates calls cryptos.fleet.v1.FleetService.ListCertificates.
func (c *fleetServiceClient) ListCertificates(ctx context.Context, req *connect.Request[v1.ListCertificatesRequest]) (*connect.Response[v1.ListCertificatesResponse], error) {
	return c.listCertificates.CallUnary(ctx, req)
}

// ListProfiles calls cryptos.fleet.v1.FleetService.ListProfiles.
func (c *fleetServiceClient) ListProfiles(ctx context.Context, req *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error) {
	return c.listProfiles.CallUnary(ctx, req)
}

// ListAdapters calls cryptos.fleet.v1.FleetService.ListAdapters.
func (c *fleetServiceClient) ListAdapters(ctx context.Context, req *connect.Request[v1.ListAdaptersRequest]) (*connect.Response[v1.ListAdaptersResponse], error) {
	return c.listAdapters.CallUnary(ctx, req)
}

// ListAudit calls cryptos.fleet.v1.FleetService.ListAudit.
func (c *fleetServiceClient) ListAudit(ctx context.Context, req *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error) {
	return c.listAudit.CallUnary(ctx, req)
}

// ListEnrollments calls cryptos.fleet.v1.FleetService.ListEnrollments.
func (c *fleetServiceClient) ListEnrollments(ctx context.Context, req *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error) {
	return c.listEnrollments.CallUnary(ctx, req)
}

// FleetServiceHandler is an implementation of the cryptos.fleet.v1.FleetService service.
type FleetServiceHandler interface {
	// ListNodes returns a summary for every node the manager knows about.
	ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error)
	// GetNode returns full detail, including the identity chain, for one node.
	GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error)
	// ListCertificates returns the aggregated certificate set across nodes,
	// optionally scoped to a single node.
	ListCertificates(context.Context, *connect.Request[v1.ListCertificatesRequest]) (*connect.Response[v1.ListCertificatesResponse], error)
	// ListProfiles returns the manager's catalog of certificate issuance
	// profiles.
	ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error)
	// ListAdapters returns the manager's catalog of enrollment protocol
	// adapters.
	ListAdapters(context.Context, *connect.Request[v1.ListAdaptersRequest]) (*connect.Response[v1.ListAdaptersResponse], error)
	// ListAudit returns the manager's audit log.
	ListAudit(context.Context, *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error)
	// ListEnrollments returns the manager's pending and resolved enrollment
	// requests.
	ListEnrollments(context.Context, *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error)
}

// NewFleetServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFleetServiceHandler(svc FleetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fleetServiceMethods := v1.File_cryptos_fleet_v1_fleet_proto.Services().ByName("FleetService").Methods()
	fleetServiceListNodesHandler := connect.NewUnaryHandler(
		FleetServiceListNodesProcedure,
		svc.ListNodes,
		connect.WithSchema(fleetServiceMethods.ByName("ListNodes")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceGetNodeHandler := connect.NewUnaryHandler(
		FleetServiceGetNodeProcedure,
		svc.GetNode,
		connect.WithSchema(fleetServiceMethods.ByName("GetNode")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceListCertificatesHandler := connect.NewUnaryHandler(
		FleetServiceListCertificatesProcedure,
		svc.ListCertificates,
		connect.WithSchema(fleetServiceMethods.ByName("ListCertificates")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceListProfilesHandler := connect.NewUnaryHandler(
		FleetServiceListProfilesProcedure,
		svc.ListProfiles,
		connect.WithSchema(fleetServiceMethods.ByName("ListProfiles")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceListAdaptersHandler := connect.NewUnaryHandler(
		FleetServiceListAdaptersProcedure,
		svc.ListAdapters,
		connect.WithSchema(fleetServiceMethods.ByName("ListAdapters")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceListAuditHandler := connect.NewUnaryHandler(
		FleetServiceListAuditProcedure,
		svc.ListAudit,
		connect.WithSchema(fleetServiceMethods.ByName("ListAudit")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceListEnrollmentsHandler := connect.NewUnaryHandler(
		FleetServiceListEnrollmentsProcedure,
		svc.ListEnrollments,
		connect.WithSchema(fleetServiceMethods.ByName("ListEnrollments")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cryptos.fleet.v1.FleetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FleetServiceListNodesProcedure:
			fleetServiceListNodesHandler.ServeHTTP(w, r)
		case FleetServiceGetNodeProcedure:
			fleetServiceGetNodeHandler.ServeHTTP(w, r)
		case FleetServiceListCertificatesProcedure:
			fleetServiceListCertificatesHandler.ServeHTTP(w, r)
		case FleetServiceListProfilesProcedure:
			fleetServiceListProfilesHandler.ServeHTTP(w, r)
		case FleetServiceListAdaptersProcedure:
			fleetServiceListAdaptersHandler.ServeHTTP(w, r)
		case FleetServiceListAuditProcedure:
			fleetServiceListAuditHandler.ServeHTTP(w, r)
		case FleetServiceListEnrollmentsProcedure:
			fleetServiceListEnrollmentsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFleetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFleetServiceHandler struct{}

func (UnimplementedFleetServiceHandler) ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListNodes is not implemented"))
}

func (UnimplementedFleetServiceHandler) GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.GetNode is not implemented"))
}

func (UnimplementedFleetServiceHandler) ListCertificates(context.Context, *connect.Request[v1.ListCertificatesRequest]) (*connect.Response[v1.ListCertificatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListCertificates is not implemented"))
}

func (UnimplementedFleetServiceHandler) ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListProfiles is not implemented"))
}

func (UnimplementedFleetServiceHandler) ListAdapters(context.Context, *connect.Request[v1.ListAdaptersRequest]) (*connect.Response[v1.ListAdaptersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListAdapters is not implemented"))
}

func (UnimplementedFleetServiceHandler) ListAudit(context.Context, *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListAudit is not implemented"))
}

func (UnimplementedFleetServiceHandler) ListEnrollments(context.Context, *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListEnrollments is not implemented"))
}
