// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cryptos/fleet/v1/fleet.proto

package fleetv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/CryptOS-PKI/api/go/cryptos/fleet/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FleetServiceName is the fully-qualified name of the FleetService service.
	FleetServiceName = "cryptos.fleet.v1.FleetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FleetServiceListNodesProcedure is the fully-qualified name of the FleetService's ListNodes RPC.
	FleetServiceListNodesProcedure = "/cryptos.fleet.v1.FleetService/ListNodes"
	// FleetServiceGetNodeProcedure is the fully-qualified name of the FleetService's GetNode RPC.
	FleetServiceGetNodeProcedure = "/cryptos.fleet.v1.FleetService/GetNode"
)

// FleetServiceClient is a client for the cryptos.fleet.v1.FleetService service.
type FleetServiceClient interface {
	// ListNodes returns a summary for every node the manager knows about.
	ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error)
	// GetNode returns full detail, including the identity chain, for one node.
	GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error)
}

// NewFleetServiceClient constructs a client for the cryptos.fleet.v1.FleetService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFleetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FleetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fleetServiceMethods := v1.File_cryptos_fleet_v1_fleet_proto.Services().ByName("FleetService").Methods()
	return &fleetServiceClient{
		listNodes: connect.NewClient[v1.ListNodesRequest, v1.ListNodesResponse](
			httpClient,
			baseURL+FleetServiceListNodesProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListNodes")),
			connect.WithClientOptions(opts...),
		),
		getNode: connect.NewClient[v1.GetNodeRequest, v1.GetNodeResponse](
			httpClient,
			baseURL+FleetServiceGetNodeProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("GetNode")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fleetServiceClient implements FleetServiceClient.
type fleetServiceClient struct {
	listNodes *connect.Client[v1.ListNodesRequest, v1.ListNodesResponse]
	getNode   *connect.Client[v1.GetNodeRequest, v1.GetNodeResponse]
}

// ListNodes calls cryptos.fleet.v1.FleetService.ListNodes.
func (c *fleetServiceClient) ListNodes(ctx context.Context, req *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error) {
	return c.listNodes.CallUnary(ctx, req)
}

// GetNode calls cryptos.fleet.v1.FleetService.GetNode.
func (c *fleetServiceClient) GetNode(ctx context.Context, req *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error) {
	return c.getNode.CallUnary(ctx, req)
}

// FleetServiceHandler is an implementation of the cryptos.fleet.v1.FleetService service.
type FleetServiceHandler interface {
	// ListNodes returns a summary for every node the manager knows about.
	ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error)
	// GetNode returns full detail, including the identity chain, for one node.
	GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error)
}

// NewFleetServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFleetServiceHandler(svc FleetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fleetServiceMethods := v1.File_cryptos_fleet_v1_fleet_proto.Services().ByName("FleetService").Methods()
	fleetServiceListNodesHandler := connect.NewUnaryHandler(
		FleetServiceListNodesProcedure,
		svc.ListNodes,
		connect.WithSchema(fleetServiceMethods.ByName("ListNodes")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceGetNodeHandler := connect.NewUnaryHandler(
		FleetServiceGetNodeProcedure,
		svc.GetNode,
		connect.WithSchema(fleetServiceMethods.ByName("GetNode")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cryptos.fleet.v1.FleetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FleetServiceListNodesProcedure:
			fleetServiceListNodesHandler.ServeHTTP(w, r)
		case FleetServiceGetNodeProcedure:
			fleetServiceGetNodeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFleetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFleetServiceHandler struct{}

func (UnimplementedFleetServiceHandler) ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListNodes is not implemented"))
}

func (UnimplementedFleetServiceHandler) GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.GetNode is not implemented"))
}
