// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cryptos/fleet/v1/fleet.proto

package fleetv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/CryptOS-PKI/api/go/cryptos/fleet/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FleetServiceName is the fully-qualified name of the FleetService service.
	FleetServiceName = "cryptos.fleet.v1.FleetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FleetServiceListNodesProcedure is the fully-qualified name of the FleetService's ListNodes RPC.
	FleetServiceListNodesProcedure = "/cryptos.fleet.v1.FleetService/ListNodes"
	// FleetServiceGetNodeProcedure is the fully-qualified name of the FleetService's GetNode RPC.
	FleetServiceGetNodeProcedure = "/cryptos.fleet.v1.FleetService/GetNode"
	// FleetServiceListCertificatesProcedure is the fully-qualified name of the FleetService's
	// ListCertificates RPC.
	FleetServiceListCertificatesProcedure = "/cryptos.fleet.v1.FleetService/ListCertificates"
	// FleetServiceListProfilesProcedure is the fully-qualified name of the FleetService's ListProfiles
	// RPC.
	FleetServiceListProfilesProcedure = "/cryptos.fleet.v1.FleetService/ListProfiles"
	// FleetServiceCreateProfileProcedure is the fully-qualified name of the FleetService's
	// CreateProfile RPC.
	FleetServiceCreateProfileProcedure = "/cryptos.fleet.v1.FleetService/CreateProfile"
	// FleetServiceUpdateProfileProcedure is the fully-qualified name of the FleetService's
	// UpdateProfile RPC.
	FleetServiceUpdateProfileProcedure = "/cryptos.fleet.v1.FleetService/UpdateProfile"
	// FleetServiceDeleteProfileProcedure is the fully-qualified name of the FleetService's
	// DeleteProfile RPC.
	FleetServiceDeleteProfileProcedure = "/cryptos.fleet.v1.FleetService/DeleteProfile"
	// FleetServiceApplyProfileToNodeProcedure is the fully-qualified name of the FleetService's
	// ApplyProfileToNode RPC.
	FleetServiceApplyProfileToNodeProcedure = "/cryptos.fleet.v1.FleetService/ApplyProfileToNode"
	// FleetServiceListAdaptersProcedure is the fully-qualified name of the FleetService's ListAdapters
	// RPC.
	FleetServiceListAdaptersProcedure = "/cryptos.fleet.v1.FleetService/ListAdapters"
	// FleetServiceSetAdapterEnabledProcedure is the fully-qualified name of the FleetService's
	// SetAdapterEnabled RPC.
	FleetServiceSetAdapterEnabledProcedure = "/cryptos.fleet.v1.FleetService/SetAdapterEnabled"
	// FleetServiceListAuditProcedure is the fully-qualified name of the FleetService's ListAudit RPC.
	FleetServiceListAuditProcedure = "/cryptos.fleet.v1.FleetService/ListAudit"
	// FleetServiceListEnrollmentsProcedure is the fully-qualified name of the FleetService's
	// ListEnrollments RPC.
	FleetServiceListEnrollmentsProcedure = "/cryptos.fleet.v1.FleetService/ListEnrollments"
	// FleetServiceCreateEnrollmentProcedure is the fully-qualified name of the FleetService's
	// CreateEnrollment RPC.
	FleetServiceCreateEnrollmentProcedure = "/cryptos.fleet.v1.FleetService/CreateEnrollment"
	// FleetServiceApproveEnrollmentProcedure is the fully-qualified name of the FleetService's
	// ApproveEnrollment RPC.
	FleetServiceApproveEnrollmentProcedure = "/cryptos.fleet.v1.FleetService/ApproveEnrollment"
	// FleetServiceRejectEnrollmentProcedure is the fully-qualified name of the FleetService's
	// RejectEnrollment RPC.
	FleetServiceRejectEnrollmentProcedure = "/cryptos.fleet.v1.FleetService/RejectEnrollment"
	// FleetServiceWhoAmIProcedure is the fully-qualified name of the FleetService's WhoAmI RPC.
	FleetServiceWhoAmIProcedure = "/cryptos.fleet.v1.FleetService/WhoAmI"
	// FleetServiceRevokeCertificateProcedure is the fully-qualified name of the FleetService's
	// RevokeCertificate RPC.
	FleetServiceRevokeCertificateProcedure = "/cryptos.fleet.v1.FleetService/RevokeCertificate"
	// FleetServiceIssueLeafProcedure is the fully-qualified name of the FleetService's IssueLeaf RPC.
	FleetServiceIssueLeafProcedure = "/cryptos.fleet.v1.FleetService/IssueLeaf"
	// FleetServiceRekeyNodeProcedure is the fully-qualified name of the FleetService's RekeyNode RPC.
	FleetServiceRekeyNodeProcedure = "/cryptos.fleet.v1.FleetService/RekeyNode"
	// FleetServiceGetNodeConfigProcedure is the fully-qualified name of the FleetService's
	// GetNodeConfig RPC.
	FleetServiceGetNodeConfigProcedure = "/cryptos.fleet.v1.FleetService/GetNodeConfig"
	// FleetServiceApplyNodeConfigProcedure is the fully-qualified name of the FleetService's
	// ApplyNodeConfig RPC.
	FleetServiceApplyNodeConfigProcedure = "/cryptos.fleet.v1.FleetService/ApplyNodeConfig"
	// FleetServiceExportCAKeyProcedure is the fully-qualified name of the FleetService's ExportCAKey
	// RPC.
	FleetServiceExportCAKeyProcedure = "/cryptos.fleet.v1.FleetService/ExportCAKey"
	// FleetServiceImportCAKeyProcedure is the fully-qualified name of the FleetService's ImportCAKey
	// RPC.
	FleetServiceImportCAKeyProcedure = "/cryptos.fleet.v1.FleetService/ImportCAKey"
	// FleetServiceIssueOperatorCredentialProcedure is the fully-qualified name of the FleetService's
	// IssueOperatorCredential RPC.
	FleetServiceIssueOperatorCredentialProcedure = "/cryptos.fleet.v1.FleetService/IssueOperatorCredential"
	// FleetServiceRevokeOperatorCredentialProcedure is the fully-qualified name of the FleetService's
	// RevokeOperatorCredential RPC.
	FleetServiceRevokeOperatorCredentialProcedure = "/cryptos.fleet.v1.FleetService/RevokeOperatorCredential"
	// FleetServiceListOperatorCredentialsProcedure is the fully-qualified name of the FleetService's
	// ListOperatorCredentials RPC.
	FleetServiceListOperatorCredentialsProcedure = "/cryptos.fleet.v1.FleetService/ListOperatorCredentials"
	// FleetServicePreviewAdoptionProcedure is the fully-qualified name of the FleetService's
	// PreviewAdoption RPC.
	FleetServicePreviewAdoptionProcedure = "/cryptos.fleet.v1.FleetService/PreviewAdoption"
	// FleetServiceAdoptNodeProcedure is the fully-qualified name of the FleetService's AdoptNode RPC.
	FleetServiceAdoptNodeProcedure = "/cryptos.fleet.v1.FleetService/AdoptNode"
	// FleetServiceDecommissionNodeProcedure is the fully-qualified name of the FleetService's
	// DecommissionNode RPC.
	FleetServiceDecommissionNodeProcedure = "/cryptos.fleet.v1.FleetService/DecommissionNode"
)

// FleetServiceClient is a client for the cryptos.fleet.v1.FleetService service.
type FleetServiceClient interface {
	// ListNodes returns a summary for every node the manager knows about.
	ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error)
	// GetNode returns full detail, including the identity chain, for one node.
	GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error)
	// ListCertificates returns the aggregated certificate set across nodes,
	// optionally scoped to a single node.
	ListCertificates(context.Context, *connect.Request[v1.ListCertificatesRequest]) (*connect.Response[v1.ListCertificatesResponse], error)
	// ListProfiles returns the manager's catalog of certificate issuance
	// profiles. Each is a cryptos.v1.CertificateProfile, the same shape a node
	// stores in pki.profiles[], so the catalog is a lossless superset the node
	// accepts verbatim. Operator-readable.
	ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error)
	// CreateProfile adds a new certificate profile to the manager's catalog.
	// The profile name must be unique. Admin-gated and audited.
	CreateProfile(context.Context, *connect.Request[v1.CreateProfileRequest]) (*connect.Response[v1.CreateProfileResponse], error)
	// UpdateProfile replaces an existing catalog profile, matched by name.
	// Admin-gated and audited.
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error)
	// DeleteProfile removes a catalog profile by name. Non-cascading: it does
	// not touch any node's existing pki.profiles[]. Admin-gated and audited.
	DeleteProfile(context.Context, *connect.Request[v1.DeleteProfileRequest]) (*connect.Response[v1.DeleteProfileResponse], error)
	// ApplyProfileToNode pushes a catalog profile onto a managed node: the
	// manager fetches the node's full config, inserts-or-replaces the named
	// profile in pki.profiles[] (matched by name), and applies the whole config
	// back via the node's ApplyConfig. Admin-gated and audited.
	ApplyProfileToNode(context.Context, *connect.Request[v1.ApplyProfileToNodeRequest]) (*connect.Response[v1.ApplyProfileToNodeResponse], error)
	// ListAdapters returns the manager's catalog of enrollment protocol
	// adapters.
	ListAdapters(context.Context, *connect.Request[v1.ListAdaptersRequest]) (*connect.Response[v1.ListAdaptersResponse], error)
	// SetAdapterEnabled records whether an enrollment protocol adapter is
	// enabled, matched by adapter name. This persists intent; the protocol
	// engines that serve enrollment requests ship in a later program, so an
	// enabled adapter does not yet answer requests. Admin-gated and audited.
	SetAdapterEnabled(context.Context, *connect.Request[v1.SetAdapterEnabledRequest]) (*connect.Response[v1.SetAdapterEnabledResponse], error)
	// ListAudit returns the manager's audit log.
	ListAudit(context.Context, *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error)
	// ListEnrollments returns the manager's pending and resolved enrollment
	// requests.
	ListEnrollments(context.Context, *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error)
	// CreateEnrollment opens a new enrollment request (LINK a node or provision a
	// SUBORDINATE CA); the manager verifies attestation for LINK.
	CreateEnrollment(context.Context, *connect.Request[v1.CreateEnrollmentRequest]) (*connect.Response[v1.CreateEnrollmentResponse], error)
	// ApproveEnrollment approves a pending request (LINK -> ApplyConfig managed
	// state; SUBORDINATE -> CSR-ferry).
	ApproveEnrollment(context.Context, *connect.Request[v1.ApproveEnrollmentRequest]) (*connect.Response[v1.ApproveEnrollmentResponse], error)
	// RejectEnrollment rejects a pending request with a reason.
	RejectEnrollment(context.Context, *connect.Request[v1.RejectEnrollmentRequest]) (*connect.Response[v1.RejectEnrollmentResponse], error)
	// WhoAmI echoes the operator identity the manager verified from the
	// presented client certificate (subject CN, cert serial, access level).
	WhoAmI(context.Context, *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error)
	// RevokeCertificate revokes an issued certificate on the node that issued
	// it, identified by node name and hex serial, with an RFC 5280 reason code.
	RevokeCertificate(context.Context, *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error)
	// IssueLeaf signs a leaf certificate on the named issuing node from a
	// browser-generated PKCS#10 CSR under a named issuance profile. Only the
	// CSR crosses the wire; the leaf private key stays in the browser.
	IssueLeaf(context.Context, *connect.Request[v1.IssueLeafRequest]) (*connect.Response[v1.IssueLeafResponse], error)
	// RekeyNode re-keys a subordinate CA node in one orchestrated call: the
	// manager has the child mint a new key + CSR, routes the CSR to the parent
	// (resolved from the child's issuer CN) for signing under profile_name, and
	// delivers the signed chain back to the child. The parent must be a node the
	// manager already knows about.
	RekeyNode(context.Context, *connect.Request[v1.RekeyNodeRequest]) (*connect.Response[v1.RekeyNodeResponse], error)
	// GetNodeConfig fetches the current machine configuration of a managed node,
	// so an operator can view it (and the web can edit a subset before applying
	// the whole config back). Operator-gated; a read, so it is not audited.
	GetNodeConfig(context.Context, *connect.Request[v1.GetNodeConfigRequest]) (*connect.Response[v1.GetNodeConfigResponse], error)
	// ApplyNodeConfig applies a full machine configuration to a managed node.
	// The config is the fetched baseline with the operator's edits merged in; the
	// node's ApplyConfig is a whole-config replace, so the caller must send the
	// complete config, never a partial one. Admin-gated and audited.
	ApplyNodeConfig(context.Context, *connect.Request[v1.ApplyNodeConfigRequest]) (*connect.Response[v1.ApplyNodeConfigResponse], error)
	// ExportCAKey backs up a managed node's CA private key to an encrypted
	// envelope. The node seals the backup with the operator passphrase
	// (Argon2id + AES-256-GCM) so the plaintext key never leaves the node; the
	// manager only relays the envelope through to the caller. The passphrase is
	// used in transit and is never persisted. A TPM-backed node refuses export.
	// Admin-gated and audited (the audit names the node only, never the secret).
	ExportCAKey(context.Context, *connect.Request[v1.ExportCAKeyRequest]) (*connect.Response[v1.ExportCAKeyResponse], error)
	// ImportCAKey restores a CA identity onto a fresh managed node from an
	// encrypted envelope produced by ExportCAKey. The node decrypts the envelope
	// with the operator passphrase and adopts the key; it refuses the import if
	// it already holds an identity. The passphrase transits the manager only to
	// reach the node and is never persisted. Admin-gated and audited (the audit
	// names the node and restored subject only, never the secret or envelope).
	ImportCAKey(context.Context, *connect.Request[v1.ImportCAKeyRequest]) (*connect.Response[v1.ImportCAKeyResponse], error)
	// IssueOperatorCredential issues an operator client certificate. The browser
	// generates the key and CSR; the manager routes signing to the node acting as
	// the operator CA under an operator-<level> profile that carries the
	// access-level extension. Only the CSR crosses the wire; the operator key
	// stays in the browser. Admin-gated and audited (the audit names the subject
	// and serial only, never the CSR or certificate bytes).
	IssueOperatorCredential(context.Context, *connect.Request[v1.IssueOperatorCredentialRequest]) (*connect.Response[v1.IssueOperatorCredentialResponse], error)
	// RevokeOperatorCredential revokes an operator credential on the operator-CA
	// node by hex serial, with an RFC 5280 reason code. The manager enforces the
	// revocation in the authz middleware, so a revoked operator can no longer
	// authenticate. Admin-gated and audited.
	RevokeOperatorCredential(context.Context, *connect.Request[v1.RevokeOperatorCredentialRequest]) (*connect.Response[v1.RevokeOperatorCredentialResponse], error)
	// ListOperatorCredentials returns the operator credentials the manager has
	// issued, with their level, expiry, and revocation state. Operator-readable.
	ListOperatorCredentials(context.Context, *connect.Request[v1.ListOperatorCredentialsRequest]) (*connect.Response[v1.ListOperatorCredentialsResponse], error)
	// PreviewAdoption performs the trust-on-first-use step of adopting a new
	// node: it dials the maintenance endpoint (no pin yet), captures the
	// self-signed certificate the node presents, and returns its SHA-256
	// fingerprint and subject so the operator can confirm it before adoption.
	// Admin-gated; a read, so it is not audited.
	PreviewAdoption(context.Context, *connect.Request[v1.PreviewAdoptionRequest]) (*connect.Response[v1.PreviewAdoptionResponse], error)
	// AdoptNode provisions a new maintenance node end to end and streams progress.
	// Pinned to the fingerprint the operator confirmed via PreviewAdoption, the
	// manager applies the initial config, awaits the reboot, drives the first-boot
	// ceremony, and registers the node. Each streamed message carries a phase
	// (applying-config, installing, awaiting-reboot, ceremony, established) with
	// human-readable detail; the final message sets done. Admin-gated and audited.
	AdoptNode(context.Context, *connect.Request[v1.AdoptNodeRequest]) (*connect.ServerStreamForClient[v1.AdoptNodeResponse], error)
	// DecommissionNode remotely wipes a managed node's identity and data via the
	// node's mTLS-served RemoteReset, then reboots it into maintenance. The caller
	// must echo the node's current Root CA CN as confirmation. Admin-gated and
	// audited (the audit names the node and that it was wiped, never any secret).
	DecommissionNode(context.Context, *connect.Request[v1.DecommissionNodeRequest]) (*connect.Response[v1.DecommissionNodeResponse], error)
}

// NewFleetServiceClient constructs a client for the cryptos.fleet.v1.FleetService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFleetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FleetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	fleetServiceMethods := v1.File_cryptos_fleet_v1_fleet_proto.Services().ByName("FleetService").Methods()
	return &fleetServiceClient{
		listNodes: connect.NewClient[v1.ListNodesRequest, v1.ListNodesResponse](
			httpClient,
			baseURL+FleetServiceListNodesProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListNodes")),
			connect.WithClientOptions(opts...),
		),
		getNode: connect.NewClient[v1.GetNodeRequest, v1.GetNodeResponse](
			httpClient,
			baseURL+FleetServiceGetNodeProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("GetNode")),
			connect.WithClientOptions(opts...),
		),
		listCertificates: connect.NewClient[v1.ListCertificatesRequest, v1.ListCertificatesResponse](
			httpClient,
			baseURL+FleetServiceListCertificatesProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListCertificates")),
			connect.WithClientOptions(opts...),
		),
		listProfiles: connect.NewClient[v1.ListProfilesRequest, v1.ListProfilesResponse](
			httpClient,
			baseURL+FleetServiceListProfilesProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListProfiles")),
			connect.WithClientOptions(opts...),
		),
		createProfile: connect.NewClient[v1.CreateProfileRequest, v1.CreateProfileResponse](
			httpClient,
			baseURL+FleetServiceCreateProfileProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("CreateProfile")),
			connect.WithClientOptions(opts...),
		),
		updateProfile: connect.NewClient[v1.UpdateProfileRequest, v1.UpdateProfileResponse](
			httpClient,
			baseURL+FleetServiceUpdateProfileProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("UpdateProfile")),
			connect.WithClientOptions(opts...),
		),
		deleteProfile: connect.NewClient[v1.DeleteProfileRequest, v1.DeleteProfileResponse](
			httpClient,
			baseURL+FleetServiceDeleteProfileProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("DeleteProfile")),
			connect.WithClientOptions(opts...),
		),
		applyProfileToNode: connect.NewClient[v1.ApplyProfileToNodeRequest, v1.ApplyProfileToNodeResponse](
			httpClient,
			baseURL+FleetServiceApplyProfileToNodeProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ApplyProfileToNode")),
			connect.WithClientOptions(opts...),
		),
		listAdapters: connect.NewClient[v1.ListAdaptersRequest, v1.ListAdaptersResponse](
			httpClient,
			baseURL+FleetServiceListAdaptersProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListAdapters")),
			connect.WithClientOptions(opts...),
		),
		setAdapterEnabled: connect.NewClient[v1.SetAdapterEnabledRequest, v1.SetAdapterEnabledResponse](
			httpClient,
			baseURL+FleetServiceSetAdapterEnabledProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("SetAdapterEnabled")),
			connect.WithClientOptions(opts...),
		),
		listAudit: connect.NewClient[v1.ListAuditRequest, v1.ListAuditResponse](
			httpClient,
			baseURL+FleetServiceListAuditProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListAudit")),
			connect.WithClientOptions(opts...),
		),
		listEnrollments: connect.NewClient[v1.ListEnrollmentsRequest, v1.ListEnrollmentsResponse](
			httpClient,
			baseURL+FleetServiceListEnrollmentsProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListEnrollments")),
			connect.WithClientOptions(opts...),
		),
		createEnrollment: connect.NewClient[v1.CreateEnrollmentRequest, v1.CreateEnrollmentResponse](
			httpClient,
			baseURL+FleetServiceCreateEnrollmentProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("CreateEnrollment")),
			connect.WithClientOptions(opts...),
		),
		approveEnrollment: connect.NewClient[v1.ApproveEnrollmentRequest, v1.ApproveEnrollmentResponse](
			httpClient,
			baseURL+FleetServiceApproveEnrollmentProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ApproveEnrollment")),
			connect.WithClientOptions(opts...),
		),
		rejectEnrollment: connect.NewClient[v1.RejectEnrollmentRequest, v1.RejectEnrollmentResponse](
			httpClient,
			baseURL+FleetServiceRejectEnrollmentProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("RejectEnrollment")),
			connect.WithClientOptions(opts...),
		),
		whoAmI: connect.NewClient[v1.WhoAmIRequest, v1.WhoAmIResponse](
			httpClient,
			baseURL+FleetServiceWhoAmIProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("WhoAmI")),
			connect.WithClientOptions(opts...),
		),
		revokeCertificate: connect.NewClient[v1.RevokeCertificateRequest, v1.RevokeCertificateResponse](
			httpClient,
			baseURL+FleetServiceRevokeCertificateProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("RevokeCertificate")),
			connect.WithClientOptions(opts...),
		),
		issueLeaf: connect.NewClient[v1.IssueLeafRequest, v1.IssueLeafResponse](
			httpClient,
			baseURL+FleetServiceIssueLeafProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("IssueLeaf")),
			connect.WithClientOptions(opts...),
		),
		rekeyNode: connect.NewClient[v1.RekeyNodeRequest, v1.RekeyNodeResponse](
			httpClient,
			baseURL+FleetServiceRekeyNodeProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("RekeyNode")),
			connect.WithClientOptions(opts...),
		),
		getNodeConfig: connect.NewClient[v1.GetNodeConfigRequest, v1.GetNodeConfigResponse](
			httpClient,
			baseURL+FleetServiceGetNodeConfigProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("GetNodeConfig")),
			connect.WithClientOptions(opts...),
		),
		applyNodeConfig: connect.NewClient[v1.ApplyNodeConfigRequest, v1.ApplyNodeConfigResponse](
			httpClient,
			baseURL+FleetServiceApplyNodeConfigProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ApplyNodeConfig")),
			connect.WithClientOptions(opts...),
		),
		exportCAKey: connect.NewClient[v1.ExportCAKeyRequest, v1.ExportCAKeyResponse](
			httpClient,
			baseURL+FleetServiceExportCAKeyProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ExportCAKey")),
			connect.WithClientOptions(opts...),
		),
		importCAKey: connect.NewClient[v1.ImportCAKeyRequest, v1.ImportCAKeyResponse](
			httpClient,
			baseURL+FleetServiceImportCAKeyProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ImportCAKey")),
			connect.WithClientOptions(opts...),
		),
		issueOperatorCredential: connect.NewClient[v1.IssueOperatorCredentialRequest, v1.IssueOperatorCredentialResponse](
			httpClient,
			baseURL+FleetServiceIssueOperatorCredentialProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("IssueOperatorCredential")),
			connect.WithClientOptions(opts...),
		),
		revokeOperatorCredential: connect.NewClient[v1.RevokeOperatorCredentialRequest, v1.RevokeOperatorCredentialResponse](
			httpClient,
			baseURL+FleetServiceRevokeOperatorCredentialProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("RevokeOperatorCredential")),
			connect.WithClientOptions(opts...),
		),
		listOperatorCredentials: connect.NewClient[v1.ListOperatorCredentialsRequest, v1.ListOperatorCredentialsResponse](
			httpClient,
			baseURL+FleetServiceListOperatorCredentialsProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("ListOperatorCredentials")),
			connect.WithClientOptions(opts...),
		),
		previewAdoption: connect.NewClient[v1.PreviewAdoptionRequest, v1.PreviewAdoptionResponse](
			httpClient,
			baseURL+FleetServicePreviewAdoptionProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("PreviewAdoption")),
			connect.WithClientOptions(opts...),
		),
		adoptNode: connect.NewClient[v1.AdoptNodeRequest, v1.AdoptNodeResponse](
			httpClient,
			baseURL+FleetServiceAdoptNodeProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("AdoptNode")),
			connect.WithClientOptions(opts...),
		),
		decommissionNode: connect.NewClient[v1.DecommissionNodeRequest, v1.DecommissionNodeResponse](
			httpClient,
			baseURL+FleetServiceDecommissionNodeProcedure,
			connect.WithSchema(fleetServiceMethods.ByName("DecommissionNode")),
			connect.WithClientOptions(opts...),
		),
	}
}

// fleetServiceClient implements FleetServiceClient.
type fleetServiceClient struct {
	listNodes                *connect.Client[v1.ListNodesRequest, v1.ListNodesResponse]
	getNode                  *connect.Client[v1.GetNodeRequest, v1.GetNodeResponse]
	listCertificates         *connect.Client[v1.ListCertificatesRequest, v1.ListCertificatesResponse]
	listProfiles             *connect.Client[v1.ListProfilesRequest, v1.ListProfilesResponse]
	createProfile            *connect.Client[v1.CreateProfileRequest, v1.CreateProfileResponse]
	updateProfile            *connect.Client[v1.UpdateProfileRequest, v1.UpdateProfileResponse]
	deleteProfile            *connect.Client[v1.DeleteProfileRequest, v1.DeleteProfileResponse]
	applyProfileToNode       *connect.Client[v1.ApplyProfileToNodeRequest, v1.ApplyProfileToNodeResponse]
	listAdapters             *connect.Client[v1.ListAdaptersRequest, v1.ListAdaptersResponse]
	setAdapterEnabled        *connect.Client[v1.SetAdapterEnabledRequest, v1.SetAdapterEnabledResponse]
	listAudit                *connect.Client[v1.ListAuditRequest, v1.ListAuditResponse]
	listEnrollments          *connect.Client[v1.ListEnrollmentsRequest, v1.ListEnrollmentsResponse]
	createEnrollment         *connect.Client[v1.CreateEnrollmentRequest, v1.CreateEnrollmentResponse]
	approveEnrollment        *connect.Client[v1.ApproveEnrollmentRequest, v1.ApproveEnrollmentResponse]
	rejectEnrollment         *connect.Client[v1.RejectEnrollmentRequest, v1.RejectEnrollmentResponse]
	whoAmI                   *connect.Client[v1.WhoAmIRequest, v1.WhoAmIResponse]
	revokeCertificate        *connect.Client[v1.RevokeCertificateRequest, v1.RevokeCertificateResponse]
	issueLeaf                *connect.Client[v1.IssueLeafRequest, v1.IssueLeafResponse]
	rekeyNode                *connect.Client[v1.RekeyNodeRequest, v1.RekeyNodeResponse]
	getNodeConfig            *connect.Client[v1.GetNodeConfigRequest, v1.GetNodeConfigResponse]
	applyNodeConfig          *connect.Client[v1.ApplyNodeConfigRequest, v1.ApplyNodeConfigResponse]
	exportCAKey              *connect.Client[v1.ExportCAKeyRequest, v1.ExportCAKeyResponse]
	importCAKey              *connect.Client[v1.ImportCAKeyRequest, v1.ImportCAKeyResponse]
	issueOperatorCredential  *connect.Client[v1.IssueOperatorCredentialRequest, v1.IssueOperatorCredentialResponse]
	revokeOperatorCredential *connect.Client[v1.RevokeOperatorCredentialRequest, v1.RevokeOperatorCredentialResponse]
	listOperatorCredentials  *connect.Client[v1.ListOperatorCredentialsRequest, v1.ListOperatorCredentialsResponse]
	previewAdoption          *connect.Client[v1.PreviewAdoptionRequest, v1.PreviewAdoptionResponse]
	adoptNode                *connect.Client[v1.AdoptNodeRequest, v1.AdoptNodeResponse]
	decommissionNode         *connect.Client[v1.DecommissionNodeRequest, v1.DecommissionNodeResponse]
}

// ListNodes calls cryptos.fleet.v1.FleetService.ListNodes.
func (c *fleetServiceClient) ListNodes(ctx context.Context, req *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error) {
	return c.listNodes.CallUnary(ctx, req)
}

// GetNode calls cryptos.fleet.v1.FleetService.GetNode.
func (c *fleetServiceClient) GetNode(ctx context.Context, req *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error) {
	return c.getNode.CallUnary(ctx, req)
}

// ListCertificates calls cryptos.fleet.v1.FleetService.ListCertificates.
func (c *fleetServiceClient) ListCertificates(ctx context.Context, req *connect.Request[v1.ListCertificatesRequest]) (*connect.Response[v1.ListCertificatesResponse], error) {
	return c.listCertificates.CallUnary(ctx, req)
}

// ListProfiles calls cryptos.fleet.v1.FleetService.ListProfiles.
func (c *fleetServiceClient) ListProfiles(ctx context.Context, req *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error) {
	return c.listProfiles.CallUnary(ctx, req)
}

// CreateProfile calls cryptos.fleet.v1.FleetService.CreateProfile.
func (c *fleetServiceClient) CreateProfile(ctx context.Context, req *connect.Request[v1.CreateProfileRequest]) (*connect.Response[v1.CreateProfileResponse], error) {
	return c.createProfile.CallUnary(ctx, req)
}

// UpdateProfile calls cryptos.fleet.v1.FleetService.UpdateProfile.
func (c *fleetServiceClient) UpdateProfile(ctx context.Context, req *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error) {
	return c.updateProfile.CallUnary(ctx, req)
}

// DeleteProfile calls cryptos.fleet.v1.FleetService.DeleteProfile.
func (c *fleetServiceClient) DeleteProfile(ctx context.Context, req *connect.Request[v1.DeleteProfileRequest]) (*connect.Response[v1.DeleteProfileResponse], error) {
	return c.deleteProfile.CallUnary(ctx, req)
}

// ApplyProfileToNode calls cryptos.fleet.v1.FleetService.ApplyProfileToNode.
func (c *fleetServiceClient) ApplyProfileToNode(ctx context.Context, req *connect.Request[v1.ApplyProfileToNodeRequest]) (*connect.Response[v1.ApplyProfileToNodeResponse], error) {
	return c.applyProfileToNode.CallUnary(ctx, req)
}

// ListAdapters calls cryptos.fleet.v1.FleetService.ListAdapters.
func (c *fleetServiceClient) ListAdapters(ctx context.Context, req *connect.Request[v1.ListAdaptersRequest]) (*connect.Response[v1.ListAdaptersResponse], error) {
	return c.listAdapters.CallUnary(ctx, req)
}

// SetAdapterEnabled calls cryptos.fleet.v1.FleetService.SetAdapterEnabled.
func (c *fleetServiceClient) SetAdapterEnabled(ctx context.Context, req *connect.Request[v1.SetAdapterEnabledRequest]) (*connect.Response[v1.SetAdapterEnabledResponse], error) {
	return c.setAdapterEnabled.CallUnary(ctx, req)
}

// ListAudit calls cryptos.fleet.v1.FleetService.ListAudit.
func (c *fleetServiceClient) ListAudit(ctx context.Context, req *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error) {
	return c.listAudit.CallUnary(ctx, req)
}

// ListEnrollments calls cryptos.fleet.v1.FleetService.ListEnrollments.
func (c *fleetServiceClient) ListEnrollments(ctx context.Context, req *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error) {
	return c.listEnrollments.CallUnary(ctx, req)
}

// CreateEnrollment calls cryptos.fleet.v1.FleetService.CreateEnrollment.
func (c *fleetServiceClient) CreateEnrollment(ctx context.Context, req *connect.Request[v1.CreateEnrollmentRequest]) (*connect.Response[v1.CreateEnrollmentResponse], error) {
	return c.createEnrollment.CallUnary(ctx, req)
}

// ApproveEnrollment calls cryptos.fleet.v1.FleetService.ApproveEnrollment.
func (c *fleetServiceClient) ApproveEnrollment(ctx context.Context, req *connect.Request[v1.ApproveEnrollmentRequest]) (*connect.Response[v1.ApproveEnrollmentResponse], error) {
	return c.approveEnrollment.CallUnary(ctx, req)
}

// RejectEnrollment calls cryptos.fleet.v1.FleetService.RejectEnrollment.
func (c *fleetServiceClient) RejectEnrollment(ctx context.Context, req *connect.Request[v1.RejectEnrollmentRequest]) (*connect.Response[v1.RejectEnrollmentResponse], error) {
	return c.rejectEnrollment.CallUnary(ctx, req)
}

// WhoAmI calls cryptos.fleet.v1.FleetService.WhoAmI.
func (c *fleetServiceClient) WhoAmI(ctx context.Context, req *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error) {
	return c.whoAmI.CallUnary(ctx, req)
}

// RevokeCertificate calls cryptos.fleet.v1.FleetService.RevokeCertificate.
func (c *fleetServiceClient) RevokeCertificate(ctx context.Context, req *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error) {
	return c.revokeCertificate.CallUnary(ctx, req)
}

// IssueLeaf calls cryptos.fleet.v1.FleetService.IssueLeaf.
func (c *fleetServiceClient) IssueLeaf(ctx context.Context, req *connect.Request[v1.IssueLeafRequest]) (*connect.Response[v1.IssueLeafResponse], error) {
	return c.issueLeaf.CallUnary(ctx, req)
}

// RekeyNode calls cryptos.fleet.v1.FleetService.RekeyNode.
func (c *fleetServiceClient) RekeyNode(ctx context.Context, req *connect.Request[v1.RekeyNodeRequest]) (*connect.Response[v1.RekeyNodeResponse], error) {
	return c.rekeyNode.CallUnary(ctx, req)
}

// GetNodeConfig calls cryptos.fleet.v1.FleetService.GetNodeConfig.
func (c *fleetServiceClient) GetNodeConfig(ctx context.Context, req *connect.Request[v1.GetNodeConfigRequest]) (*connect.Response[v1.GetNodeConfigResponse], error) {
	return c.getNodeConfig.CallUnary(ctx, req)
}

// ApplyNodeConfig calls cryptos.fleet.v1.FleetService.ApplyNodeConfig.
func (c *fleetServiceClient) ApplyNodeConfig(ctx context.Context, req *connect.Request[v1.ApplyNodeConfigRequest]) (*connect.Response[v1.ApplyNodeConfigResponse], error) {
	return c.applyNodeConfig.CallUnary(ctx, req)
}

// ExportCAKey calls cryptos.fleet.v1.FleetService.ExportCAKey.
func (c *fleetServiceClient) ExportCAKey(ctx context.Context, req *connect.Request[v1.ExportCAKeyRequest]) (*connect.Response[v1.ExportCAKeyResponse], error) {
	return c.exportCAKey.CallUnary(ctx, req)
}

// ImportCAKey calls cryptos.fleet.v1.FleetService.ImportCAKey.
func (c *fleetServiceClient) ImportCAKey(ctx context.Context, req *connect.Request[v1.ImportCAKeyRequest]) (*connect.Response[v1.ImportCAKeyResponse], error) {
	return c.importCAKey.CallUnary(ctx, req)
}

// IssueOperatorCredential calls cryptos.fleet.v1.FleetService.IssueOperatorCredential.
func (c *fleetServiceClient) IssueOperatorCredential(ctx context.Context, req *connect.Request[v1.IssueOperatorCredentialRequest]) (*connect.Response[v1.IssueOperatorCredentialResponse], error) {
	return c.issueOperatorCredential.CallUnary(ctx, req)
}

// RevokeOperatorCredential calls cryptos.fleet.v1.FleetService.RevokeOperatorCredential.
func (c *fleetServiceClient) RevokeOperatorCredential(ctx context.Context, req *connect.Request[v1.RevokeOperatorCredentialRequest]) (*connect.Response[v1.RevokeOperatorCredentialResponse], error) {
	return c.revokeOperatorCredential.CallUnary(ctx, req)
}

// ListOperatorCredentials calls cryptos.fleet.v1.FleetService.ListOperatorCredentials.
func (c *fleetServiceClient) ListOperatorCredentials(ctx context.Context, req *connect.Request[v1.ListOperatorCredentialsRequest]) (*connect.Response[v1.ListOperatorCredentialsResponse], error) {
	return c.listOperatorCredentials.CallUnary(ctx, req)
}

// PreviewAdoption calls cryptos.fleet.v1.FleetService.PreviewAdoption.
func (c *fleetServiceClient) PreviewAdoption(ctx context.Context, req *connect.Request[v1.PreviewAdoptionRequest]) (*connect.Response[v1.PreviewAdoptionResponse], error) {
	return c.previewAdoption.CallUnary(ctx, req)
}

// AdoptNode calls cryptos.fleet.v1.FleetService.AdoptNode.
func (c *fleetServiceClient) AdoptNode(ctx context.Context, req *connect.Request[v1.AdoptNodeRequest]) (*connect.ServerStreamForClient[v1.AdoptNodeResponse], error) {
	return c.adoptNode.CallServerStream(ctx, req)
}

// DecommissionNode calls cryptos.fleet.v1.FleetService.DecommissionNode.
func (c *fleetServiceClient) DecommissionNode(ctx context.Context, req *connect.Request[v1.DecommissionNodeRequest]) (*connect.Response[v1.DecommissionNodeResponse], error) {
	return c.decommissionNode.CallUnary(ctx, req)
}

// FleetServiceHandler is an implementation of the cryptos.fleet.v1.FleetService service.
type FleetServiceHandler interface {
	// ListNodes returns a summary for every node the manager knows about.
	ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error)
	// GetNode returns full detail, including the identity chain, for one node.
	GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error)
	// ListCertificates returns the aggregated certificate set across nodes,
	// optionally scoped to a single node.
	ListCertificates(context.Context, *connect.Request[v1.ListCertificatesRequest]) (*connect.Response[v1.ListCertificatesResponse], error)
	// ListProfiles returns the manager's catalog of certificate issuance
	// profiles. Each is a cryptos.v1.CertificateProfile, the same shape a node
	// stores in pki.profiles[], so the catalog is a lossless superset the node
	// accepts verbatim. Operator-readable.
	ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error)
	// CreateProfile adds a new certificate profile to the manager's catalog.
	// The profile name must be unique. Admin-gated and audited.
	CreateProfile(context.Context, *connect.Request[v1.CreateProfileRequest]) (*connect.Response[v1.CreateProfileResponse], error)
	// UpdateProfile replaces an existing catalog profile, matched by name.
	// Admin-gated and audited.
	UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error)
	// DeleteProfile removes a catalog profile by name. Non-cascading: it does
	// not touch any node's existing pki.profiles[]. Admin-gated and audited.
	DeleteProfile(context.Context, *connect.Request[v1.DeleteProfileRequest]) (*connect.Response[v1.DeleteProfileResponse], error)
	// ApplyProfileToNode pushes a catalog profile onto a managed node: the
	// manager fetches the node's full config, inserts-or-replaces the named
	// profile in pki.profiles[] (matched by name), and applies the whole config
	// back via the node's ApplyConfig. Admin-gated and audited.
	ApplyProfileToNode(context.Context, *connect.Request[v1.ApplyProfileToNodeRequest]) (*connect.Response[v1.ApplyProfileToNodeResponse], error)
	// ListAdapters returns the manager's catalog of enrollment protocol
	// adapters.
	ListAdapters(context.Context, *connect.Request[v1.ListAdaptersRequest]) (*connect.Response[v1.ListAdaptersResponse], error)
	// SetAdapterEnabled records whether an enrollment protocol adapter is
	// enabled, matched by adapter name. This persists intent; the protocol
	// engines that serve enrollment requests ship in a later program, so an
	// enabled adapter does not yet answer requests. Admin-gated and audited.
	SetAdapterEnabled(context.Context, *connect.Request[v1.SetAdapterEnabledRequest]) (*connect.Response[v1.SetAdapterEnabledResponse], error)
	// ListAudit returns the manager's audit log.
	ListAudit(context.Context, *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error)
	// ListEnrollments returns the manager's pending and resolved enrollment
	// requests.
	ListEnrollments(context.Context, *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error)
	// CreateEnrollment opens a new enrollment request (LINK a node or provision a
	// SUBORDINATE CA); the manager verifies attestation for LINK.
	CreateEnrollment(context.Context, *connect.Request[v1.CreateEnrollmentRequest]) (*connect.Response[v1.CreateEnrollmentResponse], error)
	// ApproveEnrollment approves a pending request (LINK -> ApplyConfig managed
	// state; SUBORDINATE -> CSR-ferry).
	ApproveEnrollment(context.Context, *connect.Request[v1.ApproveEnrollmentRequest]) (*connect.Response[v1.ApproveEnrollmentResponse], error)
	// RejectEnrollment rejects a pending request with a reason.
	RejectEnrollment(context.Context, *connect.Request[v1.RejectEnrollmentRequest]) (*connect.Response[v1.RejectEnrollmentResponse], error)
	// WhoAmI echoes the operator identity the manager verified from the
	// presented client certificate (subject CN, cert serial, access level).
	WhoAmI(context.Context, *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error)
	// RevokeCertificate revokes an issued certificate on the node that issued
	// it, identified by node name and hex serial, with an RFC 5280 reason code.
	RevokeCertificate(context.Context, *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error)
	// IssueLeaf signs a leaf certificate on the named issuing node from a
	// browser-generated PKCS#10 CSR under a named issuance profile. Only the
	// CSR crosses the wire; the leaf private key stays in the browser.
	IssueLeaf(context.Context, *connect.Request[v1.IssueLeafRequest]) (*connect.Response[v1.IssueLeafResponse], error)
	// RekeyNode re-keys a subordinate CA node in one orchestrated call: the
	// manager has the child mint a new key + CSR, routes the CSR to the parent
	// (resolved from the child's issuer CN) for signing under profile_name, and
	// delivers the signed chain back to the child. The parent must be a node the
	// manager already knows about.
	RekeyNode(context.Context, *connect.Request[v1.RekeyNodeRequest]) (*connect.Response[v1.RekeyNodeResponse], error)
	// GetNodeConfig fetches the current machine configuration of a managed node,
	// so an operator can view it (and the web can edit a subset before applying
	// the whole config back). Operator-gated; a read, so it is not audited.
	GetNodeConfig(context.Context, *connect.Request[v1.GetNodeConfigRequest]) (*connect.Response[v1.GetNodeConfigResponse], error)
	// ApplyNodeConfig applies a full machine configuration to a managed node.
	// The config is the fetched baseline with the operator's edits merged in; the
	// node's ApplyConfig is a whole-config replace, so the caller must send the
	// complete config, never a partial one. Admin-gated and audited.
	ApplyNodeConfig(context.Context, *connect.Request[v1.ApplyNodeConfigRequest]) (*connect.Response[v1.ApplyNodeConfigResponse], error)
	// ExportCAKey backs up a managed node's CA private key to an encrypted
	// envelope. The node seals the backup with the operator passphrase
	// (Argon2id + AES-256-GCM) so the plaintext key never leaves the node; the
	// manager only relays the envelope through to the caller. The passphrase is
	// used in transit and is never persisted. A TPM-backed node refuses export.
	// Admin-gated and audited (the audit names the node only, never the secret).
	ExportCAKey(context.Context, *connect.Request[v1.ExportCAKeyRequest]) (*connect.Response[v1.ExportCAKeyResponse], error)
	// ImportCAKey restores a CA identity onto a fresh managed node from an
	// encrypted envelope produced by ExportCAKey. The node decrypts the envelope
	// with the operator passphrase and adopts the key; it refuses the import if
	// it already holds an identity. The passphrase transits the manager only to
	// reach the node and is never persisted. Admin-gated and audited (the audit
	// names the node and restored subject only, never the secret or envelope).
	ImportCAKey(context.Context, *connect.Request[v1.ImportCAKeyRequest]) (*connect.Response[v1.ImportCAKeyResponse], error)
	// IssueOperatorCredential issues an operator client certificate. The browser
	// generates the key and CSR; the manager routes signing to the node acting as
	// the operator CA under an operator-<level> profile that carries the
	// access-level extension. Only the CSR crosses the wire; the operator key
	// stays in the browser. Admin-gated and audited (the audit names the subject
	// and serial only, never the CSR or certificate bytes).
	IssueOperatorCredential(context.Context, *connect.Request[v1.IssueOperatorCredentialRequest]) (*connect.Response[v1.IssueOperatorCredentialResponse], error)
	// RevokeOperatorCredential revokes an operator credential on the operator-CA
	// node by hex serial, with an RFC 5280 reason code. The manager enforces the
	// revocation in the authz middleware, so a revoked operator can no longer
	// authenticate. Admin-gated and audited.
	RevokeOperatorCredential(context.Context, *connect.Request[v1.RevokeOperatorCredentialRequest]) (*connect.Response[v1.RevokeOperatorCredentialResponse], error)
	// ListOperatorCredentials returns the operator credentials the manager has
	// issued, with their level, expiry, and revocation state. Operator-readable.
	ListOperatorCredentials(context.Context, *connect.Request[v1.ListOperatorCredentialsRequest]) (*connect.Response[v1.ListOperatorCredentialsResponse], error)
	// PreviewAdoption performs the trust-on-first-use step of adopting a new
	// node: it dials the maintenance endpoint (no pin yet), captures the
	// self-signed certificate the node presents, and returns its SHA-256
	// fingerprint and subject so the operator can confirm it before adoption.
	// Admin-gated; a read, so it is not audited.
	PreviewAdoption(context.Context, *connect.Request[v1.PreviewAdoptionRequest]) (*connect.Response[v1.PreviewAdoptionResponse], error)
	// AdoptNode provisions a new maintenance node end to end and streams progress.
	// Pinned to the fingerprint the operator confirmed via PreviewAdoption, the
	// manager applies the initial config, awaits the reboot, drives the first-boot
	// ceremony, and registers the node. Each streamed message carries a phase
	// (applying-config, installing, awaiting-reboot, ceremony, established) with
	// human-readable detail; the final message sets done. Admin-gated and audited.
	AdoptNode(context.Context, *connect.Request[v1.AdoptNodeRequest], *connect.ServerStream[v1.AdoptNodeResponse]) error
	// DecommissionNode remotely wipes a managed node's identity and data via the
	// node's mTLS-served RemoteReset, then reboots it into maintenance. The caller
	// must echo the node's current Root CA CN as confirmation. Admin-gated and
	// audited (the audit names the node and that it was wiped, never any secret).
	DecommissionNode(context.Context, *connect.Request[v1.DecommissionNodeRequest]) (*connect.Response[v1.DecommissionNodeResponse], error)
}

// NewFleetServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFleetServiceHandler(svc FleetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	fleetServiceMethods := v1.File_cryptos_fleet_v1_fleet_proto.Services().ByName("FleetService").Methods()
	fleetServiceListNodesHandler := connect.NewUnaryHandler(
		FleetServiceListNodesProcedure,
		svc.ListNodes,
		connect.WithSchema(fleetServiceMethods.ByName("ListNodes")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceGetNodeHandler := connect.NewUnaryHandler(
		FleetServiceGetNodeProcedure,
		svc.GetNode,
		connect.WithSchema(fleetServiceMethods.ByName("GetNode")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceListCertificatesHandler := connect.NewUnaryHandler(
		FleetServiceListCertificatesProcedure,
		svc.ListCertificates,
		connect.WithSchema(fleetServiceMethods.ByName("ListCertificates")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceListProfilesHandler := connect.NewUnaryHandler(
		FleetServiceListProfilesProcedure,
		svc.ListProfiles,
		connect.WithSchema(fleetServiceMethods.ByName("ListProfiles")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceCreateProfileHandler := connect.NewUnaryHandler(
		FleetServiceCreateProfileProcedure,
		svc.CreateProfile,
		connect.WithSchema(fleetServiceMethods.ByName("CreateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceUpdateProfileHandler := connect.NewUnaryHandler(
		FleetServiceUpdateProfileProcedure,
		svc.UpdateProfile,
		connect.WithSchema(fleetServiceMethods.ByName("UpdateProfile")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceDeleteProfileHandler := connect.NewUnaryHandler(
		FleetServiceDeleteProfileProcedure,
		svc.DeleteProfile,
		connect.WithSchema(fleetServiceMethods.ByName("DeleteProfile")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceApplyProfileToNodeHandler := connect.NewUnaryHandler(
		FleetServiceApplyProfileToNodeProcedure,
		svc.ApplyProfileToNode,
		connect.WithSchema(fleetServiceMethods.ByName("ApplyProfileToNode")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceListAdaptersHandler := connect.NewUnaryHandler(
		FleetServiceListAdaptersProcedure,
		svc.ListAdapters,
		connect.WithSchema(fleetServiceMethods.ByName("ListAdapters")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceSetAdapterEnabledHandler := connect.NewUnaryHandler(
		FleetServiceSetAdapterEnabledProcedure,
		svc.SetAdapterEnabled,
		connect.WithSchema(fleetServiceMethods.ByName("SetAdapterEnabled")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceListAuditHandler := connect.NewUnaryHandler(
		FleetServiceListAuditProcedure,
		svc.ListAudit,
		connect.WithSchema(fleetServiceMethods.ByName("ListAudit")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceListEnrollmentsHandler := connect.NewUnaryHandler(
		FleetServiceListEnrollmentsProcedure,
		svc.ListEnrollments,
		connect.WithSchema(fleetServiceMethods.ByName("ListEnrollments")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceCreateEnrollmentHandler := connect.NewUnaryHandler(
		FleetServiceCreateEnrollmentProcedure,
		svc.CreateEnrollment,
		connect.WithSchema(fleetServiceMethods.ByName("CreateEnrollment")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceApproveEnrollmentHandler := connect.NewUnaryHandler(
		FleetServiceApproveEnrollmentProcedure,
		svc.ApproveEnrollment,
		connect.WithSchema(fleetServiceMethods.ByName("ApproveEnrollment")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceRejectEnrollmentHandler := connect.NewUnaryHandler(
		FleetServiceRejectEnrollmentProcedure,
		svc.RejectEnrollment,
		connect.WithSchema(fleetServiceMethods.ByName("RejectEnrollment")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceWhoAmIHandler := connect.NewUnaryHandler(
		FleetServiceWhoAmIProcedure,
		svc.WhoAmI,
		connect.WithSchema(fleetServiceMethods.ByName("WhoAmI")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceRevokeCertificateHandler := connect.NewUnaryHandler(
		FleetServiceRevokeCertificateProcedure,
		svc.RevokeCertificate,
		connect.WithSchema(fleetServiceMethods.ByName("RevokeCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceIssueLeafHandler := connect.NewUnaryHandler(
		FleetServiceIssueLeafProcedure,
		svc.IssueLeaf,
		connect.WithSchema(fleetServiceMethods.ByName("IssueLeaf")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceRekeyNodeHandler := connect.NewUnaryHandler(
		FleetServiceRekeyNodeProcedure,
		svc.RekeyNode,
		connect.WithSchema(fleetServiceMethods.ByName("RekeyNode")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceGetNodeConfigHandler := connect.NewUnaryHandler(
		FleetServiceGetNodeConfigProcedure,
		svc.GetNodeConfig,
		connect.WithSchema(fleetServiceMethods.ByName("GetNodeConfig")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceApplyNodeConfigHandler := connect.NewUnaryHandler(
		FleetServiceApplyNodeConfigProcedure,
		svc.ApplyNodeConfig,
		connect.WithSchema(fleetServiceMethods.ByName("ApplyNodeConfig")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceExportCAKeyHandler := connect.NewUnaryHandler(
		FleetServiceExportCAKeyProcedure,
		svc.ExportCAKey,
		connect.WithSchema(fleetServiceMethods.ByName("ExportCAKey")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceImportCAKeyHandler := connect.NewUnaryHandler(
		FleetServiceImportCAKeyProcedure,
		svc.ImportCAKey,
		connect.WithSchema(fleetServiceMethods.ByName("ImportCAKey")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceIssueOperatorCredentialHandler := connect.NewUnaryHandler(
		FleetServiceIssueOperatorCredentialProcedure,
		svc.IssueOperatorCredential,
		connect.WithSchema(fleetServiceMethods.ByName("IssueOperatorCredential")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceRevokeOperatorCredentialHandler := connect.NewUnaryHandler(
		FleetServiceRevokeOperatorCredentialProcedure,
		svc.RevokeOperatorCredential,
		connect.WithSchema(fleetServiceMethods.ByName("RevokeOperatorCredential")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceListOperatorCredentialsHandler := connect.NewUnaryHandler(
		FleetServiceListOperatorCredentialsProcedure,
		svc.ListOperatorCredentials,
		connect.WithSchema(fleetServiceMethods.ByName("ListOperatorCredentials")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServicePreviewAdoptionHandler := connect.NewUnaryHandler(
		FleetServicePreviewAdoptionProcedure,
		svc.PreviewAdoption,
		connect.WithSchema(fleetServiceMethods.ByName("PreviewAdoption")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceAdoptNodeHandler := connect.NewServerStreamHandler(
		FleetServiceAdoptNodeProcedure,
		svc.AdoptNode,
		connect.WithSchema(fleetServiceMethods.ByName("AdoptNode")),
		connect.WithHandlerOptions(opts...),
	)
	fleetServiceDecommissionNodeHandler := connect.NewUnaryHandler(
		FleetServiceDecommissionNodeProcedure,
		svc.DecommissionNode,
		connect.WithSchema(fleetServiceMethods.ByName("DecommissionNode")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cryptos.fleet.v1.FleetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FleetServiceListNodesProcedure:
			fleetServiceListNodesHandler.ServeHTTP(w, r)
		case FleetServiceGetNodeProcedure:
			fleetServiceGetNodeHandler.ServeHTTP(w, r)
		case FleetServiceListCertificatesProcedure:
			fleetServiceListCertificatesHandler.ServeHTTP(w, r)
		case FleetServiceListProfilesProcedure:
			fleetServiceListProfilesHandler.ServeHTTP(w, r)
		case FleetServiceCreateProfileProcedure:
			fleetServiceCreateProfileHandler.ServeHTTP(w, r)
		case FleetServiceUpdateProfileProcedure:
			fleetServiceUpdateProfileHandler.ServeHTTP(w, r)
		case FleetServiceDeleteProfileProcedure:
			fleetServiceDeleteProfileHandler.ServeHTTP(w, r)
		case FleetServiceApplyProfileToNodeProcedure:
			fleetServiceApplyProfileToNodeHandler.ServeHTTP(w, r)
		case FleetServiceListAdaptersProcedure:
			fleetServiceListAdaptersHandler.ServeHTTP(w, r)
		case FleetServiceSetAdapterEnabledProcedure:
			fleetServiceSetAdapterEnabledHandler.ServeHTTP(w, r)
		case FleetServiceListAuditProcedure:
			fleetServiceListAuditHandler.ServeHTTP(w, r)
		case FleetServiceListEnrollmentsProcedure:
			fleetServiceListEnrollmentsHandler.ServeHTTP(w, r)
		case FleetServiceCreateEnrollmentProcedure:
			fleetServiceCreateEnrollmentHandler.ServeHTTP(w, r)
		case FleetServiceApproveEnrollmentProcedure:
			fleetServiceApproveEnrollmentHandler.ServeHTTP(w, r)
		case FleetServiceRejectEnrollmentProcedure:
			fleetServiceRejectEnrollmentHandler.ServeHTTP(w, r)
		case FleetServiceWhoAmIProcedure:
			fleetServiceWhoAmIHandler.ServeHTTP(w, r)
		case FleetServiceRevokeCertificateProcedure:
			fleetServiceRevokeCertificateHandler.ServeHTTP(w, r)
		case FleetServiceIssueLeafProcedure:
			fleetServiceIssueLeafHandler.ServeHTTP(w, r)
		case FleetServiceRekeyNodeProcedure:
			fleetServiceRekeyNodeHandler.ServeHTTP(w, r)
		case FleetServiceGetNodeConfigProcedure:
			fleetServiceGetNodeConfigHandler.ServeHTTP(w, r)
		case FleetServiceApplyNodeConfigProcedure:
			fleetServiceApplyNodeConfigHandler.ServeHTTP(w, r)
		case FleetServiceExportCAKeyProcedure:
			fleetServiceExportCAKeyHandler.ServeHTTP(w, r)
		case FleetServiceImportCAKeyProcedure:
			fleetServiceImportCAKeyHandler.ServeHTTP(w, r)
		case FleetServiceIssueOperatorCredentialProcedure:
			fleetServiceIssueOperatorCredentialHandler.ServeHTTP(w, r)
		case FleetServiceRevokeOperatorCredentialProcedure:
			fleetServiceRevokeOperatorCredentialHandler.ServeHTTP(w, r)
		case FleetServiceListOperatorCredentialsProcedure:
			fleetServiceListOperatorCredentialsHandler.ServeHTTP(w, r)
		case FleetServicePreviewAdoptionProcedure:
			fleetServicePreviewAdoptionHandler.ServeHTTP(w, r)
		case FleetServiceAdoptNodeProcedure:
			fleetServiceAdoptNodeHandler.ServeHTTP(w, r)
		case FleetServiceDecommissionNodeProcedure:
			fleetServiceDecommissionNodeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFleetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFleetServiceHandler struct{}

func (UnimplementedFleetServiceHandler) ListNodes(context.Context, *connect.Request[v1.ListNodesRequest]) (*connect.Response[v1.ListNodesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListNodes is not implemented"))
}

func (UnimplementedFleetServiceHandler) GetNode(context.Context, *connect.Request[v1.GetNodeRequest]) (*connect.Response[v1.GetNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.GetNode is not implemented"))
}

func (UnimplementedFleetServiceHandler) ListCertificates(context.Context, *connect.Request[v1.ListCertificatesRequest]) (*connect.Response[v1.ListCertificatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListCertificates is not implemented"))
}

func (UnimplementedFleetServiceHandler) ListProfiles(context.Context, *connect.Request[v1.ListProfilesRequest]) (*connect.Response[v1.ListProfilesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListProfiles is not implemented"))
}

func (UnimplementedFleetServiceHandler) CreateProfile(context.Context, *connect.Request[v1.CreateProfileRequest]) (*connect.Response[v1.CreateProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.CreateProfile is not implemented"))
}

func (UnimplementedFleetServiceHandler) UpdateProfile(context.Context, *connect.Request[v1.UpdateProfileRequest]) (*connect.Response[v1.UpdateProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.UpdateProfile is not implemented"))
}

func (UnimplementedFleetServiceHandler) DeleteProfile(context.Context, *connect.Request[v1.DeleteProfileRequest]) (*connect.Response[v1.DeleteProfileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.DeleteProfile is not implemented"))
}

func (UnimplementedFleetServiceHandler) ApplyProfileToNode(context.Context, *connect.Request[v1.ApplyProfileToNodeRequest]) (*connect.Response[v1.ApplyProfileToNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ApplyProfileToNode is not implemented"))
}

func (UnimplementedFleetServiceHandler) ListAdapters(context.Context, *connect.Request[v1.ListAdaptersRequest]) (*connect.Response[v1.ListAdaptersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListAdapters is not implemented"))
}

func (UnimplementedFleetServiceHandler) SetAdapterEnabled(context.Context, *connect.Request[v1.SetAdapterEnabledRequest]) (*connect.Response[v1.SetAdapterEnabledResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.SetAdapterEnabled is not implemented"))
}

func (UnimplementedFleetServiceHandler) ListAudit(context.Context, *connect.Request[v1.ListAuditRequest]) (*connect.Response[v1.ListAuditResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListAudit is not implemented"))
}

func (UnimplementedFleetServiceHandler) ListEnrollments(context.Context, *connect.Request[v1.ListEnrollmentsRequest]) (*connect.Response[v1.ListEnrollmentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListEnrollments is not implemented"))
}

func (UnimplementedFleetServiceHandler) CreateEnrollment(context.Context, *connect.Request[v1.CreateEnrollmentRequest]) (*connect.Response[v1.CreateEnrollmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.CreateEnrollment is not implemented"))
}

func (UnimplementedFleetServiceHandler) ApproveEnrollment(context.Context, *connect.Request[v1.ApproveEnrollmentRequest]) (*connect.Response[v1.ApproveEnrollmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ApproveEnrollment is not implemented"))
}

func (UnimplementedFleetServiceHandler) RejectEnrollment(context.Context, *connect.Request[v1.RejectEnrollmentRequest]) (*connect.Response[v1.RejectEnrollmentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.RejectEnrollment is not implemented"))
}

func (UnimplementedFleetServiceHandler) WhoAmI(context.Context, *connect.Request[v1.WhoAmIRequest]) (*connect.Response[v1.WhoAmIResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.WhoAmI is not implemented"))
}

func (UnimplementedFleetServiceHandler) RevokeCertificate(context.Context, *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.RevokeCertificate is not implemented"))
}

func (UnimplementedFleetServiceHandler) IssueLeaf(context.Context, *connect.Request[v1.IssueLeafRequest]) (*connect.Response[v1.IssueLeafResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.IssueLeaf is not implemented"))
}

func (UnimplementedFleetServiceHandler) RekeyNode(context.Context, *connect.Request[v1.RekeyNodeRequest]) (*connect.Response[v1.RekeyNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.RekeyNode is not implemented"))
}

func (UnimplementedFleetServiceHandler) GetNodeConfig(context.Context, *connect.Request[v1.GetNodeConfigRequest]) (*connect.Response[v1.GetNodeConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.GetNodeConfig is not implemented"))
}

func (UnimplementedFleetServiceHandler) ApplyNodeConfig(context.Context, *connect.Request[v1.ApplyNodeConfigRequest]) (*connect.Response[v1.ApplyNodeConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ApplyNodeConfig is not implemented"))
}

func (UnimplementedFleetServiceHandler) ExportCAKey(context.Context, *connect.Request[v1.ExportCAKeyRequest]) (*connect.Response[v1.ExportCAKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ExportCAKey is not implemented"))
}

func (UnimplementedFleetServiceHandler) ImportCAKey(context.Context, *connect.Request[v1.ImportCAKeyRequest]) (*connect.Response[v1.ImportCAKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ImportCAKey is not implemented"))
}

func (UnimplementedFleetServiceHandler) IssueOperatorCredential(context.Context, *connect.Request[v1.IssueOperatorCredentialRequest]) (*connect.Response[v1.IssueOperatorCredentialResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.IssueOperatorCredential is not implemented"))
}

func (UnimplementedFleetServiceHandler) RevokeOperatorCredential(context.Context, *connect.Request[v1.RevokeOperatorCredentialRequest]) (*connect.Response[v1.RevokeOperatorCredentialResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.RevokeOperatorCredential is not implemented"))
}

func (UnimplementedFleetServiceHandler) ListOperatorCredentials(context.Context, *connect.Request[v1.ListOperatorCredentialsRequest]) (*connect.Response[v1.ListOperatorCredentialsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.ListOperatorCredentials is not implemented"))
}

func (UnimplementedFleetServiceHandler) PreviewAdoption(context.Context, *connect.Request[v1.PreviewAdoptionRequest]) (*connect.Response[v1.PreviewAdoptionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.PreviewAdoption is not implemented"))
}

func (UnimplementedFleetServiceHandler) AdoptNode(context.Context, *connect.Request[v1.AdoptNodeRequest], *connect.ServerStream[v1.AdoptNodeResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.AdoptNode is not implemented"))
}

func (UnimplementedFleetServiceHandler) DecommissionNode(context.Context, *connect.Request[v1.DecommissionNodeRequest]) (*connect.Response[v1.DecommissionNodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.fleet.v1.FleetService.DecommissionNode is not implemented"))
}
