// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: cryptos/v1/config.proto

package cryptosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MachineConfig is the declarative configuration applied via ApplyConfig.
// Phase 1 defines this subset. Future phases add fields additively;
// breaking changes require a new apiVersion ("cryptos.dev/v1beta1", etc.).
type MachineConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Must be "cryptos.dev/v1alpha1" in Phase 1. Validator rejects other values.
	ApiVersion string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Must be "MachineConfig" in Phase 1.
	Kind      string     `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata  *Metadata  `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Role      *Role      `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Network   *Network   `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Storage   *Storage   `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"`
	Bootstrap *Bootstrap `protobuf:"bytes,7,opt,name=bootstrap,proto3" json:"bootstrap,omitempty"`
	Pki       *Pki       `protobuf:"bytes,8,opt,name=pki,proto3" json:"pki,omitempty"`
	// install carries the target-disk declaration for the maintenance-mode
	// install flow. Ignored by an already-installed node.
	Install *Install `protobuf:"bytes,9,opt,name=install,proto3" json:"install,omitempty"`
	// state_key selects how the LUKS state-partition key is protected. Empty
	// uses the node's build-time default (nodeid or tpm).
	StateKey *StateKey `protobuf:"bytes,10,opt,name=state_key,json=stateKey,proto3" json:"state_key,omitempty"`
}

func (x *MachineConfig) Reset() {
	*x = MachineConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MachineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineConfig) ProtoMessage() {}

func (x *MachineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineConfig.ProtoReflect.Descriptor instead.
func (*MachineConfig) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *MachineConfig) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *MachineConfig) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MachineConfig) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MachineConfig) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *MachineConfig) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *MachineConfig) GetStorage() *Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

func (x *MachineConfig) GetBootstrap() *Bootstrap {
	if x != nil {
		return x.Bootstrap
	}
	return nil
}

func (x *MachineConfig) GetPki() *Pki {
	if x != nil {
		return x.Pki
	}
	return nil
}

func (x *MachineConfig) GetInstall() *Install {
	if x != nil {
		return x.Install
	}
	return nil
}

func (x *MachineConfig) GetStateKey() *StateKey {
	if x != nil {
		return x.StateKey
	}
	return nil
}

// StateKey selects the protector for the encrypted state-partition key.
type StateKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// mode is "nodeid" | "tpm" | "kms"; empty means the build-time default.
	Mode string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	// kms carries the KMS settings when mode is "kms".
	Kms *KmsStateKey `protobuf:"bytes,2,opt,name=kms,proto3" json:"kms,omitempty"`
}

func (x *StateKey) Reset() {
	*x = StateKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateKey) ProtoMessage() {}

func (x *StateKey) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateKey.ProtoReflect.Descriptor instead.
func (*StateKey) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *StateKey) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StateKey) GetKms() *KmsStateKey {
	if x != nil {
		return x.Kms
	}
	return nil
}

// KmsStateKey configures the envelope-encryption KMS that seals/unseals the
// state key. The sealed blob and endpoint are stored in the LUKS2 header token,
// so only first-boot provisioning reads this from the machine config.
type KmsStateKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// endpoint is the base URL of the seal/unseal KMS.
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// trust_pem optionally pins the PEM CA bundle verifying the KMS TLS server.
	TrustPem string `protobuf:"bytes,2,opt,name=trust_pem,json=trustPem,proto3" json:"trust_pem,omitempty"`
}

func (x *KmsStateKey) Reset() {
	*x = KmsStateKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KmsStateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KmsStateKey) ProtoMessage() {}

func (x *KmsStateKey) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KmsStateKey.ProtoReflect.Descriptor instead.
func (*KmsStateKey) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *KmsStateKey) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *KmsStateKey) GetTrustPem() string {
	if x != nil {
		return x.TrustPem
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Phase 1: must be "root". Phase 2 adds "intermediate" and "issuing".
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *Role) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Network struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interface string `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	// CIDR notation, e.g. "10.0.0.10/24".
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Gateway string `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
}

func (x *Network) Reset() {
	*x = Network{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *Network) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Network) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Network) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

type Storage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatePartitionLabel string `protobuf:"bytes,1,opt,name=state_partition_label,json=statePartitionLabel,proto3" json:"state_partition_label,omitempty"`
	FirstBoot           bool   `protobuf:"varint,2,opt,name=first_boot,json=firstBoot,proto3" json:"first_boot,omitempty"`
}

func (x *Storage) Reset() {
	*x = Storage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *Storage) GetStatePartitionLabel() string {
	if x != nil {
		return x.StatePartitionLabel
	}
	return ""
}

func (x *Storage) GetFirstBoot() bool {
	if x != nil {
		return x.FirstBoot
	}
	return false
}

// Bootstrap carries the administrator credential trusted on first boot.
// Exactly one of admin_cert_pem or admin_cert_sha256 is required.
type Bootstrap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminCertPem    string `protobuf:"bytes,1,opt,name=admin_cert_pem,json=adminCertPem,proto3" json:"admin_cert_pem,omitempty"`
	AdminCertSha256 string `protobuf:"bytes,2,opt,name=admin_cert_sha256,json=adminCertSha256,proto3" json:"admin_cert_sha256,omitempty"`
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *Bootstrap) GetAdminCertPem() string {
	if x != nil {
		return x.AdminCertPem
	}
	return ""
}

func (x *Bootstrap) GetAdminCertSha256() string {
	if x != nil {
		return x.AdminCertSha256
	}
	return ""
}

type Pki struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Phase 1: must be "ECDSA-P384" for Roots.
	RootKeyAlg        string   `protobuf:"bytes,1,opt,name=root_key_alg,json=rootKeyAlg,proto3" json:"root_key_alg,omitempty"`
	RootSubject       *Subject `protobuf:"bytes,2,opt,name=root_subject,json=rootSubject,proto3" json:"root_subject,omitempty"`
	RootValidityYears uint32   `protobuf:"varint,3,opt,name=root_validity_years,json=rootValidityYears,proto3" json:"root_validity_years,omitempty"`
	PathLenConstraint uint32   `protobuf:"varint,4,opt,name=path_len_constraint,json=pathLenConstraint,proto3" json:"path_len_constraint,omitempty"`
	// Named certificate profiles this node may generate a CSR from or stamp when
	// signing (Phase 2). Referenced by name from the role/issuance flows.
	Profiles []*CertificateProfile `protobuf:"bytes,5,rep,name=profiles,proto3" json:"profiles,omitempty"`
	// parent pins the CA that signs this subordinate node's certificate, so it
	// can verify the chain it is handed (Phase 2; unset on a Root).
	Parent *Parent `protobuf:"bytes,6,opt,name=parent,proto3" json:"parent,omitempty"`
	// revocation_base_url is the base URL under which this node serves its CRL
	// and OCSP responder. When set, issued certs carry CDP/AIA pointers and the
	// node serves /crl and /ocsp over HTTP (Phase 2 revocation).
	RevocationBaseUrl string `protobuf:"bytes,7,opt,name=revocation_base_url,json=revocationBaseUrl,proto3" json:"revocation_base_url,omitempty"`
	// allow_unverified_revocation_url overrides the fail-closed revocation
	// preflight so an isolated/air-gapped node issues even when the revocation
	// URL does not resolve.
	AllowUnverifiedRevocationUrl bool `protobuf:"varint,8,opt,name=allow_unverified_revocation_url,json=allowUnverifiedRevocationUrl,proto3" json:"allow_unverified_revocation_url,omitempty"`
	// crl_next_update_hours is the CRL validity window: nextUpdate is thisUpdate
	// plus this many hours. Zero means the node default.
	CrlNextUpdateHours uint32 `protobuf:"varint,9,opt,name=crl_next_update_hours,json=crlNextUpdateHours,proto3" json:"crl_next_update_hours,omitempty"`
	// revocation_http_port is the TCP port for the anonymous CRL/OCSP HTTP
	// listener. Zero means the node default.
	RevocationHttpPort uint32 `protobuf:"varint,10,opt,name=revocation_http_port,json=revocationHttpPort,proto3" json:"revocation_http_port,omitempty"`
	// root_leaf_issuance is the explicit, irreversible operator acknowledgement
	// that unlocks direct end-entity (leaf) issuance from a ROOT-role node. Empty
	// (the default) leaves a Root refusing to issue leaves. Carried in the proto
	// so the acknowledgement survives ApplyConfig and reaches an installed node.
	RootLeafIssuance string `protobuf:"bytes,11,opt,name=root_leaf_issuance,json=rootLeafIssuance,proto3" json:"root_leaf_issuance,omitempty"`
}

func (x *Pki) Reset() {
	*x = Pki{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pki) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pki) ProtoMessage() {}

func (x *Pki) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pki.ProtoReflect.Descriptor instead.
func (*Pki) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *Pki) GetRootKeyAlg() string {
	if x != nil {
		return x.RootKeyAlg
	}
	return ""
}

func (x *Pki) GetRootSubject() *Subject {
	if x != nil {
		return x.RootSubject
	}
	return nil
}

func (x *Pki) GetRootValidityYears() uint32 {
	if x != nil {
		return x.RootValidityYears
	}
	return 0
}

func (x *Pki) GetPathLenConstraint() uint32 {
	if x != nil {
		return x.PathLenConstraint
	}
	return 0
}

func (x *Pki) GetProfiles() []*CertificateProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *Pki) GetParent() *Parent {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Pki) GetRevocationBaseUrl() string {
	if x != nil {
		return x.RevocationBaseUrl
	}
	return ""
}

func (x *Pki) GetAllowUnverifiedRevocationUrl() bool {
	if x != nil {
		return x.AllowUnverifiedRevocationUrl
	}
	return false
}

func (x *Pki) GetCrlNextUpdateHours() uint32 {
	if x != nil {
		return x.CrlNextUpdateHours
	}
	return 0
}

func (x *Pki) GetRevocationHttpPort() uint32 {
	if x != nil {
		return x.RevocationHttpPort
	}
	return 0
}

func (x *Pki) GetRootLeafIssuance() string {
	if x != nil {
		return x.RootLeafIssuance
	}
	return ""
}

// Parent is the trust anchor a subordinate CA pins for its issuer: the parent
// (or root) CA certificate, by full PEM or by SHA-256 fingerprint. Exactly one
// is set. Unused by a Root.
type Parent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaCertPem    string `protobuf:"bytes,1,opt,name=ca_cert_pem,json=caCertPem,proto3" json:"ca_cert_pem,omitempty"`
	CaCertSha256 string `protobuf:"bytes,2,opt,name=ca_cert_sha256,json=caCertSha256,proto3" json:"ca_cert_sha256,omitempty"`
}

func (x *Parent) Reset() {
	*x = Parent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parent) ProtoMessage() {}

func (x *Parent) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parent.ProtoReflect.Descriptor instead.
func (*Parent) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *Parent) GetCaCertPem() string {
	if x != nil {
		return x.CaCertPem
	}
	return ""
}

func (x *Parent) GetCaCertSha256() string {
	if x != nil {
		return x.CaCertSha256
	}
	return ""
}

// CertificateProfile drives CSR generation and certificate signing: key
// parameters, subject, validity, and X.509 extensions. Phase 2 defines a
// covering subset of typed extensions plus a raw-extension escape hatch; the
// set grows additively toward the full X.509 catalog.
type CertificateProfile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// e.g. "ECDSA-P384". Covering subset; RSA sizes and other curves are additive.
	KeyAlg           string            `protobuf:"bytes,2,opt,name=key_alg,json=keyAlg,proto3" json:"key_alg,omitempty"`
	Subject          *Subject          `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	ValidityDays     uint32            `protobuf:"varint,4,opt,name=validity_days,json=validityDays,proto3" json:"validity_days,omitempty"`
	BasicConstraints *BasicConstraints `protobuf:"bytes,5,opt,name=basic_constraints,json=basicConstraints,proto3" json:"basic_constraints,omitempty"`
	// e.g. "cert_sign", "crl_sign", "digital_signature", "key_encipherment".
	KeyUsage []string `protobuf:"bytes,6,rep,name=key_usage,json=keyUsage,proto3" json:"key_usage,omitempty"`
	// e.g. "server_auth", "client_auth".
	ExtKeyUsage []string         `protobuf:"bytes,7,rep,name=ext_key_usage,json=extKeyUsage,proto3" json:"ext_key_usage,omitempty"`
	Sans        *SubjectAltNames `protobuf:"bytes,8,opt,name=sans,proto3" json:"sans,omitempty"`
	// Raw-OID escape hatch for extensions not yet modeled as typed fields.
	ExtraExtensions []*X509Extension `protobuf:"bytes,9,rep,name=extra_extensions,json=extraExtensions,proto3" json:"extra_extensions,omitempty"`
}

func (x *CertificateProfile) Reset() {
	*x = CertificateProfile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertificateProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateProfile) ProtoMessage() {}

func (x *CertificateProfile) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateProfile.ProtoReflect.Descriptor instead.
func (*CertificateProfile) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{10}
}

func (x *CertificateProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CertificateProfile) GetKeyAlg() string {
	if x != nil {
		return x.KeyAlg
	}
	return ""
}

func (x *CertificateProfile) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *CertificateProfile) GetValidityDays() uint32 {
	if x != nil {
		return x.ValidityDays
	}
	return 0
}

func (x *CertificateProfile) GetBasicConstraints() *BasicConstraints {
	if x != nil {
		return x.BasicConstraints
	}
	return nil
}

func (x *CertificateProfile) GetKeyUsage() []string {
	if x != nil {
		return x.KeyUsage
	}
	return nil
}

func (x *CertificateProfile) GetExtKeyUsage() []string {
	if x != nil {
		return x.ExtKeyUsage
	}
	return nil
}

func (x *CertificateProfile) GetSans() *SubjectAltNames {
	if x != nil {
		return x.Sans
	}
	return nil
}

func (x *CertificateProfile) GetExtraExtensions() []*X509Extension {
	if x != nil {
		return x.ExtraExtensions
	}
	return nil
}

type BasicConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsCa bool `protobuf:"varint,1,opt,name=is_ca,json=isCa,proto3" json:"is_ca,omitempty"`
	// path_len applies when is_ca. 0 = no CAs may be issued below this one
	// (a leaf-only issuing CA). Absent = unconstrained depth.
	PathLen *uint32 `protobuf:"varint,2,opt,name=path_len,json=pathLen,proto3,oneof" json:"path_len,omitempty"`
}

func (x *BasicConstraints) Reset() {
	*x = BasicConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasicConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicConstraints) ProtoMessage() {}

func (x *BasicConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicConstraints.ProtoReflect.Descriptor instead.
func (*BasicConstraints) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{11}
}

func (x *BasicConstraints) GetIsCa() bool {
	if x != nil {
		return x.IsCa
	}
	return false
}

func (x *BasicConstraints) GetPathLen() uint32 {
	if x != nil && x.PathLen != nil {
		return *x.PathLen
	}
	return 0
}

type SubjectAltNames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dns   []string `protobuf:"bytes,1,rep,name=dns,proto3" json:"dns,omitempty"`
	Ip    []string `protobuf:"bytes,2,rep,name=ip,proto3" json:"ip,omitempty"`
	Email []string `protobuf:"bytes,3,rep,name=email,proto3" json:"email,omitempty"`
	Uri   []string `protobuf:"bytes,4,rep,name=uri,proto3" json:"uri,omitempty"`
}

func (x *SubjectAltNames) Reset() {
	*x = SubjectAltNames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubjectAltNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectAltNames) ProtoMessage() {}

func (x *SubjectAltNames) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectAltNames.ProtoReflect.Descriptor instead.
func (*SubjectAltNames) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{12}
}

func (x *SubjectAltNames) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *SubjectAltNames) GetIp() []string {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *SubjectAltNames) GetEmail() []string {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *SubjectAltNames) GetUri() []string {
	if x != nil {
		return x.Uri
	}
	return nil
}

// X509Extension is the raw escape hatch: a dotted OID, criticality flag, and the
// DER-encoded extension value, for extensions not yet modeled as typed fields.
type X509Extension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid      string `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Critical bool   `protobuf:"varint,2,opt,name=critical,proto3" json:"critical,omitempty"`
	Value    []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *X509Extension) Reset() {
	*x = X509Extension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *X509Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*X509Extension) ProtoMessage() {}

func (x *X509Extension) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use X509Extension.ProtoReflect.Descriptor instead.
func (*X509Extension) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{13}
}

func (x *X509Extension) GetOid() string {
	if x != nil {
		return x.Oid
	}
	return ""
}

func (x *X509Extension) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

func (x *X509Extension) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Install declares how the node provisions itself to persistent storage during
// the maintenance-mode install (apply-config in maintenance). Ignored by an
// already-installed node.
type Install struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// disk is the target block device to install to and WIPE, e.g. "/dev/nvme0n1".
	Disk string `protobuf:"bytes,1,opt,name=disk,proto3" json:"disk,omitempty"`
}

func (x *Install) Reset() {
	*x = Install{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Install) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Install) ProtoMessage() {}

func (x *Install) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Install.ProtoReflect.Descriptor instead.
func (*Install) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{14}
}

func (x *Install) GetDisk() string {
	if x != nil {
		return x.Disk
	}
	return ""
}

type Subject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommonName   string `protobuf:"bytes,1,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	Organization string `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	Country      string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *Subject) Reset() {
	*x = Subject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_config_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_config_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_config_proto_rawDescGZIP(), []int{15}
}

func (x *Subject) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *Subject) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *Subject) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_cryptos_v1_config_proto protoreflect.FileDescriptor

var file_cryptos_v1_config_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x73, 0x2e, 0x76, 0x31, 0x22, 0xb4, 0x03, 0x0a, 0x0d, 0x4d, 0x61, 0x63, 0x68, 0x69, 0x6e,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x70, 0x69, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70,
	0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x30, 0x0a, 0x08,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x24,
	0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04,
	0x72, 0x6f, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x07, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x07, 0x6e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x52, 0x07, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x12, 0x33, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x52, 0x09, 0x62, 0x6f,
	0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x12, 0x21, 0x0a, 0x03, 0x70, 0x6b, 0x69, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6b, 0x69, 0x52, 0x03, 0x70, 0x6b, 0x69, 0x12, 0x2d, 0x0a, 0x07, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6c, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c,
	0x52, 0x07, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x12, 0x31, 0x0a, 0x09, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x52, 0x08, 0x73, 0x74, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x49, 0x0a, 0x08,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x29, 0x0a, 0x03,
	0x6b, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x6d, 0x73, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x52, 0x03, 0x6b, 0x6d, 0x73, 0x22, 0x46, 0x0a, 0x0b, 0x4b, 0x6d, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x70, 0x65, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x72, 0x75, 0x73, 0x74, 0x50, 0x65, 0x6d, 0x22,
	0x1e, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x1a, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x5b, 0x0a, 0x07, 0x4e,
	0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x22, 0x5c, 0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x61, 0x72,
	0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x13, 0x73, 0x74, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x5f, 0x62, 0x6f, 0x6f, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x66, 0x69, 0x72,
	0x73, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x22, 0x5d, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74,
	0x72, 0x61, 0x70, 0x12, 0x24, 0x0a, 0x0e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x65, 0x72,
	0x74, 0x5f, 0x70, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x43, 0x65, 0x72, 0x74, 0x50, 0x65, 0x6d, 0x12, 0x2a, 0x0a, 0x11, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x65, 0x72, 0x74, 0x53,
	0x68, 0x61, 0x32, 0x35, 0x36, 0x22, 0xb1, 0x04, 0x0a, 0x03, 0x50, 0x6b, 0x69, 0x12, 0x20, 0x0a,
	0x0c, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x61, 0x6c, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x74, 0x4b, 0x65, 0x79, 0x41, 0x6c, 0x67, 0x12,
	0x36, 0x0a, 0x0c, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x0b, 0x72, 0x6f, 0x6f, 0x74,
	0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x72, 0x6f, 0x6f, 0x74, 0x5f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x72, 0x6f, 0x6f, 0x74, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x69,
	0x74, 0x79, 0x59, 0x65, 0x61, 0x72, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x70, 0x61, 0x74, 0x68, 0x5f,
	0x6c, 0x65, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x70, 0x61, 0x74, 0x68, 0x4c, 0x65, 0x6e, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x3a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12,
	0x2e, 0x0a, 0x13, 0x72, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x72, 0x65,
	0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x73, 0x65, 0x55, 0x72, 0x6c, 0x12,
	0x45, 0x0a, 0x1f, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x75, 0x6e, 0x76, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x1c, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x55,
	0x6e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x31, 0x0a, 0x15, 0x63, 0x72, 0x6c, 0x5f, 0x6e, 0x65,
	0x78, 0x74, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x63, 0x72, 0x6c, 0x4e, 0x65, 0x78, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x72, 0x65, 0x76,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x12, 0x72, 0x65, 0x76, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x74, 0x74, 0x70, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x72,
	0x6f, 0x6f, 0x74, 0x5f, 0x6c, 0x65, 0x61, 0x66, 0x5f, 0x69, 0x73, 0x73, 0x75, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x72, 0x6f, 0x6f, 0x74, 0x4c, 0x65, 0x61,
	0x66, 0x49, 0x73, 0x73, 0x75, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x4e, 0x0a, 0x06, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0b, 0x63, 0x61, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x70,
	0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x61, 0x43, 0x65, 0x72, 0x74,
	0x50, 0x65, 0x6d, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x61, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x5f, 0x73,
	0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x61, 0x43,
	0x65, 0x72, 0x74, 0x53, 0x68, 0x61, 0x32, 0x35, 0x36, 0x22, 0x98, 0x03, 0x0a, 0x12, 0x43, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x5f, 0x61, 0x6c, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x79, 0x41, 0x6c, 0x67, 0x12, 0x2d, 0x0a,
	0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x23, 0x0a, 0x0d,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x64, 0x61, 0x79, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x44, 0x61, 0x79,
	0x73, 0x12, 0x49, 0x0a, 0x11, 0x62, 0x61, 0x73, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x52, 0x10, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x1b, 0x0a, 0x09,
	0x6b, 0x65, 0x79, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x6b, 0x65, 0x79, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x65, 0x78, 0x74,
	0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0b, 0x65, 0x78, 0x74, 0x4b, 0x65, 0x79, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a,
	0x04, 0x73, 0x61, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x41, 0x6c, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x04, 0x73, 0x61, 0x6e, 0x73, 0x12, 0x44,
	0x0a, 0x10, 0x65, 0x78, 0x74, 0x72, 0x61, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x58, 0x35, 0x30, 0x39, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x54, 0x0a, 0x10, 0x42, 0x61, 0x73, 0x69, 0x63, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x13, 0x0a, 0x05, 0x69, 0x73, 0x5f, 0x63,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x69, 0x73, 0x43, 0x61, 0x12, 0x1e, 0x0a,
	0x08, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x48,
	0x00, 0x52, 0x07, 0x70, 0x61, 0x74, 0x68, 0x4c, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x5f, 0x6c, 0x65, 0x6e, 0x22, 0x5b, 0x0a, 0x0f, 0x53, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x6c, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x64, 0x6e, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0x53, 0x0a, 0x0d, 0x58, 0x35, 0x30, 0x39, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x72,
	0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x72,
	0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1d, 0x0a, 0x07,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x22, 0x68, 0x0a, 0x07, 0x53,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6f, 0x72, 0x67, 0x61, 0x6e,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f,
	0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x72, 0x79, 0x70, 0x74, 0x4f, 0x53, 0x2d, 0x50, 0x4b, 0x49, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2f, 0x76,
	0x31, 0x3b, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_cryptos_v1_config_proto_rawDescOnce sync.Once
	file_cryptos_v1_config_proto_rawDescData = file_cryptos_v1_config_proto_rawDesc
)

func file_cryptos_v1_config_proto_rawDescGZIP() []byte {
	file_cryptos_v1_config_proto_rawDescOnce.Do(func() {
		file_cryptos_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_cryptos_v1_config_proto_rawDescData)
	})
	return file_cryptos_v1_config_proto_rawDescData
}

var file_cryptos_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_cryptos_v1_config_proto_goTypes = []any{
	(*MachineConfig)(nil),      // 0: cryptos.v1.MachineConfig
	(*StateKey)(nil),           // 1: cryptos.v1.StateKey
	(*KmsStateKey)(nil),        // 2: cryptos.v1.KmsStateKey
	(*Metadata)(nil),           // 3: cryptos.v1.Metadata
	(*Role)(nil),               // 4: cryptos.v1.Role
	(*Network)(nil),            // 5: cryptos.v1.Network
	(*Storage)(nil),            // 6: cryptos.v1.Storage
	(*Bootstrap)(nil),          // 7: cryptos.v1.Bootstrap
	(*Pki)(nil),                // 8: cryptos.v1.Pki
	(*Parent)(nil),             // 9: cryptos.v1.Parent
	(*CertificateProfile)(nil), // 10: cryptos.v1.CertificateProfile
	(*BasicConstraints)(nil),   // 11: cryptos.v1.BasicConstraints
	(*SubjectAltNames)(nil),    // 12: cryptos.v1.SubjectAltNames
	(*X509Extension)(nil),      // 13: cryptos.v1.X509Extension
	(*Install)(nil),            // 14: cryptos.v1.Install
	(*Subject)(nil),            // 15: cryptos.v1.Subject
}
var file_cryptos_v1_config_proto_depIdxs = []int32{
	3,  // 0: cryptos.v1.MachineConfig.metadata:type_name -> cryptos.v1.Metadata
	4,  // 1: cryptos.v1.MachineConfig.role:type_name -> cryptos.v1.Role
	5,  // 2: cryptos.v1.MachineConfig.network:type_name -> cryptos.v1.Network
	6,  // 3: cryptos.v1.MachineConfig.storage:type_name -> cryptos.v1.Storage
	7,  // 4: cryptos.v1.MachineConfig.bootstrap:type_name -> cryptos.v1.Bootstrap
	8,  // 5: cryptos.v1.MachineConfig.pki:type_name -> cryptos.v1.Pki
	14, // 6: cryptos.v1.MachineConfig.install:type_name -> cryptos.v1.Install
	1,  // 7: cryptos.v1.MachineConfig.state_key:type_name -> cryptos.v1.StateKey
	2,  // 8: cryptos.v1.StateKey.kms:type_name -> cryptos.v1.KmsStateKey
	15, // 9: cryptos.v1.Pki.root_subject:type_name -> cryptos.v1.Subject
	10, // 10: cryptos.v1.Pki.profiles:type_name -> cryptos.v1.CertificateProfile
	9,  // 11: cryptos.v1.Pki.parent:type_name -> cryptos.v1.Parent
	15, // 12: cryptos.v1.CertificateProfile.subject:type_name -> cryptos.v1.Subject
	11, // 13: cryptos.v1.CertificateProfile.basic_constraints:type_name -> cryptos.v1.BasicConstraints
	12, // 14: cryptos.v1.CertificateProfile.sans:type_name -> cryptos.v1.SubjectAltNames
	13, // 15: cryptos.v1.CertificateProfile.extra_extensions:type_name -> cryptos.v1.X509Extension
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_cryptos_v1_config_proto_init() }
func file_cryptos_v1_config_proto_init() {
	if File_cryptos_v1_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cryptos_v1_config_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MachineConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*StateKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*KmsStateKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Network); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Storage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Bootstrap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Pki); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Parent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CertificateProfile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*BasicConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*SubjectAltNames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*X509Extension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Install); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_config_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*Subject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cryptos_v1_config_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cryptos_v1_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cryptos_v1_config_proto_goTypes,
		DependencyIndexes: file_cryptos_v1_config_proto_depIdxs,
		MessageInfos:      file_cryptos_v1_config_proto_msgTypes,
	}.Build()
	File_cryptos_v1_config_proto = out.File
	file_cryptos_v1_config_proto_rawDesc = nil
	file_cryptos_v1_config_proto_goTypes = nil
	file_cryptos_v1_config_proto_depIdxs = nil
}
