// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: cryptos/v1/node.proto

package cryptosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *MachineConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ApplyConfigRequest) Reset() {
	*x = ApplyConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigRequest) ProtoMessage() {}

func (x *ApplyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigRequest.ProtoReflect.Descriptor instead.
func (*ApplyConfigRequest) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyConfigRequest) GetConfig() *MachineConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ApplyConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Monotonically increasing generation; bumped on every successful apply.
	Generation uint64 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	// True when the apply changed a field that takes effect only on reboot.
	RequiresReboot bool `protobuf:"varint,2,opt,name=requires_reboot,json=requiresReboot,proto3" json:"requires_reboot,omitempty"`
	// SHA-256 digest of the canonical-encoded applied configuration.
	ConfigDigest []byte `protobuf:"bytes,3,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
}

func (x *ApplyConfigResponse) Reset() {
	*x = ApplyConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfigResponse) ProtoMessage() {}

func (x *ApplyConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfigResponse.ProtoReflect.Descriptor instead.
func (*ApplyConfigResponse) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyConfigResponse) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ApplyConfigResponse) GetRequiresReboot() bool {
	if x != nil {
		return x.RequiresReboot
	}
	return false
}

func (x *ApplyConfigResponse) GetConfigDigest() []byte {
	if x != nil {
		return x.ConfigDigest
	}
	return nil
}

type GetStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{2}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *NodeStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetStatus() *NodeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type GetIdentityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetIdentityRequest) Reset() {
	*x = GetIdentityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityRequest) ProtoMessage() {}

func (x *GetIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetIdentityRequest) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{4}
}

type GetIdentityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *GetIdentityResponse) Reset() {
	*x = GetIdentityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdentityResponse) ProtoMessage() {}

func (x *GetIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetIdentityResponse) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *GetIdentityResponse) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

type StartCeremonyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind CeremonyKind `protobuf:"varint,1,opt,name=kind,proto3,enum=cryptos.v1.CeremonyKind" json:"kind,omitempty"`
	// Operator's machine config to apply as part of the ceremony.
	// Carried as YAML bytes; server parses and validates.
	MachineConfigYaml []byte `protobuf:"bytes,2,opt,name=machine_config_yaml,json=machineConfigYaml,proto3" json:"machine_config_yaml,omitempty"`
}

func (x *StartCeremonyRequest) Reset() {
	*x = StartCeremonyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCeremonyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCeremonyRequest) ProtoMessage() {}

func (x *StartCeremonyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCeremonyRequest.ProtoReflect.Descriptor instead.
func (*StartCeremonyRequest) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *StartCeremonyRequest) GetKind() CeremonyKind {
	if x != nil {
		return x.Kind
	}
	return CeremonyKind_CEREMONY_KIND_UNSPECIFIED
}

func (x *StartCeremonyRequest) GetMachineConfigYaml() []byte {
	if x != nil {
		return x.MachineConfigYaml
	}
	return nil
}

// StartCeremonyResponse is the unit streamed back during a ceremony.
// Exactly one detail field on the embedded event is set per message.
type StartCeremonyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *CeremonyEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *StartCeremonyResponse) Reset() {
	*x = StartCeremonyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartCeremonyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCeremonyResponse) ProtoMessage() {}

func (x *StartCeremonyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCeremonyResponse.ProtoReflect.Descriptor instead.
func (*StartCeremonyResponse) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *StartCeremonyResponse) GetEvent() *CeremonyEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// SignCSRRequest carries a DER-encoded PKCS#10 CSR and the profile to apply.
// Phase 1 debug build only.
type SignCSRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsrDer  []byte `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	Profile string `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
}

func (x *SignCSRRequest) Reset() {
	*x = SignCSRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignCSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRRequest) ProtoMessage() {}

func (x *SignCSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRRequest.ProtoReflect.Descriptor instead.
func (*SignCSRRequest) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *SignCSRRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *SignCSRRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

type SignCSRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CertDer []byte `protobuf:"bytes,1,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
}

func (x *SignCSRResponse) Reset() {
	*x = SignCSRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignCSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRResponse) ProtoMessage() {}

func (x *SignCSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRResponse.ProtoReflect.Descriptor instead.
func (*SignCSRResponse) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *SignCSRResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

// ResetRequest confirms a destructive node reset. confirm_common_name must
// exactly equal the node's current Root CA CN, or the node refuses the reset.
type ResetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfirmCommonName string `protobuf:"bytes,1,opt,name=confirm_common_name,json=confirmCommonName,proto3" json:"confirm_common_name,omitempty"`
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *ResetRequest) GetConfirmCommonName() string {
	if x != nil {
		return x.ConfirmCommonName
	}
	return ""
}

type ResetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{11}
}

// SignSubordinateCSRRequest carries a DER PKCS#10 CSR and the name of the
// certificate profile the signer stamps (which sets CA:TRUE + pathLen).
type SignSubordinateCSRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsrDer      []byte `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	ProfileName string `protobuf:"bytes,2,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
}

func (x *SignSubordinateCSRRequest) Reset() {
	*x = SignSubordinateCSRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignSubordinateCSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignSubordinateCSRRequest) ProtoMessage() {}

func (x *SignSubordinateCSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignSubordinateCSRRequest.ProtoReflect.Descriptor instead.
func (*SignSubordinateCSRRequest) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{12}
}

func (x *SignSubordinateCSRRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *SignSubordinateCSRRequest) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

// SignSubordinateCSRResponse returns the signed child CA certificate and the
// full issuing chain, leaf-first (child, parent, ..., root).
type SignSubordinateCSRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainDer [][]byte `protobuf:"bytes,1,rep,name=chain_der,json=chainDer,proto3" json:"chain_der,omitempty"`
	ChainPem string   `protobuf:"bytes,2,opt,name=chain_pem,json=chainPem,proto3" json:"chain_pem,omitempty"`
}

func (x *SignSubordinateCSRResponse) Reset() {
	*x = SignSubordinateCSRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignSubordinateCSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignSubordinateCSRResponse) ProtoMessage() {}

func (x *SignSubordinateCSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignSubordinateCSRResponse.ProtoReflect.Descriptor instead.
func (*SignSubordinateCSRResponse) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{13}
}

func (x *SignSubordinateCSRResponse) GetChainDer() [][]byte {
	if x != nil {
		return x.ChainDer
	}
	return nil
}

func (x *SignSubordinateCSRResponse) GetChainPem() string {
	if x != nil {
		return x.ChainPem
	}
	return ""
}

// IssueLeafRequest carries a DER PKCS#10 CSR and the leaf profile name.
type IssueLeafRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsrDer      []byte `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	ProfileName string `protobuf:"bytes,2,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
}

func (x *IssueLeafRequest) Reset() {
	*x = IssueLeafRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueLeafRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueLeafRequest) ProtoMessage() {}

func (x *IssueLeafRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueLeafRequest.ProtoReflect.Descriptor instead.
func (*IssueLeafRequest) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{14}
}

func (x *IssueLeafRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

func (x *IssueLeafRequest) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

type IssueLeafResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CertDer []byte `protobuf:"bytes,1,opt,name=cert_der,json=certDer,proto3" json:"cert_der,omitempty"`
}

func (x *IssueLeafResponse) Reset() {
	*x = IssueLeafResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IssueLeafResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueLeafResponse) ProtoMessage() {}

func (x *IssueLeafResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueLeafResponse.ProtoReflect.Descriptor instead.
func (*IssueLeafResponse) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{15}
}

func (x *IssueLeafResponse) GetCertDer() []byte {
	if x != nil {
		return x.CertDer
	}
	return nil
}

type GetSubordinateCSRRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSubordinateCSRRequest) Reset() {
	*x = GetSubordinateCSRRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubordinateCSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubordinateCSRRequest) ProtoMessage() {}

func (x *GetSubordinateCSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubordinateCSRRequest.ProtoReflect.Descriptor instead.
func (*GetSubordinateCSRRequest) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{16}
}

type GetSubordinateCSRResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CsrDer []byte `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
}

func (x *GetSubordinateCSRResponse) Reset() {
	*x = GetSubordinateCSRResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSubordinateCSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubordinateCSRResponse) ProtoMessage() {}

func (x *GetSubordinateCSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubordinateCSRResponse.ProtoReflect.Descriptor instead.
func (*GetSubordinateCSRResponse) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{17}
}

func (x *GetSubordinateCSRResponse) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

// SubmitSubordinateCertificateRequest carries the parent-signed chain,
// leaf-first (this node's cert, parent, ..., root).
type SubmitSubordinateCertificateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainDer [][]byte `protobuf:"bytes,1,rep,name=chain_der,json=chainDer,proto3" json:"chain_der,omitempty"`
	ChainPem string   `protobuf:"bytes,2,opt,name=chain_pem,json=chainPem,proto3" json:"chain_pem,omitempty"`
}

func (x *SubmitSubordinateCertificateRequest) Reset() {
	*x = SubmitSubordinateCertificateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitSubordinateCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSubordinateCertificateRequest) ProtoMessage() {}

func (x *SubmitSubordinateCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSubordinateCertificateRequest.ProtoReflect.Descriptor instead.
func (*SubmitSubordinateCertificateRequest) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{18}
}

func (x *SubmitSubordinateCertificateRequest) GetChainDer() [][]byte {
	if x != nil {
		return x.ChainDer
	}
	return nil
}

func (x *SubmitSubordinateCertificateRequest) GetChainPem() string {
	if x != nil {
		return x.ChainPem
	}
	return ""
}

type SubmitSubordinateCertificateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Identity *Identity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
}

func (x *SubmitSubordinateCertificateResponse) Reset() {
	*x = SubmitSubordinateCertificateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cryptos_v1_node_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitSubordinateCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSubordinateCertificateResponse) ProtoMessage() {}

func (x *SubmitSubordinateCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cryptos_v1_node_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSubordinateCertificateResponse.ProtoReflect.Descriptor instead.
func (*SubmitSubordinateCertificateResponse) Descriptor() ([]byte, []int) {
	return file_cryptos_v1_node_proto_rawDescGZIP(), []int{19}
}

func (x *SubmitSubordinateCertificateResponse) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

var File_cryptos_v1_node_proto protoreflect.FileDescriptor

var file_cryptos_v1_node_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6e, 0x6f, 0x64,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73,
	0x2e, 0x76, 0x31, 0x1a, 0x19, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f,
	0x63, 0x65, 0x72, 0x65, 0x6d, 0x6f, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73,
	0x2f, 0x76, 0x31, 0x2f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x17, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x47, 0x0a, 0x12, 0x41,
	0x70, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x31, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x22, 0x83, 0x01, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x0a, 0x0f,
	0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x73, 0x52,
	0x65, 0x62, 0x6f, 0x6f, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f,
	0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x43,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x30, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x22, 0x74, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x65, 0x72, 0x65, 0x6d,
	0x6f, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x65, 0x72, 0x65, 0x6d, 0x6f, 0x6e, 0x79, 0x4b, 0x69,
	0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x6d, 0x61, 0x63, 0x68,
	0x69, 0x6e, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x79, 0x61, 0x6d, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x6d, 0x61, 0x63, 0x68, 0x69, 0x6e, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x59, 0x61, 0x6d, 0x6c, 0x22, 0x48, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x65, 0x72, 0x65, 0x6d, 0x6f, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2f, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x65,
	0x72, 0x65, 0x6d, 0x6f, 0x6e, 0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x22, 0x43, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x53, 0x52, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x73, 0x72, 0x5f, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x73, 0x72, 0x44, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x2c, 0x0a, 0x0f, 0x53, 0x69, 0x67, 0x6e, 0x43,
	0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x65,
	0x72, 0x74, 0x5f, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x65,
	0x72, 0x74, 0x44, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x0f, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x57, 0x0a, 0x19, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x75,
	0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x73, 0x72, 0x5f, 0x64, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x73, 0x72, 0x44, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x56, 0x0a, 0x1a, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x43, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x44, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x5f, 0x70, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x50, 0x65, 0x6d, 0x22, 0x4e, 0x0a, 0x10, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x73, 0x72, 0x5f, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x73,
	0x72, 0x44, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x2e, 0x0a, 0x11, 0x49, 0x73, 0x73, 0x75, 0x65,
	0x4c, 0x65, 0x61, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x63, 0x65, 0x72, 0x74, 0x5f, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x63, 0x65, 0x72, 0x74, 0x44, 0x65, 0x72, 0x22, 0x1a, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x75,
	0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x73, 0x72, 0x5f, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x63, 0x73, 0x72, 0x44, 0x65, 0x72, 0x22, 0x5f, 0x0a, 0x23, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x65,
	0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x44, 0x65, 0x72, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x70, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x50, 0x65, 0x6d, 0x22, 0x58, 0x0a, 0x24, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x32, 0xe6, 0x06, 0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x1e, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1c, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1e, 0x2e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56,
	0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x65, 0x72, 0x65, 0x6d, 0x6f, 0x6e, 0x79, 0x12,
	0x20, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x43, 0x65, 0x72, 0x65, 0x6d, 0x6f, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x21, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x43, 0x65, 0x72, 0x65, 0x6d, 0x6f, 0x6e, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x42, 0x0a, 0x07, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x53,
	0x52, 0x12, 0x1a, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x69, 0x67, 0x6e, 0x43, 0x53, 0x52, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x43,
	0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x12, 0x53, 0x69,
	0x67, 0x6e, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x53, 0x52,
	0x12, 0x25, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x53, 0x52,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x43, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x48, 0x0a, 0x09, 0x49, 0x73, 0x73, 0x75, 0x65, 0x4c, 0x65, 0x61, 0x66, 0x12, 0x1c, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x4c,
	0x65, 0x61, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x73, 0x73, 0x75, 0x65, 0x4c, 0x65, 0x61,
	0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x53, 0x52, 0x12, 0x24,
	0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x53, 0x52, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x43, 0x53, 0x52, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x81, 0x01, 0x0a, 0x1c,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x2f, 0x2e, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x62, 0x6d, 0x69,
	0x74, 0x53, 0x75, 0x62, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3c, 0x0a, 0x05, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x19, 0x2e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x34, 0x5a,
	0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x72, 0x79, 0x70,
	0x74, 0x4f, 0x53, 0x2d, 0x50, 0x4b, 0x49, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x6f, 0x2f, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x72, 0x79, 0x70, 0x74, 0x6f,
	0x73, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cryptos_v1_node_proto_rawDescOnce sync.Once
	file_cryptos_v1_node_proto_rawDescData = file_cryptos_v1_node_proto_rawDesc
)

func file_cryptos_v1_node_proto_rawDescGZIP() []byte {
	file_cryptos_v1_node_proto_rawDescOnce.Do(func() {
		file_cryptos_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_cryptos_v1_node_proto_rawDescData)
	})
	return file_cryptos_v1_node_proto_rawDescData
}

var file_cryptos_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_cryptos_v1_node_proto_goTypes = []any{
	(*ApplyConfigRequest)(nil),                   // 0: cryptos.v1.ApplyConfigRequest
	(*ApplyConfigResponse)(nil),                  // 1: cryptos.v1.ApplyConfigResponse
	(*GetStatusRequest)(nil),                     // 2: cryptos.v1.GetStatusRequest
	(*GetStatusResponse)(nil),                    // 3: cryptos.v1.GetStatusResponse
	(*GetIdentityRequest)(nil),                   // 4: cryptos.v1.GetIdentityRequest
	(*GetIdentityResponse)(nil),                  // 5: cryptos.v1.GetIdentityResponse
	(*StartCeremonyRequest)(nil),                 // 6: cryptos.v1.StartCeremonyRequest
	(*StartCeremonyResponse)(nil),                // 7: cryptos.v1.StartCeremonyResponse
	(*SignCSRRequest)(nil),                       // 8: cryptos.v1.SignCSRRequest
	(*SignCSRResponse)(nil),                      // 9: cryptos.v1.SignCSRResponse
	(*ResetRequest)(nil),                         // 10: cryptos.v1.ResetRequest
	(*ResetResponse)(nil),                        // 11: cryptos.v1.ResetResponse
	(*SignSubordinateCSRRequest)(nil),            // 12: cryptos.v1.SignSubordinateCSRRequest
	(*SignSubordinateCSRResponse)(nil),           // 13: cryptos.v1.SignSubordinateCSRResponse
	(*IssueLeafRequest)(nil),                     // 14: cryptos.v1.IssueLeafRequest
	(*IssueLeafResponse)(nil),                    // 15: cryptos.v1.IssueLeafResponse
	(*GetSubordinateCSRRequest)(nil),             // 16: cryptos.v1.GetSubordinateCSRRequest
	(*GetSubordinateCSRResponse)(nil),            // 17: cryptos.v1.GetSubordinateCSRResponse
	(*SubmitSubordinateCertificateRequest)(nil),  // 18: cryptos.v1.SubmitSubordinateCertificateRequest
	(*SubmitSubordinateCertificateResponse)(nil), // 19: cryptos.v1.SubmitSubordinateCertificateResponse
	(*MachineConfig)(nil),                        // 20: cryptos.v1.MachineConfig
	(*NodeStatus)(nil),                           // 21: cryptos.v1.NodeStatus
	(*Identity)(nil),                             // 22: cryptos.v1.Identity
	(CeremonyKind)(0),                            // 23: cryptos.v1.CeremonyKind
	(*CeremonyEvent)(nil),                        // 24: cryptos.v1.CeremonyEvent
}
var file_cryptos_v1_node_proto_depIdxs = []int32{
	20, // 0: cryptos.v1.ApplyConfigRequest.config:type_name -> cryptos.v1.MachineConfig
	21, // 1: cryptos.v1.GetStatusResponse.status:type_name -> cryptos.v1.NodeStatus
	22, // 2: cryptos.v1.GetIdentityResponse.identity:type_name -> cryptos.v1.Identity
	23, // 3: cryptos.v1.StartCeremonyRequest.kind:type_name -> cryptos.v1.CeremonyKind
	24, // 4: cryptos.v1.StartCeremonyResponse.event:type_name -> cryptos.v1.CeremonyEvent
	22, // 5: cryptos.v1.SubmitSubordinateCertificateResponse.identity:type_name -> cryptos.v1.Identity
	0,  // 6: cryptos.v1.NodeService.ApplyConfig:input_type -> cryptos.v1.ApplyConfigRequest
	2,  // 7: cryptos.v1.NodeService.GetStatus:input_type -> cryptos.v1.GetStatusRequest
	4,  // 8: cryptos.v1.NodeService.GetIdentity:input_type -> cryptos.v1.GetIdentityRequest
	6,  // 9: cryptos.v1.NodeService.StartCeremony:input_type -> cryptos.v1.StartCeremonyRequest
	8,  // 10: cryptos.v1.NodeService.SignCSR:input_type -> cryptos.v1.SignCSRRequest
	12, // 11: cryptos.v1.NodeService.SignSubordinateCSR:input_type -> cryptos.v1.SignSubordinateCSRRequest
	14, // 12: cryptos.v1.NodeService.IssueLeaf:input_type -> cryptos.v1.IssueLeafRequest
	16, // 13: cryptos.v1.NodeService.GetSubordinateCSR:input_type -> cryptos.v1.GetSubordinateCSRRequest
	18, // 14: cryptos.v1.NodeService.SubmitSubordinateCertificate:input_type -> cryptos.v1.SubmitSubordinateCertificateRequest
	10, // 15: cryptos.v1.NodeService.Reset:input_type -> cryptos.v1.ResetRequest
	1,  // 16: cryptos.v1.NodeService.ApplyConfig:output_type -> cryptos.v1.ApplyConfigResponse
	3,  // 17: cryptos.v1.NodeService.GetStatus:output_type -> cryptos.v1.GetStatusResponse
	5,  // 18: cryptos.v1.NodeService.GetIdentity:output_type -> cryptos.v1.GetIdentityResponse
	7,  // 19: cryptos.v1.NodeService.StartCeremony:output_type -> cryptos.v1.StartCeremonyResponse
	9,  // 20: cryptos.v1.NodeService.SignCSR:output_type -> cryptos.v1.SignCSRResponse
	13, // 21: cryptos.v1.NodeService.SignSubordinateCSR:output_type -> cryptos.v1.SignSubordinateCSRResponse
	15, // 22: cryptos.v1.NodeService.IssueLeaf:output_type -> cryptos.v1.IssueLeafResponse
	17, // 23: cryptos.v1.NodeService.GetSubordinateCSR:output_type -> cryptos.v1.GetSubordinateCSRResponse
	19, // 24: cryptos.v1.NodeService.SubmitSubordinateCertificate:output_type -> cryptos.v1.SubmitSubordinateCertificateResponse
	11, // 25: cryptos.v1.NodeService.Reset:output_type -> cryptos.v1.ResetResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_cryptos_v1_node_proto_init() }
func file_cryptos_v1_node_proto_init() {
	if File_cryptos_v1_node_proto != nil {
		return
	}
	file_cryptos_v1_ceremony_proto_init()
	file_cryptos_v1_config_proto_init()
	file_cryptos_v1_identity_proto_init()
	file_cryptos_v1_status_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cryptos_v1_node_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ApplyConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ApplyConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetIdentityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetIdentityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*StartCeremonyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*StartCeremonyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*SignCSRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*SignCSRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*ResetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ResetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*SignSubordinateCSRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*SignSubordinateCSRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*IssueLeafRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*IssueLeafResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*GetSubordinateCSRRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*GetSubordinateCSRResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*SubmitSubordinateCertificateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cryptos_v1_node_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*SubmitSubordinateCertificateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cryptos_v1_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cryptos_v1_node_proto_goTypes,
		DependencyIndexes: file_cryptos_v1_node_proto_depIdxs,
		MessageInfos:      file_cryptos_v1_node_proto_msgTypes,
	}.Build()
	File_cryptos_v1_node_proto = out.File
	file_cryptos_v1_node_proto_rawDesc = nil
	file_cryptos_v1_node_proto_goTypes = nil
	file_cryptos_v1_node_proto_depIdxs = nil
}
