// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: cryptos/v1/node.proto

package cryptosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeService_ApplyConfig_FullMethodName   = "/cryptos.v1.NodeService/ApplyConfig"
	NodeService_GetStatus_FullMethodName     = "/cryptos.v1.NodeService/GetStatus"
	NodeService_GetIdentity_FullMethodName   = "/cryptos.v1.NodeService/GetIdentity"
	NodeService_StartCeremony_FullMethodName = "/cryptos.v1.NodeService/StartCeremony"
	NodeService_SignCSR_FullMethodName       = "/cryptos.v1.NodeService/SignCSR"
)

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeService is the Phase 1 management surface for a single CryptOS node.
// All RPCs are served over mTLS gRPC on port 443 of the management
// interface, plus a local UNIX socket for on-box cryptosctl access.
//
// Phase 1 ships exactly these RPCs. Phase 2 splits SignCSR into
// role-restricted RPCs and adds protocol-adapter management.
type NodeServiceClient interface {
	// ApplyConfig sets the node's declarative machine configuration.
	// Returns requires_reboot=true when the change cannot take effect at runtime.
	ApplyConfig(ctx context.Context, in *ApplyConfigRequest, opts ...grpc.CallOption) (*ApplyConfigResponse, error)
	// GetStatus returns node role, identity state, and subsystem health.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// GetIdentity returns the node's CA certificate chain in DER and PEM.
	GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*GetIdentityResponse, error)
	// StartCeremony drives the first-boot ceremony. Operator-initiated;
	// streams progress events until completion. Only valid when the node
	// is in the no-identity state.
	StartCeremony(ctx context.Context, in *StartCeremonyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StartCeremonyResponse], error)
	// SignCSR signs a Certificate Signing Request with the Root CA key.
	// Phase 1 debug-only: included only in builds compiled with
	// -tags=debug_signcsr. Phase 2 replaces this with role-restricted
	// RPCs (Root.SignSubordinateCSR and an internal Issuing.IssueLeaf).
	SignCSR(ctx context.Context, in *SignCSRRequest, opts ...grpc.CallOption) (*SignCSRResponse, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) ApplyConfig(ctx context.Context, in *ApplyConfigRequest, opts ...grpc.CallOption) (*ApplyConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyConfigResponse)
	err := c.cc.Invoke(ctx, NodeService_ApplyConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, NodeService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) GetIdentity(ctx context.Context, in *GetIdentityRequest, opts ...grpc.CallOption) (*GetIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdentityResponse)
	err := c.cc.Invoke(ctx, NodeService_GetIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) StartCeremony(ctx context.Context, in *StartCeremonyRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StartCeremonyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeService_ServiceDesc.Streams[0], NodeService_StartCeremony_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartCeremonyRequest, StartCeremonyResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StartCeremonyClient = grpc.ServerStreamingClient[StartCeremonyResponse]

func (c *nodeServiceClient) SignCSR(ctx context.Context, in *SignCSRRequest, opts ...grpc.CallOption) (*SignCSRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignCSRResponse)
	err := c.cc.Invoke(ctx, NodeService_SignCSR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations should embed UnimplementedNodeServiceServer
// for forward compatibility.
//
// NodeService is the Phase 1 management surface for a single CryptOS node.
// All RPCs are served over mTLS gRPC on port 443 of the management
// interface, plus a local UNIX socket for on-box cryptosctl access.
//
// Phase 1 ships exactly these RPCs. Phase 2 splits SignCSR into
// role-restricted RPCs and adds protocol-adapter management.
type NodeServiceServer interface {
	// ApplyConfig sets the node's declarative machine configuration.
	// Returns requires_reboot=true when the change cannot take effect at runtime.
	ApplyConfig(context.Context, *ApplyConfigRequest) (*ApplyConfigResponse, error)
	// GetStatus returns node role, identity state, and subsystem health.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// GetIdentity returns the node's CA certificate chain in DER and PEM.
	GetIdentity(context.Context, *GetIdentityRequest) (*GetIdentityResponse, error)
	// StartCeremony drives the first-boot ceremony. Operator-initiated;
	// streams progress events until completion. Only valid when the node
	// is in the no-identity state.
	StartCeremony(*StartCeremonyRequest, grpc.ServerStreamingServer[StartCeremonyResponse]) error
	// SignCSR signs a Certificate Signing Request with the Root CA key.
	// Phase 1 debug-only: included only in builds compiled with
	// -tags=debug_signcsr. Phase 2 replaces this with role-restricted
	// RPCs (Root.SignSubordinateCSR and an internal Issuing.IssueLeaf).
	SignCSR(context.Context, *SignCSRRequest) (*SignCSRResponse, error)
}

// UnimplementedNodeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeServiceServer struct{}

func (UnimplementedNodeServiceServer) ApplyConfig(context.Context, *ApplyConfigRequest) (*ApplyConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyConfig not implemented")
}
func (UnimplementedNodeServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedNodeServiceServer) GetIdentity(context.Context, *GetIdentityRequest) (*GetIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentity not implemented")
}
func (UnimplementedNodeServiceServer) StartCeremony(*StartCeremonyRequest, grpc.ServerStreamingServer[StartCeremonyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StartCeremony not implemented")
}
func (UnimplementedNodeServiceServer) SignCSR(context.Context, *SignCSRRequest) (*SignCSRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignCSR not implemented")
}
func (UnimplementedNodeServiceServer) testEmbeddedByValue() {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_ApplyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).ApplyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_ApplyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).ApplyConfig(ctx, req.(*ApplyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_GetIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).GetIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_GetIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).GetIdentity(ctx, req.(*GetIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_StartCeremony_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartCeremonyRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeServiceServer).StartCeremony(m, &grpc.GenericServerStream[StartCeremonyRequest, StartCeremonyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeService_StartCeremonyServer = grpc.ServerStreamingServer[StartCeremonyResponse]

func _NodeService_SignCSR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignCSRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).SignCSR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeService_SignCSR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).SignCSR(ctx, req.(*SignCSRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cryptos.v1.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyConfig",
			Handler:    _NodeService_ApplyConfig_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _NodeService_GetStatus_Handler,
		},
		{
			MethodName: "GetIdentity",
			Handler:    _NodeService_GetIdentity_Handler,
		},
		{
			MethodName: "SignCSR",
			Handler:    _NodeService_SignCSR_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartCeremony",
			Handler:       _NodeService_StartCeremony_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cryptos/v1/node.proto",
}
