// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cryptos/v1/node.proto

package cryptosv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/CryptOS-PKI/api/go/cryptos/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// NodeServiceName is the fully-qualified name of the NodeService service.
	NodeServiceName = "cryptos.v1.NodeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// NodeServiceApplyConfigProcedure is the fully-qualified name of the NodeService's ApplyConfig RPC.
	NodeServiceApplyConfigProcedure = "/cryptos.v1.NodeService/ApplyConfig"
	// NodeServiceGetStatusProcedure is the fully-qualified name of the NodeService's GetStatus RPC.
	NodeServiceGetStatusProcedure = "/cryptos.v1.NodeService/GetStatus"
	// NodeServiceGetIdentityProcedure is the fully-qualified name of the NodeService's GetIdentity RPC.
	NodeServiceGetIdentityProcedure = "/cryptos.v1.NodeService/GetIdentity"
	// NodeServiceStartCeremonyProcedure is the fully-qualified name of the NodeService's StartCeremony
	// RPC.
	NodeServiceStartCeremonyProcedure = "/cryptos.v1.NodeService/StartCeremony"
	// NodeServiceSignCSRProcedure is the fully-qualified name of the NodeService's SignCSR RPC.
	NodeServiceSignCSRProcedure = "/cryptos.v1.NodeService/SignCSR"
	// NodeServiceSignSubordinateCSRProcedure is the fully-qualified name of the NodeService's
	// SignSubordinateCSR RPC.
	NodeServiceSignSubordinateCSRProcedure = "/cryptos.v1.NodeService/SignSubordinateCSR"
	// NodeServiceIssueLeafProcedure is the fully-qualified name of the NodeService's IssueLeaf RPC.
	NodeServiceIssueLeafProcedure = "/cryptos.v1.NodeService/IssueLeaf"
	// NodeServiceGetSubordinateCSRProcedure is the fully-qualified name of the NodeService's
	// GetSubordinateCSR RPC.
	NodeServiceGetSubordinateCSRProcedure = "/cryptos.v1.NodeService/GetSubordinateCSR"
	// NodeServiceSubmitSubordinateCertificateProcedure is the fully-qualified name of the NodeService's
	// SubmitSubordinateCertificate RPC.
	NodeServiceSubmitSubordinateCertificateProcedure = "/cryptos.v1.NodeService/SubmitSubordinateCertificate"
	// NodeServiceRevokeCertificateProcedure is the fully-qualified name of the NodeService's
	// RevokeCertificate RPC.
	NodeServiceRevokeCertificateProcedure = "/cryptos.v1.NodeService/RevokeCertificate"
	// NodeServiceListIssuedProcedure is the fully-qualified name of the NodeService's ListIssued RPC.
	NodeServiceListIssuedProcedure = "/cryptos.v1.NodeService/ListIssued"
	// NodeServiceListRevocationsProcedure is the fully-qualified name of the NodeService's
	// ListRevocations RPC.
	NodeServiceListRevocationsProcedure = "/cryptos.v1.NodeService/ListRevocations"
	// NodeServiceExportCAKeyProcedure is the fully-qualified name of the NodeService's ExportCAKey RPC.
	NodeServiceExportCAKeyProcedure = "/cryptos.v1.NodeService/ExportCAKey"
	// NodeServiceImportCAKeyProcedure is the fully-qualified name of the NodeService's ImportCAKey RPC.
	NodeServiceImportCAKeyProcedure = "/cryptos.v1.NodeService/ImportCAKey"
	// NodeServiceBeginKeyRotationProcedure is the fully-qualified name of the NodeService's
	// BeginKeyRotation RPC.
	NodeServiceBeginKeyRotationProcedure = "/cryptos.v1.NodeService/BeginKeyRotation"
	// NodeServiceCompleteKeyRotationProcedure is the fully-qualified name of the NodeService's
	// CompleteKeyRotation RPC.
	NodeServiceCompleteKeyRotationProcedure = "/cryptos.v1.NodeService/CompleteKeyRotation"
	// NodeServiceResetProcedure is the fully-qualified name of the NodeService's Reset RPC.
	NodeServiceResetProcedure = "/cryptos.v1.NodeService/Reset"
)

// NodeServiceClient is a client for the cryptos.v1.NodeService service.
type NodeServiceClient interface {
	// ApplyConfig sets the node's declarative machine configuration.
	// Returns requires_reboot=true when the change cannot take effect at runtime.
	ApplyConfig(context.Context, *connect.Request[v1.ApplyConfigRequest]) (*connect.Response[v1.ApplyConfigResponse], error)
	// GetStatus returns node role, identity state, and subsystem health.
	GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error)
	// GetIdentity returns the node's CA certificate chain in DER and PEM.
	GetIdentity(context.Context, *connect.Request[v1.GetIdentityRequest]) (*connect.Response[v1.GetIdentityResponse], error)
	// StartCeremony drives the first-boot ceremony. Operator-initiated;
	// streams progress events until completion. Only valid when the node
	// is in the no-identity state.
	StartCeremony(context.Context, *connect.Request[v1.StartCeremonyRequest]) (*connect.ServerStreamForClient[v1.StartCeremonyResponse], error)
	// SignCSR signs a Certificate Signing Request with the Root CA key.
	// Phase 1 debug-only: included only in builds compiled with
	// -tags=debug_signcsr. Phase 2 replaces this with role-restricted
	// RPCs (Root.SignSubordinateCSR and an internal Issuing.IssueLeaf).
	SignCSR(context.Context, *connect.Request[v1.SignCSRRequest]) (*connect.Response[v1.SignCSRResponse], error)
	// SignSubordinateCSR signs a child CA's CSR into a CA certificate per a
	// named profile (BasicConstraints CA:TRUE, pathLen clamped to the parent's
	// budget) and returns the new cert plus the parent's chain. Role-restricted
	// (a CA that may sign sub-CAs) and authorized by the bootstrap admin;
	// reachable online (parent mTLS) or offline (operator ferry via the local
	// socket). Supersedes the debug-only SignCSR for the CA path.
	SignSubordinateCSR(context.Context, *connect.Request[v1.SignSubordinateCSRRequest]) (*connect.Response[v1.SignSubordinateCSRResponse], error)
	// IssueLeaf signs an end-entity (CA:FALSE) certificate per a named profile.
	// Role-restricted (intermediate/issuing; a root only with the irreversible
	// ack). The internal path the Phase-2 protocol adapters will call.
	IssueLeaf(context.Context, *connect.Request[v1.IssueLeafRequest]) (*connect.Response[v1.IssueLeafResponse], error)
	// GetSubordinateCSR returns the CSR a subordinate node generated on first
	// boot, while it is in IDENTITY_STATE_AWAITING_CERT. The operator carries it
	// to the parent's SignSubordinateCSR (Refused unless awaiting a cert).
	GetSubordinateCSR(context.Context, *connect.Request[v1.GetSubordinateCSRRequest]) (*connect.Response[v1.GetSubordinateCSRResponse], error)
	// SubmitSubordinateCertificate hands a subordinate node the parent-signed
	// certificate + chain. The node verifies the chain roots to its configured
	// parent trust anchor (pki.parent) and that the leaf matches its own key,
	// then commits and becomes ESTABLISHED. Returns the committed identity.
	SubmitSubordinateCertificate(context.Context, *connect.Request[v1.SubmitSubordinateCertificateRequest]) (*connect.Response[v1.SubmitSubordinateCertificateResponse], error)
	// RevokeCertificate marks a certificate this node issued (identified by its
	// hex serial) as revoked with an RFC 5280 reason, records it, and refreshes
	// the CRL. Admin-authorized. NotFound if the serial is not in this node's
	// issued set. Idempotent: re-revoking returns the existing revocation.
	RevokeCertificate(context.Context, *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error)
	// ListIssued returns the certificates this node has issued, for inventory
	// and for the Fleet Manager to drive revocation.
	ListIssued(context.Context, *connect.Request[v1.ListIssuedRequest]) (*connect.Response[v1.ListIssuedResponse], error)
	// ListRevocations returns this node's revoked certificates.
	ListRevocations(context.Context, *connect.Request[v1.ListRevocationsRequest]) (*connect.Response[v1.ListRevocationsResponse], error)
	// ExportCAKey returns an encrypted backup of this node's software CA key and
	// certificate chain, sealed under the operator passphrase. The plaintext key
	// never leaves the node. Admin-authorized; refused on a TPM node (TPM keys
	// are non-exportable by design).
	ExportCAKey(context.Context, *connect.Request[v1.ExportCAKeyRequest]) (*connect.Response[v1.ExportCAKeyResponse], error)
	// ImportCAKey restores a CA from an encrypted backup: it is the recovery
	// counterpart of StartCeremony, valid only on a node whose storage is up but
	// which has no identity yet. It decrypts the envelope with the passphrase and
	// commits the restored key + chain, becoming ESTABLISHED as the same CA.
	ImportCAKey(context.Context, *connect.Request[v1.ImportCAKeyRequest]) (*connect.Response[v1.ImportCAKeyResponse], error)
	// BeginKeyRotation starts a subordinate CA key rotation: the established
	// intermediate/issuing node generates a new key and returns a CSR to ferry to
	// the parent, while continuing to sign with its current key. Admin-authorized;
	// refused on a root or a node with no identity.
	BeginKeyRotation(context.Context, *connect.Request[v1.BeginKeyRotationRequest]) (*connect.Response[v1.BeginKeyRotationResponse], error)
	// CompleteKeyRotation submits the parent-signed chain for the new key. The
	// node verifies it roots to the pinned parent and matches the staged new key,
	// then atomically swaps to the new key + cert. Certificates the old key signed
	// remain valid until they expire.
	CompleteKeyRotation(context.Context, *connect.Request[v1.CompleteKeyRotationRequest]) (*connect.Response[v1.CompleteKeyRotationResponse], error)
	// Reset destroys the node's identity: it erases the state-partition key
	// material (rendering all encrypted data unrecoverable), clears any staged
	// config, and reboots into maintenance. Served ONLY on the local UNIX
	// socket (physical-console trust); the node refuses it over mTLS and in
	// maintenance mode. The caller must echo the current Root CA CN as
	// confirmation.
	Reset(context.Context, *connect.Request[v1.ResetRequest]) (*connect.Response[v1.ResetResponse], error)
}

// NewNodeServiceClient constructs a client for the cryptos.v1.NodeService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewNodeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NodeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nodeServiceMethods := v1.File_cryptos_v1_node_proto.Services().ByName("NodeService").Methods()
	return &nodeServiceClient{
		applyConfig: connect.NewClient[v1.ApplyConfigRequest, v1.ApplyConfigResponse](
			httpClient,
			baseURL+NodeServiceApplyConfigProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ApplyConfig")),
			connect.WithClientOptions(opts...),
		),
		getStatus: connect.NewClient[v1.GetStatusRequest, v1.GetStatusResponse](
			httpClient,
			baseURL+NodeServiceGetStatusProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetStatus")),
			connect.WithClientOptions(opts...),
		),
		getIdentity: connect.NewClient[v1.GetIdentityRequest, v1.GetIdentityResponse](
			httpClient,
			baseURL+NodeServiceGetIdentityProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetIdentity")),
			connect.WithClientOptions(opts...),
		),
		startCeremony: connect.NewClient[v1.StartCeremonyRequest, v1.StartCeremonyResponse](
			httpClient,
			baseURL+NodeServiceStartCeremonyProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("StartCeremony")),
			connect.WithClientOptions(opts...),
		),
		signCSR: connect.NewClient[v1.SignCSRRequest, v1.SignCSRResponse](
			httpClient,
			baseURL+NodeServiceSignCSRProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("SignCSR")),
			connect.WithClientOptions(opts...),
		),
		signSubordinateCSR: connect.NewClient[v1.SignSubordinateCSRRequest, v1.SignSubordinateCSRResponse](
			httpClient,
			baseURL+NodeServiceSignSubordinateCSRProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("SignSubordinateCSR")),
			connect.WithClientOptions(opts...),
		),
		issueLeaf: connect.NewClient[v1.IssueLeafRequest, v1.IssueLeafResponse](
			httpClient,
			baseURL+NodeServiceIssueLeafProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("IssueLeaf")),
			connect.WithClientOptions(opts...),
		),
		getSubordinateCSR: connect.NewClient[v1.GetSubordinateCSRRequest, v1.GetSubordinateCSRResponse](
			httpClient,
			baseURL+NodeServiceGetSubordinateCSRProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("GetSubordinateCSR")),
			connect.WithClientOptions(opts...),
		),
		submitSubordinateCertificate: connect.NewClient[v1.SubmitSubordinateCertificateRequest, v1.SubmitSubordinateCertificateResponse](
			httpClient,
			baseURL+NodeServiceSubmitSubordinateCertificateProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("SubmitSubordinateCertificate")),
			connect.WithClientOptions(opts...),
		),
		revokeCertificate: connect.NewClient[v1.RevokeCertificateRequest, v1.RevokeCertificateResponse](
			httpClient,
			baseURL+NodeServiceRevokeCertificateProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("RevokeCertificate")),
			connect.WithClientOptions(opts...),
		),
		listIssued: connect.NewClient[v1.ListIssuedRequest, v1.ListIssuedResponse](
			httpClient,
			baseURL+NodeServiceListIssuedProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ListIssued")),
			connect.WithClientOptions(opts...),
		),
		listRevocations: connect.NewClient[v1.ListRevocationsRequest, v1.ListRevocationsResponse](
			httpClient,
			baseURL+NodeServiceListRevocationsProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ListRevocations")),
			connect.WithClientOptions(opts...),
		),
		exportCAKey: connect.NewClient[v1.ExportCAKeyRequest, v1.ExportCAKeyResponse](
			httpClient,
			baseURL+NodeServiceExportCAKeyProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ExportCAKey")),
			connect.WithClientOptions(opts...),
		),
		importCAKey: connect.NewClient[v1.ImportCAKeyRequest, v1.ImportCAKeyResponse](
			httpClient,
			baseURL+NodeServiceImportCAKeyProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("ImportCAKey")),
			connect.WithClientOptions(opts...),
		),
		beginKeyRotation: connect.NewClient[v1.BeginKeyRotationRequest, v1.BeginKeyRotationResponse](
			httpClient,
			baseURL+NodeServiceBeginKeyRotationProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("BeginKeyRotation")),
			connect.WithClientOptions(opts...),
		),
		completeKeyRotation: connect.NewClient[v1.CompleteKeyRotationRequest, v1.CompleteKeyRotationResponse](
			httpClient,
			baseURL+NodeServiceCompleteKeyRotationProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("CompleteKeyRotation")),
			connect.WithClientOptions(opts...),
		),
		reset: connect.NewClient[v1.ResetRequest, v1.ResetResponse](
			httpClient,
			baseURL+NodeServiceResetProcedure,
			connect.WithSchema(nodeServiceMethods.ByName("Reset")),
			connect.WithClientOptions(opts...),
		),
	}
}

// nodeServiceClient implements NodeServiceClient.
type nodeServiceClient struct {
	applyConfig                  *connect.Client[v1.ApplyConfigRequest, v1.ApplyConfigResponse]
	getStatus                    *connect.Client[v1.GetStatusRequest, v1.GetStatusResponse]
	getIdentity                  *connect.Client[v1.GetIdentityRequest, v1.GetIdentityResponse]
	startCeremony                *connect.Client[v1.StartCeremonyRequest, v1.StartCeremonyResponse]
	signCSR                      *connect.Client[v1.SignCSRRequest, v1.SignCSRResponse]
	signSubordinateCSR           *connect.Client[v1.SignSubordinateCSRRequest, v1.SignSubordinateCSRResponse]
	issueLeaf                    *connect.Client[v1.IssueLeafRequest, v1.IssueLeafResponse]
	getSubordinateCSR            *connect.Client[v1.GetSubordinateCSRRequest, v1.GetSubordinateCSRResponse]
	submitSubordinateCertificate *connect.Client[v1.SubmitSubordinateCertificateRequest, v1.SubmitSubordinateCertificateResponse]
	revokeCertificate            *connect.Client[v1.RevokeCertificateRequest, v1.RevokeCertificateResponse]
	listIssued                   *connect.Client[v1.ListIssuedRequest, v1.ListIssuedResponse]
	listRevocations              *connect.Client[v1.ListRevocationsRequest, v1.ListRevocationsResponse]
	exportCAKey                  *connect.Client[v1.ExportCAKeyRequest, v1.ExportCAKeyResponse]
	importCAKey                  *connect.Client[v1.ImportCAKeyRequest, v1.ImportCAKeyResponse]
	beginKeyRotation             *connect.Client[v1.BeginKeyRotationRequest, v1.BeginKeyRotationResponse]
	completeKeyRotation          *connect.Client[v1.CompleteKeyRotationRequest, v1.CompleteKeyRotationResponse]
	reset                        *connect.Client[v1.ResetRequest, v1.ResetResponse]
}

// ApplyConfig calls cryptos.v1.NodeService.ApplyConfig.
func (c *nodeServiceClient) ApplyConfig(ctx context.Context, req *connect.Request[v1.ApplyConfigRequest]) (*connect.Response[v1.ApplyConfigResponse], error) {
	return c.applyConfig.CallUnary(ctx, req)
}

// GetStatus calls cryptos.v1.NodeService.GetStatus.
func (c *nodeServiceClient) GetStatus(ctx context.Context, req *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error) {
	return c.getStatus.CallUnary(ctx, req)
}

// GetIdentity calls cryptos.v1.NodeService.GetIdentity.
func (c *nodeServiceClient) GetIdentity(ctx context.Context, req *connect.Request[v1.GetIdentityRequest]) (*connect.Response[v1.GetIdentityResponse], error) {
	return c.getIdentity.CallUnary(ctx, req)
}

// StartCeremony calls cryptos.v1.NodeService.StartCeremony.
func (c *nodeServiceClient) StartCeremony(ctx context.Context, req *connect.Request[v1.StartCeremonyRequest]) (*connect.ServerStreamForClient[v1.StartCeremonyResponse], error) {
	return c.startCeremony.CallServerStream(ctx, req)
}

// SignCSR calls cryptos.v1.NodeService.SignCSR.
func (c *nodeServiceClient) SignCSR(ctx context.Context, req *connect.Request[v1.SignCSRRequest]) (*connect.Response[v1.SignCSRResponse], error) {
	return c.signCSR.CallUnary(ctx, req)
}

// SignSubordinateCSR calls cryptos.v1.NodeService.SignSubordinateCSR.
func (c *nodeServiceClient) SignSubordinateCSR(ctx context.Context, req *connect.Request[v1.SignSubordinateCSRRequest]) (*connect.Response[v1.SignSubordinateCSRResponse], error) {
	return c.signSubordinateCSR.CallUnary(ctx, req)
}

// IssueLeaf calls cryptos.v1.NodeService.IssueLeaf.
func (c *nodeServiceClient) IssueLeaf(ctx context.Context, req *connect.Request[v1.IssueLeafRequest]) (*connect.Response[v1.IssueLeafResponse], error) {
	return c.issueLeaf.CallUnary(ctx, req)
}

// GetSubordinateCSR calls cryptos.v1.NodeService.GetSubordinateCSR.
func (c *nodeServiceClient) GetSubordinateCSR(ctx context.Context, req *connect.Request[v1.GetSubordinateCSRRequest]) (*connect.Response[v1.GetSubordinateCSRResponse], error) {
	return c.getSubordinateCSR.CallUnary(ctx, req)
}

// SubmitSubordinateCertificate calls cryptos.v1.NodeService.SubmitSubordinateCertificate.
func (c *nodeServiceClient) SubmitSubordinateCertificate(ctx context.Context, req *connect.Request[v1.SubmitSubordinateCertificateRequest]) (*connect.Response[v1.SubmitSubordinateCertificateResponse], error) {
	return c.submitSubordinateCertificate.CallUnary(ctx, req)
}

// RevokeCertificate calls cryptos.v1.NodeService.RevokeCertificate.
func (c *nodeServiceClient) RevokeCertificate(ctx context.Context, req *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error) {
	return c.revokeCertificate.CallUnary(ctx, req)
}

// ListIssued calls cryptos.v1.NodeService.ListIssued.
func (c *nodeServiceClient) ListIssued(ctx context.Context, req *connect.Request[v1.ListIssuedRequest]) (*connect.Response[v1.ListIssuedResponse], error) {
	return c.listIssued.CallUnary(ctx, req)
}

// ListRevocations calls cryptos.v1.NodeService.ListRevocations.
func (c *nodeServiceClient) ListRevocations(ctx context.Context, req *connect.Request[v1.ListRevocationsRequest]) (*connect.Response[v1.ListRevocationsResponse], error) {
	return c.listRevocations.CallUnary(ctx, req)
}

// ExportCAKey calls cryptos.v1.NodeService.ExportCAKey.
func (c *nodeServiceClient) ExportCAKey(ctx context.Context, req *connect.Request[v1.ExportCAKeyRequest]) (*connect.Response[v1.ExportCAKeyResponse], error) {
	return c.exportCAKey.CallUnary(ctx, req)
}

// ImportCAKey calls cryptos.v1.NodeService.ImportCAKey.
func (c *nodeServiceClient) ImportCAKey(ctx context.Context, req *connect.Request[v1.ImportCAKeyRequest]) (*connect.Response[v1.ImportCAKeyResponse], error) {
	return c.importCAKey.CallUnary(ctx, req)
}

// BeginKeyRotation calls cryptos.v1.NodeService.BeginKeyRotation.
func (c *nodeServiceClient) BeginKeyRotation(ctx context.Context, req *connect.Request[v1.BeginKeyRotationRequest]) (*connect.Response[v1.BeginKeyRotationResponse], error) {
	return c.beginKeyRotation.CallUnary(ctx, req)
}

// CompleteKeyRotation calls cryptos.v1.NodeService.CompleteKeyRotation.
func (c *nodeServiceClient) CompleteKeyRotation(ctx context.Context, req *connect.Request[v1.CompleteKeyRotationRequest]) (*connect.Response[v1.CompleteKeyRotationResponse], error) {
	return c.completeKeyRotation.CallUnary(ctx, req)
}

// Reset calls cryptos.v1.NodeService.Reset.
func (c *nodeServiceClient) Reset(ctx context.Context, req *connect.Request[v1.ResetRequest]) (*connect.Response[v1.ResetResponse], error) {
	return c.reset.CallUnary(ctx, req)
}

// NodeServiceHandler is an implementation of the cryptos.v1.NodeService service.
type NodeServiceHandler interface {
	// ApplyConfig sets the node's declarative machine configuration.
	// Returns requires_reboot=true when the change cannot take effect at runtime.
	ApplyConfig(context.Context, *connect.Request[v1.ApplyConfigRequest]) (*connect.Response[v1.ApplyConfigResponse], error)
	// GetStatus returns node role, identity state, and subsystem health.
	GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error)
	// GetIdentity returns the node's CA certificate chain in DER and PEM.
	GetIdentity(context.Context, *connect.Request[v1.GetIdentityRequest]) (*connect.Response[v1.GetIdentityResponse], error)
	// StartCeremony drives the first-boot ceremony. Operator-initiated;
	// streams progress events until completion. Only valid when the node
	// is in the no-identity state.
	StartCeremony(context.Context, *connect.Request[v1.StartCeremonyRequest], *connect.ServerStream[v1.StartCeremonyResponse]) error
	// SignCSR signs a Certificate Signing Request with the Root CA key.
	// Phase 1 debug-only: included only in builds compiled with
	// -tags=debug_signcsr. Phase 2 replaces this with role-restricted
	// RPCs (Root.SignSubordinateCSR and an internal Issuing.IssueLeaf).
	SignCSR(context.Context, *connect.Request[v1.SignCSRRequest]) (*connect.Response[v1.SignCSRResponse], error)
	// SignSubordinateCSR signs a child CA's CSR into a CA certificate per a
	// named profile (BasicConstraints CA:TRUE, pathLen clamped to the parent's
	// budget) and returns the new cert plus the parent's chain. Role-restricted
	// (a CA that may sign sub-CAs) and authorized by the bootstrap admin;
	// reachable online (parent mTLS) or offline (operator ferry via the local
	// socket). Supersedes the debug-only SignCSR for the CA path.
	SignSubordinateCSR(context.Context, *connect.Request[v1.SignSubordinateCSRRequest]) (*connect.Response[v1.SignSubordinateCSRResponse], error)
	// IssueLeaf signs an end-entity (CA:FALSE) certificate per a named profile.
	// Role-restricted (intermediate/issuing; a root only with the irreversible
	// ack). The internal path the Phase-2 protocol adapters will call.
	IssueLeaf(context.Context, *connect.Request[v1.IssueLeafRequest]) (*connect.Response[v1.IssueLeafResponse], error)
	// GetSubordinateCSR returns the CSR a subordinate node generated on first
	// boot, while it is in IDENTITY_STATE_AWAITING_CERT. The operator carries it
	// to the parent's SignSubordinateCSR (Refused unless awaiting a cert).
	GetSubordinateCSR(context.Context, *connect.Request[v1.GetSubordinateCSRRequest]) (*connect.Response[v1.GetSubordinateCSRResponse], error)
	// SubmitSubordinateCertificate hands a subordinate node the parent-signed
	// certificate + chain. The node verifies the chain roots to its configured
	// parent trust anchor (pki.parent) and that the leaf matches its own key,
	// then commits and becomes ESTABLISHED. Returns the committed identity.
	SubmitSubordinateCertificate(context.Context, *connect.Request[v1.SubmitSubordinateCertificateRequest]) (*connect.Response[v1.SubmitSubordinateCertificateResponse], error)
	// RevokeCertificate marks a certificate this node issued (identified by its
	// hex serial) as revoked with an RFC 5280 reason, records it, and refreshes
	// the CRL. Admin-authorized. NotFound if the serial is not in this node's
	// issued set. Idempotent: re-revoking returns the existing revocation.
	RevokeCertificate(context.Context, *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error)
	// ListIssued returns the certificates this node has issued, for inventory
	// and for the Fleet Manager to drive revocation.
	ListIssued(context.Context, *connect.Request[v1.ListIssuedRequest]) (*connect.Response[v1.ListIssuedResponse], error)
	// ListRevocations returns this node's revoked certificates.
	ListRevocations(context.Context, *connect.Request[v1.ListRevocationsRequest]) (*connect.Response[v1.ListRevocationsResponse], error)
	// ExportCAKey returns an encrypted backup of this node's software CA key and
	// certificate chain, sealed under the operator passphrase. The plaintext key
	// never leaves the node. Admin-authorized; refused on a TPM node (TPM keys
	// are non-exportable by design).
	ExportCAKey(context.Context, *connect.Request[v1.ExportCAKeyRequest]) (*connect.Response[v1.ExportCAKeyResponse], error)
	// ImportCAKey restores a CA from an encrypted backup: it is the recovery
	// counterpart of StartCeremony, valid only on a node whose storage is up but
	// which has no identity yet. It decrypts the envelope with the passphrase and
	// commits the restored key + chain, becoming ESTABLISHED as the same CA.
	ImportCAKey(context.Context, *connect.Request[v1.ImportCAKeyRequest]) (*connect.Response[v1.ImportCAKeyResponse], error)
	// BeginKeyRotation starts a subordinate CA key rotation: the established
	// intermediate/issuing node generates a new key and returns a CSR to ferry to
	// the parent, while continuing to sign with its current key. Admin-authorized;
	// refused on a root or a node with no identity.
	BeginKeyRotation(context.Context, *connect.Request[v1.BeginKeyRotationRequest]) (*connect.Response[v1.BeginKeyRotationResponse], error)
	// CompleteKeyRotation submits the parent-signed chain for the new key. The
	// node verifies it roots to the pinned parent and matches the staged new key,
	// then atomically swaps to the new key + cert. Certificates the old key signed
	// remain valid until they expire.
	CompleteKeyRotation(context.Context, *connect.Request[v1.CompleteKeyRotationRequest]) (*connect.Response[v1.CompleteKeyRotationResponse], error)
	// Reset destroys the node's identity: it erases the state-partition key
	// material (rendering all encrypted data unrecoverable), clears any staged
	// config, and reboots into maintenance. Served ONLY on the local UNIX
	// socket (physical-console trust); the node refuses it over mTLS and in
	// maintenance mode. The caller must echo the current Root CA CN as
	// confirmation.
	Reset(context.Context, *connect.Request[v1.ResetRequest]) (*connect.Response[v1.ResetResponse], error)
}

// NewNodeServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewNodeServiceHandler(svc NodeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nodeServiceMethods := v1.File_cryptos_v1_node_proto.Services().ByName("NodeService").Methods()
	nodeServiceApplyConfigHandler := connect.NewUnaryHandler(
		NodeServiceApplyConfigProcedure,
		svc.ApplyConfig,
		connect.WithSchema(nodeServiceMethods.ByName("ApplyConfig")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceGetStatusHandler := connect.NewUnaryHandler(
		NodeServiceGetStatusProcedure,
		svc.GetStatus,
		connect.WithSchema(nodeServiceMethods.ByName("GetStatus")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceGetIdentityHandler := connect.NewUnaryHandler(
		NodeServiceGetIdentityProcedure,
		svc.GetIdentity,
		connect.WithSchema(nodeServiceMethods.ByName("GetIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceStartCeremonyHandler := connect.NewServerStreamHandler(
		NodeServiceStartCeremonyProcedure,
		svc.StartCeremony,
		connect.WithSchema(nodeServiceMethods.ByName("StartCeremony")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceSignCSRHandler := connect.NewUnaryHandler(
		NodeServiceSignCSRProcedure,
		svc.SignCSR,
		connect.WithSchema(nodeServiceMethods.ByName("SignCSR")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceSignSubordinateCSRHandler := connect.NewUnaryHandler(
		NodeServiceSignSubordinateCSRProcedure,
		svc.SignSubordinateCSR,
		connect.WithSchema(nodeServiceMethods.ByName("SignSubordinateCSR")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceIssueLeafHandler := connect.NewUnaryHandler(
		NodeServiceIssueLeafProcedure,
		svc.IssueLeaf,
		connect.WithSchema(nodeServiceMethods.ByName("IssueLeaf")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceGetSubordinateCSRHandler := connect.NewUnaryHandler(
		NodeServiceGetSubordinateCSRProcedure,
		svc.GetSubordinateCSR,
		connect.WithSchema(nodeServiceMethods.ByName("GetSubordinateCSR")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceSubmitSubordinateCertificateHandler := connect.NewUnaryHandler(
		NodeServiceSubmitSubordinateCertificateProcedure,
		svc.SubmitSubordinateCertificate,
		connect.WithSchema(nodeServiceMethods.ByName("SubmitSubordinateCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceRevokeCertificateHandler := connect.NewUnaryHandler(
		NodeServiceRevokeCertificateProcedure,
		svc.RevokeCertificate,
		connect.WithSchema(nodeServiceMethods.ByName("RevokeCertificate")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceListIssuedHandler := connect.NewUnaryHandler(
		NodeServiceListIssuedProcedure,
		svc.ListIssued,
		connect.WithSchema(nodeServiceMethods.ByName("ListIssued")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceListRevocationsHandler := connect.NewUnaryHandler(
		NodeServiceListRevocationsProcedure,
		svc.ListRevocations,
		connect.WithSchema(nodeServiceMethods.ByName("ListRevocations")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceExportCAKeyHandler := connect.NewUnaryHandler(
		NodeServiceExportCAKeyProcedure,
		svc.ExportCAKey,
		connect.WithSchema(nodeServiceMethods.ByName("ExportCAKey")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceImportCAKeyHandler := connect.NewUnaryHandler(
		NodeServiceImportCAKeyProcedure,
		svc.ImportCAKey,
		connect.WithSchema(nodeServiceMethods.ByName("ImportCAKey")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceBeginKeyRotationHandler := connect.NewUnaryHandler(
		NodeServiceBeginKeyRotationProcedure,
		svc.BeginKeyRotation,
		connect.WithSchema(nodeServiceMethods.ByName("BeginKeyRotation")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceCompleteKeyRotationHandler := connect.NewUnaryHandler(
		NodeServiceCompleteKeyRotationProcedure,
		svc.CompleteKeyRotation,
		connect.WithSchema(nodeServiceMethods.ByName("CompleteKeyRotation")),
		connect.WithHandlerOptions(opts...),
	)
	nodeServiceResetHandler := connect.NewUnaryHandler(
		NodeServiceResetProcedure,
		svc.Reset,
		connect.WithSchema(nodeServiceMethods.ByName("Reset")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cryptos.v1.NodeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NodeServiceApplyConfigProcedure:
			nodeServiceApplyConfigHandler.ServeHTTP(w, r)
		case NodeServiceGetStatusProcedure:
			nodeServiceGetStatusHandler.ServeHTTP(w, r)
		case NodeServiceGetIdentityProcedure:
			nodeServiceGetIdentityHandler.ServeHTTP(w, r)
		case NodeServiceStartCeremonyProcedure:
			nodeServiceStartCeremonyHandler.ServeHTTP(w, r)
		case NodeServiceSignCSRProcedure:
			nodeServiceSignCSRHandler.ServeHTTP(w, r)
		case NodeServiceSignSubordinateCSRProcedure:
			nodeServiceSignSubordinateCSRHandler.ServeHTTP(w, r)
		case NodeServiceIssueLeafProcedure:
			nodeServiceIssueLeafHandler.ServeHTTP(w, r)
		case NodeServiceGetSubordinateCSRProcedure:
			nodeServiceGetSubordinateCSRHandler.ServeHTTP(w, r)
		case NodeServiceSubmitSubordinateCertificateProcedure:
			nodeServiceSubmitSubordinateCertificateHandler.ServeHTTP(w, r)
		case NodeServiceRevokeCertificateProcedure:
			nodeServiceRevokeCertificateHandler.ServeHTTP(w, r)
		case NodeServiceListIssuedProcedure:
			nodeServiceListIssuedHandler.ServeHTTP(w, r)
		case NodeServiceListRevocationsProcedure:
			nodeServiceListRevocationsHandler.ServeHTTP(w, r)
		case NodeServiceExportCAKeyProcedure:
			nodeServiceExportCAKeyHandler.ServeHTTP(w, r)
		case NodeServiceImportCAKeyProcedure:
			nodeServiceImportCAKeyHandler.ServeHTTP(w, r)
		case NodeServiceBeginKeyRotationProcedure:
			nodeServiceBeginKeyRotationHandler.ServeHTTP(w, r)
		case NodeServiceCompleteKeyRotationProcedure:
			nodeServiceCompleteKeyRotationHandler.ServeHTTP(w, r)
		case NodeServiceResetProcedure:
			nodeServiceResetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedNodeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedNodeServiceHandler struct{}

func (UnimplementedNodeServiceHandler) ApplyConfig(context.Context, *connect.Request[v1.ApplyConfigRequest]) (*connect.Response[v1.ApplyConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.ApplyConfig is not implemented"))
}

func (UnimplementedNodeServiceHandler) GetStatus(context.Context, *connect.Request[v1.GetStatusRequest]) (*connect.Response[v1.GetStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.GetStatus is not implemented"))
}

func (UnimplementedNodeServiceHandler) GetIdentity(context.Context, *connect.Request[v1.GetIdentityRequest]) (*connect.Response[v1.GetIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.GetIdentity is not implemented"))
}

func (UnimplementedNodeServiceHandler) StartCeremony(context.Context, *connect.Request[v1.StartCeremonyRequest], *connect.ServerStream[v1.StartCeremonyResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.StartCeremony is not implemented"))
}

func (UnimplementedNodeServiceHandler) SignCSR(context.Context, *connect.Request[v1.SignCSRRequest]) (*connect.Response[v1.SignCSRResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.SignCSR is not implemented"))
}

func (UnimplementedNodeServiceHandler) SignSubordinateCSR(context.Context, *connect.Request[v1.SignSubordinateCSRRequest]) (*connect.Response[v1.SignSubordinateCSRResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.SignSubordinateCSR is not implemented"))
}

func (UnimplementedNodeServiceHandler) IssueLeaf(context.Context, *connect.Request[v1.IssueLeafRequest]) (*connect.Response[v1.IssueLeafResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.IssueLeaf is not implemented"))
}

func (UnimplementedNodeServiceHandler) GetSubordinateCSR(context.Context, *connect.Request[v1.GetSubordinateCSRRequest]) (*connect.Response[v1.GetSubordinateCSRResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.GetSubordinateCSR is not implemented"))
}

func (UnimplementedNodeServiceHandler) SubmitSubordinateCertificate(context.Context, *connect.Request[v1.SubmitSubordinateCertificateRequest]) (*connect.Response[v1.SubmitSubordinateCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.SubmitSubordinateCertificate is not implemented"))
}

func (UnimplementedNodeServiceHandler) RevokeCertificate(context.Context, *connect.Request[v1.RevokeCertificateRequest]) (*connect.Response[v1.RevokeCertificateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.RevokeCertificate is not implemented"))
}

func (UnimplementedNodeServiceHandler) ListIssued(context.Context, *connect.Request[v1.ListIssuedRequest]) (*connect.Response[v1.ListIssuedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.ListIssued is not implemented"))
}

func (UnimplementedNodeServiceHandler) ListRevocations(context.Context, *connect.Request[v1.ListRevocationsRequest]) (*connect.Response[v1.ListRevocationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.ListRevocations is not implemented"))
}

func (UnimplementedNodeServiceHandler) ExportCAKey(context.Context, *connect.Request[v1.ExportCAKeyRequest]) (*connect.Response[v1.ExportCAKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.ExportCAKey is not implemented"))
}

func (UnimplementedNodeServiceHandler) ImportCAKey(context.Context, *connect.Request[v1.ImportCAKeyRequest]) (*connect.Response[v1.ImportCAKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.ImportCAKey is not implemented"))
}

func (UnimplementedNodeServiceHandler) BeginKeyRotation(context.Context, *connect.Request[v1.BeginKeyRotationRequest]) (*connect.Response[v1.BeginKeyRotationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.BeginKeyRotation is not implemented"))
}

func (UnimplementedNodeServiceHandler) CompleteKeyRotation(context.Context, *connect.Request[v1.CompleteKeyRotationRequest]) (*connect.Response[v1.CompleteKeyRotationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.CompleteKeyRotation is not implemented"))
}

func (UnimplementedNodeServiceHandler) Reset(context.Context, *connect.Request[v1.ResetRequest]) (*connect.Response[v1.ResetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cryptos.v1.NodeService.Reset is not implemented"))
}
