// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: cryptos/fleet/v1/fleet.proto

package fleetv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetService_ListNodes_FullMethodName                = "/cryptos.fleet.v1.FleetService/ListNodes"
	FleetService_GetNode_FullMethodName                  = "/cryptos.fleet.v1.FleetService/GetNode"
	FleetService_ListCertificates_FullMethodName         = "/cryptos.fleet.v1.FleetService/ListCertificates"
	FleetService_ListProfiles_FullMethodName             = "/cryptos.fleet.v1.FleetService/ListProfiles"
	FleetService_CreateProfile_FullMethodName            = "/cryptos.fleet.v1.FleetService/CreateProfile"
	FleetService_UpdateProfile_FullMethodName            = "/cryptos.fleet.v1.FleetService/UpdateProfile"
	FleetService_DeleteProfile_FullMethodName            = "/cryptos.fleet.v1.FleetService/DeleteProfile"
	FleetService_ApplyProfileToNode_FullMethodName       = "/cryptos.fleet.v1.FleetService/ApplyProfileToNode"
	FleetService_ListAdapters_FullMethodName             = "/cryptos.fleet.v1.FleetService/ListAdapters"
	FleetService_SetAdapterEnabled_FullMethodName        = "/cryptos.fleet.v1.FleetService/SetAdapterEnabled"
	FleetService_ListAudit_FullMethodName                = "/cryptos.fleet.v1.FleetService/ListAudit"
	FleetService_ListEnrollments_FullMethodName          = "/cryptos.fleet.v1.FleetService/ListEnrollments"
	FleetService_CreateEnrollment_FullMethodName         = "/cryptos.fleet.v1.FleetService/CreateEnrollment"
	FleetService_ApproveEnrollment_FullMethodName        = "/cryptos.fleet.v1.FleetService/ApproveEnrollment"
	FleetService_RejectEnrollment_FullMethodName         = "/cryptos.fleet.v1.FleetService/RejectEnrollment"
	FleetService_WhoAmI_FullMethodName                   = "/cryptos.fleet.v1.FleetService/WhoAmI"
	FleetService_RevokeCertificate_FullMethodName        = "/cryptos.fleet.v1.FleetService/RevokeCertificate"
	FleetService_IssueLeaf_FullMethodName                = "/cryptos.fleet.v1.FleetService/IssueLeaf"
	FleetService_RekeyNode_FullMethodName                = "/cryptos.fleet.v1.FleetService/RekeyNode"
	FleetService_GetNodeConfig_FullMethodName            = "/cryptos.fleet.v1.FleetService/GetNodeConfig"
	FleetService_ApplyNodeConfig_FullMethodName          = "/cryptos.fleet.v1.FleetService/ApplyNodeConfig"
	FleetService_ExportCAKey_FullMethodName              = "/cryptos.fleet.v1.FleetService/ExportCAKey"
	FleetService_ImportCAKey_FullMethodName              = "/cryptos.fleet.v1.FleetService/ImportCAKey"
	FleetService_IssueOperatorCredential_FullMethodName  = "/cryptos.fleet.v1.FleetService/IssueOperatorCredential"
	FleetService_RevokeOperatorCredential_FullMethodName = "/cryptos.fleet.v1.FleetService/RevokeOperatorCredential"
	FleetService_ListOperatorCredentials_FullMethodName  = "/cryptos.fleet.v1.FleetService/ListOperatorCredentials"
	FleetService_PreviewAdoption_FullMethodName          = "/cryptos.fleet.v1.FleetService/PreviewAdoption"
	FleetService_AdoptNode_FullMethodName                = "/cryptos.fleet.v1.FleetService/AdoptNode"
	FleetService_DecommissionNode_FullMethodName         = "/cryptos.fleet.v1.FleetService/DecommissionNode"
)

// FleetServiceClient is the client API for FleetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FleetService is the Fleet Manager's surface over a set of CryptOS nodes:
// read aggregation (status, identity, certificates, catalog) plus the
// operator-driven enrollment writes. A single Connect endpoint for the
// manager's web UI.
type FleetServiceClient interface {
	// ListNodes returns a summary for every node the manager knows about.
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// GetNode returns full detail, including the identity chain, for one node.
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// ListCertificates returns the aggregated certificate set across nodes,
	// optionally scoped to a single node.
	ListCertificates(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error)
	// ListProfiles returns the manager's catalog of certificate issuance
	// profiles. Each is a cryptos.v1.CertificateProfile, the same shape a node
	// stores in pki.profiles[], so the catalog is a lossless superset the node
	// accepts verbatim. Operator-readable.
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	// CreateProfile adds a new certificate profile to the manager's catalog.
	// The profile name must be unique. Admin-gated and audited.
	CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error)
	// UpdateProfile replaces an existing catalog profile, matched by name.
	// Admin-gated and audited.
	UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error)
	// DeleteProfile removes a catalog profile by name. Non-cascading: it does
	// not touch any node's existing pki.profiles[]. Admin-gated and audited.
	DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error)
	// ApplyProfileToNode pushes a catalog profile onto a managed node: the
	// manager fetches the node's full config, inserts-or-replaces the named
	// profile in pki.profiles[] (matched by name), and applies the whole config
	// back via the node's ApplyConfig. Admin-gated and audited.
	ApplyProfileToNode(ctx context.Context, in *ApplyProfileToNodeRequest, opts ...grpc.CallOption) (*ApplyProfileToNodeResponse, error)
	// ListAdapters returns the manager's catalog of enrollment protocol
	// adapters.
	ListAdapters(ctx context.Context, in *ListAdaptersRequest, opts ...grpc.CallOption) (*ListAdaptersResponse, error)
	// SetAdapterEnabled records whether an enrollment protocol adapter is
	// enabled, matched by adapter name. This persists intent; the protocol
	// engines that serve enrollment requests ship in a later program, so an
	// enabled adapter does not yet answer requests. Admin-gated and audited.
	SetAdapterEnabled(ctx context.Context, in *SetAdapterEnabledRequest, opts ...grpc.CallOption) (*SetAdapterEnabledResponse, error)
	// ListAudit returns the manager's audit log.
	ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error)
	// ListEnrollments returns the manager's pending and resolved enrollment
	// requests.
	ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error)
	// CreateEnrollment opens a new enrollment request (LINK a node or provision a
	// SUBORDINATE CA); the manager verifies attestation for LINK.
	CreateEnrollment(ctx context.Context, in *CreateEnrollmentRequest, opts ...grpc.CallOption) (*CreateEnrollmentResponse, error)
	// ApproveEnrollment approves a pending request (LINK -> ApplyConfig managed
	// state; SUBORDINATE -> CSR-ferry).
	ApproveEnrollment(ctx context.Context, in *ApproveEnrollmentRequest, opts ...grpc.CallOption) (*ApproveEnrollmentResponse, error)
	// RejectEnrollment rejects a pending request with a reason.
	RejectEnrollment(ctx context.Context, in *RejectEnrollmentRequest, opts ...grpc.CallOption) (*RejectEnrollmentResponse, error)
	// WhoAmI echoes the operator identity the manager verified from the
	// presented client certificate (subject CN, cert serial, access level).
	WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error)
	// RevokeCertificate revokes an issued certificate on the node that issued
	// it, identified by node name and hex serial, with an RFC 5280 reason code.
	RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error)
	// IssueLeaf signs a leaf certificate on the named issuing node from a
	// browser-generated PKCS#10 CSR under a named issuance profile. Only the
	// CSR crosses the wire; the leaf private key stays in the browser.
	IssueLeaf(ctx context.Context, in *IssueLeafRequest, opts ...grpc.CallOption) (*IssueLeafResponse, error)
	// RekeyNode re-keys a subordinate CA node in one orchestrated call: the
	// manager has the child mint a new key + CSR, routes the CSR to the parent
	// (resolved from the child's issuer CN) for signing under profile_name, and
	// delivers the signed chain back to the child. The parent must be a node the
	// manager already knows about.
	RekeyNode(ctx context.Context, in *RekeyNodeRequest, opts ...grpc.CallOption) (*RekeyNodeResponse, error)
	// GetNodeConfig fetches the current machine configuration of a managed node,
	// so an operator can view it (and the web can edit a subset before applying
	// the whole config back). Operator-gated; a read, so it is not audited.
	GetNodeConfig(ctx context.Context, in *GetNodeConfigRequest, opts ...grpc.CallOption) (*GetNodeConfigResponse, error)
	// ApplyNodeConfig applies a full machine configuration to a managed node.
	// The config is the fetched baseline with the operator's edits merged in; the
	// node's ApplyConfig is a whole-config replace, so the caller must send the
	// complete config, never a partial one. Admin-gated and audited.
	ApplyNodeConfig(ctx context.Context, in *ApplyNodeConfigRequest, opts ...grpc.CallOption) (*ApplyNodeConfigResponse, error)
	// ExportCAKey backs up a managed node's CA private key to an encrypted
	// envelope. The node seals the backup with the operator passphrase
	// (Argon2id + AES-256-GCM) so the plaintext key never leaves the node; the
	// manager only relays the envelope through to the caller. The passphrase is
	// used in transit and is never persisted. A TPM-backed node refuses export.
	// Admin-gated and audited (the audit names the node only, never the secret).
	ExportCAKey(ctx context.Context, in *ExportCAKeyRequest, opts ...grpc.CallOption) (*ExportCAKeyResponse, error)
	// ImportCAKey restores a CA identity onto a fresh managed node from an
	// encrypted envelope produced by ExportCAKey. The node decrypts the envelope
	// with the operator passphrase and adopts the key; it refuses the import if
	// it already holds an identity. The passphrase transits the manager only to
	// reach the node and is never persisted. Admin-gated and audited (the audit
	// names the node and restored subject only, never the secret or envelope).
	ImportCAKey(ctx context.Context, in *ImportCAKeyRequest, opts ...grpc.CallOption) (*ImportCAKeyResponse, error)
	// IssueOperatorCredential issues an operator client certificate. The browser
	// generates the key and CSR; the manager routes signing to the node acting as
	// the operator CA under an operator-<level> profile that carries the
	// access-level extension. Only the CSR crosses the wire; the operator key
	// stays in the browser. Admin-gated and audited (the audit names the subject
	// and serial only, never the CSR or certificate bytes).
	IssueOperatorCredential(ctx context.Context, in *IssueOperatorCredentialRequest, opts ...grpc.CallOption) (*IssueOperatorCredentialResponse, error)
	// RevokeOperatorCredential revokes an operator credential on the operator-CA
	// node by hex serial, with an RFC 5280 reason code. The manager enforces the
	// revocation in the authz middleware, so a revoked operator can no longer
	// authenticate. Admin-gated and audited.
	RevokeOperatorCredential(ctx context.Context, in *RevokeOperatorCredentialRequest, opts ...grpc.CallOption) (*RevokeOperatorCredentialResponse, error)
	// ListOperatorCredentials returns the operator credentials the manager has
	// issued, with their level, expiry, and revocation state. Operator-readable.
	ListOperatorCredentials(ctx context.Context, in *ListOperatorCredentialsRequest, opts ...grpc.CallOption) (*ListOperatorCredentialsResponse, error)
	// PreviewAdoption performs the trust-on-first-use step of adopting a new
	// node: it dials the maintenance endpoint (no pin yet), captures the
	// self-signed certificate the node presents, and returns its SHA-256
	// fingerprint and subject so the operator can confirm it before adoption.
	// Admin-gated; a read, so it is not audited.
	PreviewAdoption(ctx context.Context, in *PreviewAdoptionRequest, opts ...grpc.CallOption) (*PreviewAdoptionResponse, error)
	// AdoptNode provisions a new maintenance node end to end and streams progress.
	// Pinned to the fingerprint the operator confirmed via PreviewAdoption, the
	// manager applies the initial config, awaits the reboot, drives the first-boot
	// ceremony, and registers the node. Each streamed message carries a phase
	// (applying-config, installing, awaiting-reboot, ceremony, established) with
	// human-readable detail; the final message sets done. Admin-gated and audited.
	AdoptNode(ctx context.Context, in *AdoptNodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AdoptNodeResponse], error)
	// DecommissionNode remotely wipes a managed node's identity and data via the
	// node's mTLS-served RemoteReset, then reboots it into maintenance. The caller
	// must echo the node's current Root CA CN as confirmation. Admin-gated and
	// audited (the audit names the node and that it was wiped, never any secret).
	DecommissionNode(ctx context.Context, in *DecommissionNodeRequest, opts ...grpc.CallOption) (*DecommissionNodeResponse, error)
}

type fleetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetServiceClient(cc grpc.ClientConnInterface) FleetServiceClient {
	return &fleetServiceClient{cc}
}

func (c *fleetServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, FleetService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, FleetService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListCertificates(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCertificatesResponse)
	err := c.cc.Invoke(ctx, FleetService_ListCertificates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, FleetService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) CreateProfile(ctx context.Context, in *CreateProfileRequest, opts ...grpc.CallOption) (*CreateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProfileResponse)
	err := c.cc.Invoke(ctx, FleetService_CreateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*UpdateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResponse)
	err := c.cc.Invoke(ctx, FleetService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) DeleteProfile(ctx context.Context, in *DeleteProfileRequest, opts ...grpc.CallOption) (*DeleteProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteProfileResponse)
	err := c.cc.Invoke(ctx, FleetService_DeleteProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ApplyProfileToNode(ctx context.Context, in *ApplyProfileToNodeRequest, opts ...grpc.CallOption) (*ApplyProfileToNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyProfileToNodeResponse)
	err := c.cc.Invoke(ctx, FleetService_ApplyProfileToNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListAdapters(ctx context.Context, in *ListAdaptersRequest, opts ...grpc.CallOption) (*ListAdaptersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdaptersResponse)
	err := c.cc.Invoke(ctx, FleetService_ListAdapters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) SetAdapterEnabled(ctx context.Context, in *SetAdapterEnabledRequest, opts ...grpc.CallOption) (*SetAdapterEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAdapterEnabledResponse)
	err := c.cc.Invoke(ctx, FleetService_SetAdapterEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditResponse)
	err := c.cc.Invoke(ctx, FleetService_ListAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrollmentsResponse)
	err := c.cc.Invoke(ctx, FleetService_ListEnrollments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) CreateEnrollment(ctx context.Context, in *CreateEnrollmentRequest, opts ...grpc.CallOption) (*CreateEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEnrollmentResponse)
	err := c.cc.Invoke(ctx, FleetService_CreateEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ApproveEnrollment(ctx context.Context, in *ApproveEnrollmentRequest, opts ...grpc.CallOption) (*ApproveEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveEnrollmentResponse)
	err := c.cc.Invoke(ctx, FleetService_ApproveEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RejectEnrollment(ctx context.Context, in *RejectEnrollmentRequest, opts ...grpc.CallOption) (*RejectEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectEnrollmentResponse)
	err := c.cc.Invoke(ctx, FleetService_RejectEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, FleetService_WhoAmI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCertificateResponse)
	err := c.cc.Invoke(ctx, FleetService_RevokeCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) IssueLeaf(ctx context.Context, in *IssueLeafRequest, opts ...grpc.CallOption) (*IssueLeafResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueLeafResponse)
	err := c.cc.Invoke(ctx, FleetService_IssueLeaf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RekeyNode(ctx context.Context, in *RekeyNodeRequest, opts ...grpc.CallOption) (*RekeyNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RekeyNodeResponse)
	err := c.cc.Invoke(ctx, FleetService_RekeyNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetNodeConfig(ctx context.Context, in *GetNodeConfigRequest, opts ...grpc.CallOption) (*GetNodeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeConfigResponse)
	err := c.cc.Invoke(ctx, FleetService_GetNodeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ApplyNodeConfig(ctx context.Context, in *ApplyNodeConfigRequest, opts ...grpc.CallOption) (*ApplyNodeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyNodeConfigResponse)
	err := c.cc.Invoke(ctx, FleetService_ApplyNodeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ExportCAKey(ctx context.Context, in *ExportCAKeyRequest, opts ...grpc.CallOption) (*ExportCAKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportCAKeyResponse)
	err := c.cc.Invoke(ctx, FleetService_ExportCAKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ImportCAKey(ctx context.Context, in *ImportCAKeyRequest, opts ...grpc.CallOption) (*ImportCAKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportCAKeyResponse)
	err := c.cc.Invoke(ctx, FleetService_ImportCAKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) IssueOperatorCredential(ctx context.Context, in *IssueOperatorCredentialRequest, opts ...grpc.CallOption) (*IssueOperatorCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueOperatorCredentialResponse)
	err := c.cc.Invoke(ctx, FleetService_IssueOperatorCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RevokeOperatorCredential(ctx context.Context, in *RevokeOperatorCredentialRequest, opts ...grpc.CallOption) (*RevokeOperatorCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeOperatorCredentialResponse)
	err := c.cc.Invoke(ctx, FleetService_RevokeOperatorCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListOperatorCredentials(ctx context.Context, in *ListOperatorCredentialsRequest, opts ...grpc.CallOption) (*ListOperatorCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperatorCredentialsResponse)
	err := c.cc.Invoke(ctx, FleetService_ListOperatorCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) PreviewAdoption(ctx context.Context, in *PreviewAdoptionRequest, opts ...grpc.CallOption) (*PreviewAdoptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewAdoptionResponse)
	err := c.cc.Invoke(ctx, FleetService_PreviewAdoption_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) AdoptNode(ctx context.Context, in *AdoptNodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AdoptNodeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FleetService_ServiceDesc.Streams[0], FleetService_AdoptNode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AdoptNodeRequest, AdoptNodeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_AdoptNodeClient = grpc.ServerStreamingClient[AdoptNodeResponse]

func (c *fleetServiceClient) DecommissionNode(ctx context.Context, in *DecommissionNodeRequest, opts ...grpc.CallOption) (*DecommissionNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecommissionNodeResponse)
	err := c.cc.Invoke(ctx, FleetService_DecommissionNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetServiceServer is the server API for FleetService service.
// All implementations should embed UnimplementedFleetServiceServer
// for forward compatibility.
//
// FleetService is the Fleet Manager's surface over a set of CryptOS nodes:
// read aggregation (status, identity, certificates, catalog) plus the
// operator-driven enrollment writes. A single Connect endpoint for the
// manager's web UI.
type FleetServiceServer interface {
	// ListNodes returns a summary for every node the manager knows about.
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// GetNode returns full detail, including the identity chain, for one node.
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// ListCertificates returns the aggregated certificate set across nodes,
	// optionally scoped to a single node.
	ListCertificates(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error)
	// ListProfiles returns the manager's catalog of certificate issuance
	// profiles. Each is a cryptos.v1.CertificateProfile, the same shape a node
	// stores in pki.profiles[], so the catalog is a lossless superset the node
	// accepts verbatim. Operator-readable.
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	// CreateProfile adds a new certificate profile to the manager's catalog.
	// The profile name must be unique. Admin-gated and audited.
	CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error)
	// UpdateProfile replaces an existing catalog profile, matched by name.
	// Admin-gated and audited.
	UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error)
	// DeleteProfile removes a catalog profile by name. Non-cascading: it does
	// not touch any node's existing pki.profiles[]. Admin-gated and audited.
	DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error)
	// ApplyProfileToNode pushes a catalog profile onto a managed node: the
	// manager fetches the node's full config, inserts-or-replaces the named
	// profile in pki.profiles[] (matched by name), and applies the whole config
	// back via the node's ApplyConfig. Admin-gated and audited.
	ApplyProfileToNode(context.Context, *ApplyProfileToNodeRequest) (*ApplyProfileToNodeResponse, error)
	// ListAdapters returns the manager's catalog of enrollment protocol
	// adapters.
	ListAdapters(context.Context, *ListAdaptersRequest) (*ListAdaptersResponse, error)
	// SetAdapterEnabled records whether an enrollment protocol adapter is
	// enabled, matched by adapter name. This persists intent; the protocol
	// engines that serve enrollment requests ship in a later program, so an
	// enabled adapter does not yet answer requests. Admin-gated and audited.
	SetAdapterEnabled(context.Context, *SetAdapterEnabledRequest) (*SetAdapterEnabledResponse, error)
	// ListAudit returns the manager's audit log.
	ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error)
	// ListEnrollments returns the manager's pending and resolved enrollment
	// requests.
	ListEnrollments(context.Context, *ListEnrollmentsRequest) (*ListEnrollmentsResponse, error)
	// CreateEnrollment opens a new enrollment request (LINK a node or provision a
	// SUBORDINATE CA); the manager verifies attestation for LINK.
	CreateEnrollment(context.Context, *CreateEnrollmentRequest) (*CreateEnrollmentResponse, error)
	// ApproveEnrollment approves a pending request (LINK -> ApplyConfig managed
	// state; SUBORDINATE -> CSR-ferry).
	ApproveEnrollment(context.Context, *ApproveEnrollmentRequest) (*ApproveEnrollmentResponse, error)
	// RejectEnrollment rejects a pending request with a reason.
	RejectEnrollment(context.Context, *RejectEnrollmentRequest) (*RejectEnrollmentResponse, error)
	// WhoAmI echoes the operator identity the manager verified from the
	// presented client certificate (subject CN, cert serial, access level).
	WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error)
	// RevokeCertificate revokes an issued certificate on the node that issued
	// it, identified by node name and hex serial, with an RFC 5280 reason code.
	RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error)
	// IssueLeaf signs a leaf certificate on the named issuing node from a
	// browser-generated PKCS#10 CSR under a named issuance profile. Only the
	// CSR crosses the wire; the leaf private key stays in the browser.
	IssueLeaf(context.Context, *IssueLeafRequest) (*IssueLeafResponse, error)
	// RekeyNode re-keys a subordinate CA node in one orchestrated call: the
	// manager has the child mint a new key + CSR, routes the CSR to the parent
	// (resolved from the child's issuer CN) for signing under profile_name, and
	// delivers the signed chain back to the child. The parent must be a node the
	// manager already knows about.
	RekeyNode(context.Context, *RekeyNodeRequest) (*RekeyNodeResponse, error)
	// GetNodeConfig fetches the current machine configuration of a managed node,
	// so an operator can view it (and the web can edit a subset before applying
	// the whole config back). Operator-gated; a read, so it is not audited.
	GetNodeConfig(context.Context, *GetNodeConfigRequest) (*GetNodeConfigResponse, error)
	// ApplyNodeConfig applies a full machine configuration to a managed node.
	// The config is the fetched baseline with the operator's edits merged in; the
	// node's ApplyConfig is a whole-config replace, so the caller must send the
	// complete config, never a partial one. Admin-gated and audited.
	ApplyNodeConfig(context.Context, *ApplyNodeConfigRequest) (*ApplyNodeConfigResponse, error)
	// ExportCAKey backs up a managed node's CA private key to an encrypted
	// envelope. The node seals the backup with the operator passphrase
	// (Argon2id + AES-256-GCM) so the plaintext key never leaves the node; the
	// manager only relays the envelope through to the caller. The passphrase is
	// used in transit and is never persisted. A TPM-backed node refuses export.
	// Admin-gated and audited (the audit names the node only, never the secret).
	ExportCAKey(context.Context, *ExportCAKeyRequest) (*ExportCAKeyResponse, error)
	// ImportCAKey restores a CA identity onto a fresh managed node from an
	// encrypted envelope produced by ExportCAKey. The node decrypts the envelope
	// with the operator passphrase and adopts the key; it refuses the import if
	// it already holds an identity. The passphrase transits the manager only to
	// reach the node and is never persisted. Admin-gated and audited (the audit
	// names the node and restored subject only, never the secret or envelope).
	ImportCAKey(context.Context, *ImportCAKeyRequest) (*ImportCAKeyResponse, error)
	// IssueOperatorCredential issues an operator client certificate. The browser
	// generates the key and CSR; the manager routes signing to the node acting as
	// the operator CA under an operator-<level> profile that carries the
	// access-level extension. Only the CSR crosses the wire; the operator key
	// stays in the browser. Admin-gated and audited (the audit names the subject
	// and serial only, never the CSR or certificate bytes).
	IssueOperatorCredential(context.Context, *IssueOperatorCredentialRequest) (*IssueOperatorCredentialResponse, error)
	// RevokeOperatorCredential revokes an operator credential on the operator-CA
	// node by hex serial, with an RFC 5280 reason code. The manager enforces the
	// revocation in the authz middleware, so a revoked operator can no longer
	// authenticate. Admin-gated and audited.
	RevokeOperatorCredential(context.Context, *RevokeOperatorCredentialRequest) (*RevokeOperatorCredentialResponse, error)
	// ListOperatorCredentials returns the operator credentials the manager has
	// issued, with their level, expiry, and revocation state. Operator-readable.
	ListOperatorCredentials(context.Context, *ListOperatorCredentialsRequest) (*ListOperatorCredentialsResponse, error)
	// PreviewAdoption performs the trust-on-first-use step of adopting a new
	// node: it dials the maintenance endpoint (no pin yet), captures the
	// self-signed certificate the node presents, and returns its SHA-256
	// fingerprint and subject so the operator can confirm it before adoption.
	// Admin-gated; a read, so it is not audited.
	PreviewAdoption(context.Context, *PreviewAdoptionRequest) (*PreviewAdoptionResponse, error)
	// AdoptNode provisions a new maintenance node end to end and streams progress.
	// Pinned to the fingerprint the operator confirmed via PreviewAdoption, the
	// manager applies the initial config, awaits the reboot, drives the first-boot
	// ceremony, and registers the node. Each streamed message carries a phase
	// (applying-config, installing, awaiting-reboot, ceremony, established) with
	// human-readable detail; the final message sets done. Admin-gated and audited.
	AdoptNode(*AdoptNodeRequest, grpc.ServerStreamingServer[AdoptNodeResponse]) error
	// DecommissionNode remotely wipes a managed node's identity and data via the
	// node's mTLS-served RemoteReset, then reboots it into maintenance. The caller
	// must echo the node's current Root CA CN as confirmation. Admin-gated and
	// audited (the audit names the node and that it was wiped, never any secret).
	DecommissionNode(context.Context, *DecommissionNodeRequest) (*DecommissionNodeResponse, error)
}

// UnimplementedFleetServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetServiceServer struct{}

func (UnimplementedFleetServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedFleetServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedFleetServiceServer) ListCertificates(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCertificates not implemented")
}
func (UnimplementedFleetServiceServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedFleetServiceServer) CreateProfile(context.Context, *CreateProfileRequest) (*CreateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProfile not implemented")
}
func (UnimplementedFleetServiceServer) UpdateProfile(context.Context, *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedFleetServiceServer) DeleteProfile(context.Context, *DeleteProfileRequest) (*DeleteProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProfile not implemented")
}
func (UnimplementedFleetServiceServer) ApplyProfileToNode(context.Context, *ApplyProfileToNodeRequest) (*ApplyProfileToNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyProfileToNode not implemented")
}
func (UnimplementedFleetServiceServer) ListAdapters(context.Context, *ListAdaptersRequest) (*ListAdaptersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdapters not implemented")
}
func (UnimplementedFleetServiceServer) SetAdapterEnabled(context.Context, *SetAdapterEnabledRequest) (*SetAdapterEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAdapterEnabled not implemented")
}
func (UnimplementedFleetServiceServer) ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAudit not implemented")
}
func (UnimplementedFleetServiceServer) ListEnrollments(context.Context, *ListEnrollmentsRequest) (*ListEnrollmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnrollments not implemented")
}
func (UnimplementedFleetServiceServer) CreateEnrollment(context.Context, *CreateEnrollmentRequest) (*CreateEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnrollment not implemented")
}
func (UnimplementedFleetServiceServer) ApproveEnrollment(context.Context, *ApproveEnrollmentRequest) (*ApproveEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveEnrollment not implemented")
}
func (UnimplementedFleetServiceServer) RejectEnrollment(context.Context, *RejectEnrollmentRequest) (*RejectEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectEnrollment not implemented")
}
func (UnimplementedFleetServiceServer) WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedFleetServiceServer) RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeCertificate not implemented")
}
func (UnimplementedFleetServiceServer) IssueLeaf(context.Context, *IssueLeafRequest) (*IssueLeafResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueLeaf not implemented")
}
func (UnimplementedFleetServiceServer) RekeyNode(context.Context, *RekeyNodeRequest) (*RekeyNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RekeyNode not implemented")
}
func (UnimplementedFleetServiceServer) GetNodeConfig(context.Context, *GetNodeConfigRequest) (*GetNodeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeConfig not implemented")
}
func (UnimplementedFleetServiceServer) ApplyNodeConfig(context.Context, *ApplyNodeConfigRequest) (*ApplyNodeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyNodeConfig not implemented")
}
func (UnimplementedFleetServiceServer) ExportCAKey(context.Context, *ExportCAKeyRequest) (*ExportCAKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportCAKey not implemented")
}
func (UnimplementedFleetServiceServer) ImportCAKey(context.Context, *ImportCAKeyRequest) (*ImportCAKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportCAKey not implemented")
}
func (UnimplementedFleetServiceServer) IssueOperatorCredential(context.Context, *IssueOperatorCredentialRequest) (*IssueOperatorCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueOperatorCredential not implemented")
}
func (UnimplementedFleetServiceServer) RevokeOperatorCredential(context.Context, *RevokeOperatorCredentialRequest) (*RevokeOperatorCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeOperatorCredential not implemented")
}
func (UnimplementedFleetServiceServer) ListOperatorCredentials(context.Context, *ListOperatorCredentialsRequest) (*ListOperatorCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOperatorCredentials not implemented")
}
func (UnimplementedFleetServiceServer) PreviewAdoption(context.Context, *PreviewAdoptionRequest) (*PreviewAdoptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewAdoption not implemented")
}
func (UnimplementedFleetServiceServer) AdoptNode(*AdoptNodeRequest, grpc.ServerStreamingServer[AdoptNodeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method AdoptNode not implemented")
}
func (UnimplementedFleetServiceServer) DecommissionNode(context.Context, *DecommissionNodeRequest) (*DecommissionNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecommissionNode not implemented")
}
func (UnimplementedFleetServiceServer) testEmbeddedByValue() {}

// UnsafeFleetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetServiceServer will
// result in compilation errors.
type UnsafeFleetServiceServer interface {
	mustEmbedUnimplementedFleetServiceServer()
}

func RegisterFleetServiceServer(s grpc.ServiceRegistrar, srv FleetServiceServer) {
	// If the following call pancis, it indicates UnimplementedFleetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetService_ServiceDesc, srv)
}

func _FleetService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListCertificates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertificatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListCertificates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListCertificates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListCertificates(ctx, req.(*ListCertificatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_CreateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CreateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CreateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CreateProfile(ctx, req.(*CreateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).UpdateProfile(ctx, req.(*UpdateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_DeleteProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).DeleteProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_DeleteProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).DeleteProfile(ctx, req.(*DeleteProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ApplyProfileToNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyProfileToNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ApplyProfileToNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ApplyProfileToNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ApplyProfileToNode(ctx, req.(*ApplyProfileToNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListAdapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdaptersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListAdapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListAdapters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListAdapters(ctx, req.(*ListAdaptersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_SetAdapterEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdapterEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).SetAdapterEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_SetAdapterEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).SetAdapterEnabled(ctx, req.(*SetAdapterEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListAudit(ctx, req.(*ListAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListEnrollments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrollmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListEnrollments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListEnrollments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListEnrollments(ctx, req.(*ListEnrollmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_CreateEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CreateEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CreateEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CreateEnrollment(ctx, req.(*CreateEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ApproveEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ApproveEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ApproveEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ApproveEnrollment(ctx, req.(*ApproveEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RejectEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RejectEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RejectEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RejectEnrollment(ctx, req.(*RejectEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_WhoAmI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).WhoAmI(ctx, req.(*WhoAmIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RevokeCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RevokeCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RevokeCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RevokeCertificate(ctx, req.(*RevokeCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_IssueLeaf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueLeafRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).IssueLeaf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_IssueLeaf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).IssueLeaf(ctx, req.(*IssueLeafRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RekeyNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RekeyNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RekeyNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RekeyNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RekeyNode(ctx, req.(*RekeyNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetNodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetNodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetNodeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetNodeConfig(ctx, req.(*GetNodeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ApplyNodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyNodeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ApplyNodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ApplyNodeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ApplyNodeConfig(ctx, req.(*ApplyNodeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ExportCAKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportCAKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ExportCAKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ExportCAKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ExportCAKey(ctx, req.(*ExportCAKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ImportCAKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportCAKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ImportCAKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ImportCAKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ImportCAKey(ctx, req.(*ImportCAKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_IssueOperatorCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueOperatorCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).IssueOperatorCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_IssueOperatorCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).IssueOperatorCredential(ctx, req.(*IssueOperatorCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RevokeOperatorCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeOperatorCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RevokeOperatorCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RevokeOperatorCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RevokeOperatorCredential(ctx, req.(*RevokeOperatorCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListOperatorCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperatorCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListOperatorCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListOperatorCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListOperatorCredentials(ctx, req.(*ListOperatorCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_PreviewAdoption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewAdoptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).PreviewAdoption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_PreviewAdoption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).PreviewAdoption(ctx, req.(*PreviewAdoptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_AdoptNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AdoptNodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetServiceServer).AdoptNode(m, &grpc.GenericServerStream[AdoptNodeRequest, AdoptNodeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FleetService_AdoptNodeServer = grpc.ServerStreamingServer[AdoptNodeResponse]

func _FleetService_DecommissionNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecommissionNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).DecommissionNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_DecommissionNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).DecommissionNode(ctx, req.(*DecommissionNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetService_ServiceDesc is the grpc.ServiceDesc for FleetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cryptos.fleet.v1.FleetService",
	HandlerType: (*FleetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNodes",
			Handler:    _FleetService_ListNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _FleetService_GetNode_Handler,
		},
		{
			MethodName: "ListCertificates",
			Handler:    _FleetService_ListCertificates_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _FleetService_ListProfiles_Handler,
		},
		{
			MethodName: "CreateProfile",
			Handler:    _FleetService_CreateProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _FleetService_UpdateProfile_Handler,
		},
		{
			MethodName: "DeleteProfile",
			Handler:    _FleetService_DeleteProfile_Handler,
		},
		{
			MethodName: "ApplyProfileToNode",
			Handler:    _FleetService_ApplyProfileToNode_Handler,
		},
		{
			MethodName: "ListAdapters",
			Handler:    _FleetService_ListAdapters_Handler,
		},
		{
			MethodName: "SetAdapterEnabled",
			Handler:    _FleetService_SetAdapterEnabled_Handler,
		},
		{
			MethodName: "ListAudit",
			Handler:    _FleetService_ListAudit_Handler,
		},
		{
			MethodName: "ListEnrollments",
			Handler:    _FleetService_ListEnrollments_Handler,
		},
		{
			MethodName: "CreateEnrollment",
			Handler:    _FleetService_CreateEnrollment_Handler,
		},
		{
			MethodName: "ApproveEnrollment",
			Handler:    _FleetService_ApproveEnrollment_Handler,
		},
		{
			MethodName: "RejectEnrollment",
			Handler:    _FleetService_RejectEnrollment_Handler,
		},
		{
			MethodName: "WhoAmI",
			Handler:    _FleetService_WhoAmI_Handler,
		},
		{
			MethodName: "RevokeCertificate",
			Handler:    _FleetService_RevokeCertificate_Handler,
		},
		{
			MethodName: "IssueLeaf",
			Handler:    _FleetService_IssueLeaf_Handler,
		},
		{
			MethodName: "RekeyNode",
			Handler:    _FleetService_RekeyNode_Handler,
		},
		{
			MethodName: "GetNodeConfig",
			Handler:    _FleetService_GetNodeConfig_Handler,
		},
		{
			MethodName: "ApplyNodeConfig",
			Handler:    _FleetService_ApplyNodeConfig_Handler,
		},
		{
			MethodName: "ExportCAKey",
			Handler:    _FleetService_ExportCAKey_Handler,
		},
		{
			MethodName: "ImportCAKey",
			Handler:    _FleetService_ImportCAKey_Handler,
		},
		{
			MethodName: "IssueOperatorCredential",
			Handler:    _FleetService_IssueOperatorCredential_Handler,
		},
		{
			MethodName: "RevokeOperatorCredential",
			Handler:    _FleetService_RevokeOperatorCredential_Handler,
		},
		{
			MethodName: "ListOperatorCredentials",
			Handler:    _FleetService_ListOperatorCredentials_Handler,
		},
		{
			MethodName: "PreviewAdoption",
			Handler:    _FleetService_PreviewAdoption_Handler,
		},
		{
			MethodName: "DecommissionNode",
			Handler:    _FleetService_DecommissionNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AdoptNode",
			Handler:       _FleetService_AdoptNode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cryptos/fleet/v1/fleet.proto",
}
