// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: cryptos/fleet/v1/fleet.proto

package fleetv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetService_ListNodes_FullMethodName         = "/cryptos.fleet.v1.FleetService/ListNodes"
	FleetService_GetNode_FullMethodName           = "/cryptos.fleet.v1.FleetService/GetNode"
	FleetService_ListCertificates_FullMethodName  = "/cryptos.fleet.v1.FleetService/ListCertificates"
	FleetService_ListProfiles_FullMethodName      = "/cryptos.fleet.v1.FleetService/ListProfiles"
	FleetService_ListAdapters_FullMethodName      = "/cryptos.fleet.v1.FleetService/ListAdapters"
	FleetService_ListAudit_FullMethodName         = "/cryptos.fleet.v1.FleetService/ListAudit"
	FleetService_ListEnrollments_FullMethodName   = "/cryptos.fleet.v1.FleetService/ListEnrollments"
	FleetService_CreateEnrollment_FullMethodName  = "/cryptos.fleet.v1.FleetService/CreateEnrollment"
	FleetService_ApproveEnrollment_FullMethodName = "/cryptos.fleet.v1.FleetService/ApproveEnrollment"
	FleetService_RejectEnrollment_FullMethodName  = "/cryptos.fleet.v1.FleetService/RejectEnrollment"
	FleetService_WhoAmI_FullMethodName            = "/cryptos.fleet.v1.FleetService/WhoAmI"
	FleetService_RevokeCertificate_FullMethodName = "/cryptos.fleet.v1.FleetService/RevokeCertificate"
	FleetService_IssueLeaf_FullMethodName         = "/cryptos.fleet.v1.FleetService/IssueLeaf"
	FleetService_RekeyNode_FullMethodName         = "/cryptos.fleet.v1.FleetService/RekeyNode"
	FleetService_GetNodeConfig_FullMethodName     = "/cryptos.fleet.v1.FleetService/GetNodeConfig"
	FleetService_ApplyNodeConfig_FullMethodName   = "/cryptos.fleet.v1.FleetService/ApplyNodeConfig"
)

// FleetServiceClient is the client API for FleetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FleetService is the Fleet Manager's surface over a set of CryptOS nodes:
// read aggregation (status, identity, certificates, catalog) plus the
// operator-driven enrollment writes. A single Connect endpoint for the
// manager's web UI.
type FleetServiceClient interface {
	// ListNodes returns a summary for every node the manager knows about.
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// GetNode returns full detail, including the identity chain, for one node.
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// ListCertificates returns the aggregated certificate set across nodes,
	// optionally scoped to a single node.
	ListCertificates(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error)
	// ListProfiles returns the manager's catalog of certificate issuance
	// profiles.
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	// ListAdapters returns the manager's catalog of enrollment protocol
	// adapters.
	ListAdapters(ctx context.Context, in *ListAdaptersRequest, opts ...grpc.CallOption) (*ListAdaptersResponse, error)
	// ListAudit returns the manager's audit log.
	ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error)
	// ListEnrollments returns the manager's pending and resolved enrollment
	// requests.
	ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error)
	// CreateEnrollment opens a new enrollment request (LINK a node or provision a
	// SUBORDINATE CA); the manager verifies attestation for LINK.
	CreateEnrollment(ctx context.Context, in *CreateEnrollmentRequest, opts ...grpc.CallOption) (*CreateEnrollmentResponse, error)
	// ApproveEnrollment approves a pending request (LINK -> ApplyConfig managed
	// state; SUBORDINATE -> CSR-ferry).
	ApproveEnrollment(ctx context.Context, in *ApproveEnrollmentRequest, opts ...grpc.CallOption) (*ApproveEnrollmentResponse, error)
	// RejectEnrollment rejects a pending request with a reason.
	RejectEnrollment(ctx context.Context, in *RejectEnrollmentRequest, opts ...grpc.CallOption) (*RejectEnrollmentResponse, error)
	// WhoAmI echoes the operator identity the manager verified from the
	// presented client certificate (subject CN, cert serial, access level).
	WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error)
	// RevokeCertificate revokes an issued certificate on the node that issued
	// it, identified by node name and hex serial, with an RFC 5280 reason code.
	RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error)
	// IssueLeaf signs a leaf certificate on the named issuing node from a
	// browser-generated PKCS#10 CSR under a named issuance profile. Only the
	// CSR crosses the wire; the leaf private key stays in the browser.
	IssueLeaf(ctx context.Context, in *IssueLeafRequest, opts ...grpc.CallOption) (*IssueLeafResponse, error)
	// RekeyNode re-keys a subordinate CA node in one orchestrated call: the
	// manager has the child mint a new key + CSR, routes the CSR to the parent
	// (resolved from the child's issuer CN) for signing under profile_name, and
	// delivers the signed chain back to the child. The parent must be a node the
	// manager already knows about.
	RekeyNode(ctx context.Context, in *RekeyNodeRequest, opts ...grpc.CallOption) (*RekeyNodeResponse, error)
	// GetNodeConfig fetches the current machine configuration of a managed node,
	// so an operator can view it (and the web can edit a subset before applying
	// the whole config back). Operator-gated; a read, so it is not audited.
	GetNodeConfig(ctx context.Context, in *GetNodeConfigRequest, opts ...grpc.CallOption) (*GetNodeConfigResponse, error)
	// ApplyNodeConfig applies a full machine configuration to a managed node.
	// The config is the fetched baseline with the operator's edits merged in; the
	// node's ApplyConfig is a whole-config replace, so the caller must send the
	// complete config, never a partial one. Admin-gated and audited.
	ApplyNodeConfig(ctx context.Context, in *ApplyNodeConfigRequest, opts ...grpc.CallOption) (*ApplyNodeConfigResponse, error)
}

type fleetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetServiceClient(cc grpc.ClientConnInterface) FleetServiceClient {
	return &fleetServiceClient{cc}
}

func (c *fleetServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, FleetService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, FleetService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListCertificates(ctx context.Context, in *ListCertificatesRequest, opts ...grpc.CallOption) (*ListCertificatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCertificatesResponse)
	err := c.cc.Invoke(ctx, FleetService_ListCertificates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, FleetService_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListAdapters(ctx context.Context, in *ListAdaptersRequest, opts ...grpc.CallOption) (*ListAdaptersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdaptersResponse)
	err := c.cc.Invoke(ctx, FleetService_ListAdapters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListAudit(ctx context.Context, in *ListAuditRequest, opts ...grpc.CallOption) (*ListAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditResponse)
	err := c.cc.Invoke(ctx, FleetService_ListAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ListEnrollments(ctx context.Context, in *ListEnrollmentsRequest, opts ...grpc.CallOption) (*ListEnrollmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrollmentsResponse)
	err := c.cc.Invoke(ctx, FleetService_ListEnrollments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) CreateEnrollment(ctx context.Context, in *CreateEnrollmentRequest, opts ...grpc.CallOption) (*CreateEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEnrollmentResponse)
	err := c.cc.Invoke(ctx, FleetService_CreateEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ApproveEnrollment(ctx context.Context, in *ApproveEnrollmentRequest, opts ...grpc.CallOption) (*ApproveEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveEnrollmentResponse)
	err := c.cc.Invoke(ctx, FleetService_ApproveEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RejectEnrollment(ctx context.Context, in *RejectEnrollmentRequest, opts ...grpc.CallOption) (*RejectEnrollmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RejectEnrollmentResponse)
	err := c.cc.Invoke(ctx, FleetService_RejectEnrollment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, FleetService_WhoAmI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RevokeCertificate(ctx context.Context, in *RevokeCertificateRequest, opts ...grpc.CallOption) (*RevokeCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCertificateResponse)
	err := c.cc.Invoke(ctx, FleetService_RevokeCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) IssueLeaf(ctx context.Context, in *IssueLeafRequest, opts ...grpc.CallOption) (*IssueLeafResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueLeafResponse)
	err := c.cc.Invoke(ctx, FleetService_IssueLeaf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) RekeyNode(ctx context.Context, in *RekeyNodeRequest, opts ...grpc.CallOption) (*RekeyNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RekeyNodeResponse)
	err := c.cc.Invoke(ctx, FleetService_RekeyNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) GetNodeConfig(ctx context.Context, in *GetNodeConfigRequest, opts ...grpc.CallOption) (*GetNodeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeConfigResponse)
	err := c.cc.Invoke(ctx, FleetService_GetNodeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetServiceClient) ApplyNodeConfig(ctx context.Context, in *ApplyNodeConfigRequest, opts ...grpc.CallOption) (*ApplyNodeConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyNodeConfigResponse)
	err := c.cc.Invoke(ctx, FleetService_ApplyNodeConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetServiceServer is the server API for FleetService service.
// All implementations should embed UnimplementedFleetServiceServer
// for forward compatibility.
//
// FleetService is the Fleet Manager's surface over a set of CryptOS nodes:
// read aggregation (status, identity, certificates, catalog) plus the
// operator-driven enrollment writes. A single Connect endpoint for the
// manager's web UI.
type FleetServiceServer interface {
	// ListNodes returns a summary for every node the manager knows about.
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// GetNode returns full detail, including the identity chain, for one node.
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// ListCertificates returns the aggregated certificate set across nodes,
	// optionally scoped to a single node.
	ListCertificates(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error)
	// ListProfiles returns the manager's catalog of certificate issuance
	// profiles.
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	// ListAdapters returns the manager's catalog of enrollment protocol
	// adapters.
	ListAdapters(context.Context, *ListAdaptersRequest) (*ListAdaptersResponse, error)
	// ListAudit returns the manager's audit log.
	ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error)
	// ListEnrollments returns the manager's pending and resolved enrollment
	// requests.
	ListEnrollments(context.Context, *ListEnrollmentsRequest) (*ListEnrollmentsResponse, error)
	// CreateEnrollment opens a new enrollment request (LINK a node or provision a
	// SUBORDINATE CA); the manager verifies attestation for LINK.
	CreateEnrollment(context.Context, *CreateEnrollmentRequest) (*CreateEnrollmentResponse, error)
	// ApproveEnrollment approves a pending request (LINK -> ApplyConfig managed
	// state; SUBORDINATE -> CSR-ferry).
	ApproveEnrollment(context.Context, *ApproveEnrollmentRequest) (*ApproveEnrollmentResponse, error)
	// RejectEnrollment rejects a pending request with a reason.
	RejectEnrollment(context.Context, *RejectEnrollmentRequest) (*RejectEnrollmentResponse, error)
	// WhoAmI echoes the operator identity the manager verified from the
	// presented client certificate (subject CN, cert serial, access level).
	WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error)
	// RevokeCertificate revokes an issued certificate on the node that issued
	// it, identified by node name and hex serial, with an RFC 5280 reason code.
	RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error)
	// IssueLeaf signs a leaf certificate on the named issuing node from a
	// browser-generated PKCS#10 CSR under a named issuance profile. Only the
	// CSR crosses the wire; the leaf private key stays in the browser.
	IssueLeaf(context.Context, *IssueLeafRequest) (*IssueLeafResponse, error)
	// RekeyNode re-keys a subordinate CA node in one orchestrated call: the
	// manager has the child mint a new key + CSR, routes the CSR to the parent
	// (resolved from the child's issuer CN) for signing under profile_name, and
	// delivers the signed chain back to the child. The parent must be a node the
	// manager already knows about.
	RekeyNode(context.Context, *RekeyNodeRequest) (*RekeyNodeResponse, error)
	// GetNodeConfig fetches the current machine configuration of a managed node,
	// so an operator can view it (and the web can edit a subset before applying
	// the whole config back). Operator-gated; a read, so it is not audited.
	GetNodeConfig(context.Context, *GetNodeConfigRequest) (*GetNodeConfigResponse, error)
	// ApplyNodeConfig applies a full machine configuration to a managed node.
	// The config is the fetched baseline with the operator's edits merged in; the
	// node's ApplyConfig is a whole-config replace, so the caller must send the
	// complete config, never a partial one. Admin-gated and audited.
	ApplyNodeConfig(context.Context, *ApplyNodeConfigRequest) (*ApplyNodeConfigResponse, error)
}

// UnimplementedFleetServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetServiceServer struct{}

func (UnimplementedFleetServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedFleetServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedFleetServiceServer) ListCertificates(context.Context, *ListCertificatesRequest) (*ListCertificatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCertificates not implemented")
}
func (UnimplementedFleetServiceServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedFleetServiceServer) ListAdapters(context.Context, *ListAdaptersRequest) (*ListAdaptersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAdapters not implemented")
}
func (UnimplementedFleetServiceServer) ListAudit(context.Context, *ListAuditRequest) (*ListAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAudit not implemented")
}
func (UnimplementedFleetServiceServer) ListEnrollments(context.Context, *ListEnrollmentsRequest) (*ListEnrollmentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEnrollments not implemented")
}
func (UnimplementedFleetServiceServer) CreateEnrollment(context.Context, *CreateEnrollmentRequest) (*CreateEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEnrollment not implemented")
}
func (UnimplementedFleetServiceServer) ApproveEnrollment(context.Context, *ApproveEnrollmentRequest) (*ApproveEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveEnrollment not implemented")
}
func (UnimplementedFleetServiceServer) RejectEnrollment(context.Context, *RejectEnrollmentRequest) (*RejectEnrollmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectEnrollment not implemented")
}
func (UnimplementedFleetServiceServer) WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedFleetServiceServer) RevokeCertificate(context.Context, *RevokeCertificateRequest) (*RevokeCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeCertificate not implemented")
}
func (UnimplementedFleetServiceServer) IssueLeaf(context.Context, *IssueLeafRequest) (*IssueLeafResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueLeaf not implemented")
}
func (UnimplementedFleetServiceServer) RekeyNode(context.Context, *RekeyNodeRequest) (*RekeyNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RekeyNode not implemented")
}
func (UnimplementedFleetServiceServer) GetNodeConfig(context.Context, *GetNodeConfigRequest) (*GetNodeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeConfig not implemented")
}
func (UnimplementedFleetServiceServer) ApplyNodeConfig(context.Context, *ApplyNodeConfigRequest) (*ApplyNodeConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyNodeConfig not implemented")
}
func (UnimplementedFleetServiceServer) testEmbeddedByValue() {}

// UnsafeFleetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetServiceServer will
// result in compilation errors.
type UnsafeFleetServiceServer interface {
	mustEmbedUnimplementedFleetServiceServer()
}

func RegisterFleetServiceServer(s grpc.ServiceRegistrar, srv FleetServiceServer) {
	// If the following call pancis, it indicates UnimplementedFleetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetService_ServiceDesc, srv)
}

func _FleetService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListCertificates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertificatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListCertificates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListCertificates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListCertificates(ctx, req.(*ListCertificatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListAdapters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdaptersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListAdapters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListAdapters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListAdapters(ctx, req.(*ListAdaptersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListAudit(ctx, req.(*ListAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ListEnrollments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrollmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ListEnrollments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ListEnrollments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ListEnrollments(ctx, req.(*ListEnrollmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_CreateEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).CreateEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_CreateEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).CreateEnrollment(ctx, req.(*CreateEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ApproveEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ApproveEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ApproveEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ApproveEnrollment(ctx, req.(*ApproveEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RejectEnrollment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectEnrollmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RejectEnrollment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RejectEnrollment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RejectEnrollment(ctx, req.(*RejectEnrollmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_WhoAmI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).WhoAmI(ctx, req.(*WhoAmIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RevokeCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RevokeCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RevokeCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RevokeCertificate(ctx, req.(*RevokeCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_IssueLeaf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueLeafRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).IssueLeaf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_IssueLeaf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).IssueLeaf(ctx, req.(*IssueLeafRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_RekeyNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RekeyNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).RekeyNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_RekeyNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).RekeyNode(ctx, req.(*RekeyNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_GetNodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).GetNodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_GetNodeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).GetNodeConfig(ctx, req.(*GetNodeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetService_ApplyNodeConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyNodeConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetServiceServer).ApplyNodeConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetService_ApplyNodeConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetServiceServer).ApplyNodeConfig(ctx, req.(*ApplyNodeConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetService_ServiceDesc is the grpc.ServiceDesc for FleetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cryptos.fleet.v1.FleetService",
	HandlerType: (*FleetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNodes",
			Handler:    _FleetService_ListNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _FleetService_GetNode_Handler,
		},
		{
			MethodName: "ListCertificates",
			Handler:    _FleetService_ListCertificates_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _FleetService_ListProfiles_Handler,
		},
		{
			MethodName: "ListAdapters",
			Handler:    _FleetService_ListAdapters_Handler,
		},
		{
			MethodName: "ListAudit",
			Handler:    _FleetService_ListAudit_Handler,
		},
		{
			MethodName: "ListEnrollments",
			Handler:    _FleetService_ListEnrollments_Handler,
		},
		{
			MethodName: "CreateEnrollment",
			Handler:    _FleetService_CreateEnrollment_Handler,
		},
		{
			MethodName: "ApproveEnrollment",
			Handler:    _FleetService_ApproveEnrollment_Handler,
		},
		{
			MethodName: "RejectEnrollment",
			Handler:    _FleetService_RejectEnrollment_Handler,
		},
		{
			MethodName: "WhoAmI",
			Handler:    _FleetService_WhoAmI_Handler,
		},
		{
			MethodName: "RevokeCertificate",
			Handler:    _FleetService_RevokeCertificate_Handler,
		},
		{
			MethodName: "IssueLeaf",
			Handler:    _FleetService_IssueLeaf_Handler,
		},
		{
			MethodName: "RekeyNode",
			Handler:    _FleetService_RekeyNode_Handler,
		},
		{
			MethodName: "GetNodeConfig",
			Handler:    _FleetService_GetNodeConfig_Handler,
		},
		{
			MethodName: "ApplyNodeConfig",
			Handler:    _FleetService_ApplyNodeConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cryptos/fleet/v1/fleet.proto",
}
